// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package assets

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAssetTag = `-- name: AddAssetTag :exec
INSERT INTO asset_tag (asset_id, tag)
VALUES ($1, $2)
ON CONFLICT (asset_id, tag) DO NOTHING
`

type AddAssetTagParams struct {
	AssetID pgtype.UUID
	Tag     string
}

func (q *Queries) AddAssetTag(ctx context.Context, arg AddAssetTagParams) error {
	_, err := q.db.Exec(ctx, addAssetTag, arg.AssetID, arg.Tag)
	return err
}

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    title, description, resource_type, owner_user_ref, status,
    file_hash, file_extension, file_size_bytes, metadata, origin_server_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, title, description, resource_type, owner_user_ref, status,
          file_hash, file_extension, file_size_bytes, metadata,
          origin_server_id, created_at, updated_at
`

type CreateAssetParams struct {
	Title          string
	Description    string
	ResourceType   int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Metadata       []byte
	OriginServerID pgtype.UUID
}

type CreateAssetRow struct {
	ID             pgtype.UUID
	Title          string
	Description    string
	ResourceType   int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Metadata       []byte
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (CreateAssetRow, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.Title,
		arg.Description,
		arg.ResourceType,
		arg.OwnerUserRef,
		arg.Status,
		arg.FileHash,
		arg.FileExtension,
		arg.FileSizeBytes,
		arg.Metadata,
		arg.OriginServerID,
	)
	var i CreateAssetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ResourceType,
		&i.OwnerUserRef,
		&i.Status,
		&i.FileHash,
		&i.FileExtension,
		&i.FileSizeBytes,
		&i.Metadata,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAsset = `-- name: GetAsset :one
SELECT id, title, description, resource_type, owner_user_ref, status,
       file_hash, file_extension, file_size_bytes, metadata,
       origin_server_id, created_at, updated_at
FROM assets
WHERE id = $1 AND deleted_at IS NULL
`

type GetAssetRow struct {
	ID             pgtype.UUID
	Title          string
	Description    string
	ResourceType   int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Metadata       []byte
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (GetAssetRow, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i GetAssetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ResourceType,
		&i.OwnerUserRef,
		&i.Status,
		&i.FileHash,
		&i.FileExtension,
		&i.FileSizeBytes,
		&i.Metadata,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssetTags = `-- name: ListAssetTags :many
SELECT tag FROM asset_tag WHERE asset_id = $1 ORDER BY tag
`

func (q *Queries) ListAssetTags(ctx context.Context, assetID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAssetTags, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByTagPage = `-- name: ListAssetsByTagPage :many
SELECT a.id, a.title, a.description, a.resource_type, a.owner_user_ref, a.status,
       a.file_hash, a.file_extension, a.file_size_bytes, a.metadata,
       a.origin_server_id, a.created_at, a.updated_at
FROM assets a
JOIN asset_tag t ON t.asset_id = a.id
WHERE a.deleted_at IS NULL
  AND t.tag = $1::TEXT
  AND ($2::BIGINT IS NULL OR a.owner_user_ref = $2::BIGINT)
  AND ($3::BIGINT  IS NULL OR a.resource_type  = $3::BIGINT)
  AND ($4::TEXT           IS NULL OR a.status          = $4::TEXT)
  AND ($5::TIMESTAMPTZ IS NULL
       OR a.created_at < $5::TIMESTAMPTZ
       OR (a.created_at = $5::TIMESTAMPTZ
           AND a.id < $6::UUID))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $7::INTEGER
`

type ListAssetsByTagPageParams struct {
	Tag             string
	OwnerUserRef    *int64
	ResourceType    *int64
	Status          *string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	RowLimit        int32
}

type ListAssetsByTagPageRow struct {
	ID             pgtype.UUID
	Title          string
	Description    string
	ResourceType   int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Metadata       []byte
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Same paginated list but constrained to a single tag. Separate
// query because the join breaks the COALESCE pattern.
func (q *Queries) ListAssetsByTagPage(ctx context.Context, arg ListAssetsByTagPageParams) ([]ListAssetsByTagPageRow, error) {
	rows, err := q.db.Query(ctx, listAssetsByTagPage,
		arg.Tag,
		arg.OwnerUserRef,
		arg.ResourceType,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsByTagPageRow
	for rows.Next() {
		var i ListAssetsByTagPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ResourceType,
			&i.OwnerUserRef,
			&i.Status,
			&i.FileHash,
			&i.FileExtension,
			&i.FileSizeBytes,
			&i.Metadata,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsPage = `-- name: ListAssetsPage :many
SELECT id, title, description, resource_type, owner_user_ref, status,
       file_hash, file_extension, file_size_bytes, metadata,
       origin_server_id, created_at, updated_at
FROM assets
WHERE deleted_at IS NULL
  AND ($1::BIGINT IS NULL OR owner_user_ref = $1::BIGINT)
  AND ($2::BIGINT  IS NULL OR resource_type  = $2::BIGINT)
  AND ($3::TEXT           IS NULL OR status          = $3::TEXT)
  AND ($4::TIMESTAMPTZ IS NULL
       OR created_at < $4::TIMESTAMPTZ
       OR (created_at = $4::TIMESTAMPTZ
           AND id < $5::UUID))
ORDER BY created_at DESC, id DESC
LIMIT $6::INTEGER
`

type ListAssetsPageParams struct {
	OwnerUserRef    *int64
	ResourceType    *int64
	Status          *string
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	RowLimit        int32
}

type ListAssetsPageRow struct {
	ID             pgtype.UUID
	Title          string
	Description    string
	ResourceType   int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Metadata       []byte
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Cursor pagination: rows newer than the cursor timestamp, plus tie-
// breaker on id. Filters are OR'd with NULL-checks so a single query
// covers all the optional-filter combinations.
func (q *Queries) ListAssetsPage(ctx context.Context, arg ListAssetsPageParams) ([]ListAssetsPageRow, error) {
	rows, err := q.db.Query(ctx, listAssetsPage,
		arg.OwnerUserRef,
		arg.ResourceType,
		arg.Status,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsPageRow
	for rows.Next() {
		var i ListAssetsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ResourceType,
			&i.OwnerUserRef,
			&i.Status,
			&i.FileHash,
			&i.FileExtension,
			&i.FileSizeBytes,
			&i.Metadata,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAssetTag = `-- name: RemoveAssetTag :exec
DELETE FROM asset_tag WHERE asset_id = $1 AND tag = $2
`

type RemoveAssetTagParams struct {
	AssetID pgtype.UUID
	Tag     string
}

func (q *Queries) RemoveAssetTag(ctx context.Context, arg RemoveAssetTagParams) error {
	_, err := q.db.Exec(ctx, removeAssetTag, arg.AssetID, arg.Tag)
	return err
}

const replaceAssetTags = `-- name: ReplaceAssetTags :exec
WITH wipe AS (
    DELETE FROM asset_tag WHERE asset_id = $1
)
INSERT INTO asset_tag (asset_id, tag)
SELECT $1, unnest($2::TEXT[])
ON CONFLICT (asset_id, tag) DO NOTHING
`

type ReplaceAssetTagsParams struct {
	AssetID pgtype.UUID
	Column2 []string
}

// Wipes and refills the tag set in one transaction. Called by
// AssetUpdate when the request body sends a `tags` array.
func (q *Queries) ReplaceAssetTags(ctx context.Context, arg ReplaceAssetTagsParams) error {
	_, err := q.db.Exec(ctx, replaceAssetTags, arg.AssetID, arg.Column2)
	return err
}

const softDeleteAsset = `-- name: SoftDeleteAsset :exec
UPDATE assets
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAsset, id)
	return err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets SET
    title       = COALESCE($1,       title),
    description = COALESCE($2, description),
    status      = COALESCE($3,      status),
    metadata    = COALESCE($4,    metadata),
    updated_at  = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, title, description, resource_type, owner_user_ref, status,
          file_hash, file_extension, file_size_bytes, metadata,
          origin_server_id, created_at, updated_at
`

type UpdateAssetParams struct {
	Title       *string
	Description *string
	Status      *string
	Metadata    []byte
	ID          pgtype.UUID
}

type UpdateAssetRow struct {
	ID             pgtype.UUID
	Title          string
	Description    string
	ResourceType   int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Metadata       []byte
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Partial update via COALESCE: any field passed as NULL keeps its
// current value. Tag changes go through a separate set of queries.
func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (UpdateAssetRow, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Metadata,
		arg.ID,
	)
	var i UpdateAssetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ResourceType,
		&i.OwnerUserRef,
		&i.Status,
		&i.FileHash,
		&i.FileExtension,
		&i.FileSizeBytes,
		&i.Metadata,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
