// Package jobs implements the ai.tag + ai.caption job handlers for
// the Phase 1.14.A inference fan-out. The handlers register with
// the jobs.Service.Registry at boot; assets.Handler enqueues one
// of each type per uploaded image/video as part of the existing
// post-upload fan-out (alongside ai.embed in 1.14.B and ai.transcribe
// in 1.14.C).
//
// Lives under app/internal/ai/ rather than app/internal/jobs/
// because the handler logic depends on ai.Router + the ai concern
// types — putting it in the jobs package would create a cycle
// (jobs is upstream of ai). The router/audit/cost machinery stays
// where it lives.
//
// Both handlers idempotency-key per (asset, prompt version) so
// re-fanout of the same asset under the same prompt version returns
// the existing in-flight job rather than queuing a duplicate. The
// key derivation matches the brief's `SHA-256("ai.tag|"+asset_id+
// "|"+prompt_version)` pattern.
package jobs

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"

	"github.com/mscrnt/artist-alley/app/internal/ai"
	"github.com/mscrnt/artist-alley/app/internal/jobs"
)

// Job type identifiers. These are the canonical strings written
// into the jobs.type column AND the keys the worker pool uses to
// route to handlers.
const (
	JobTypeTag     jobs.JobType = "ai.tag"
	JobTypeCaption jobs.JobType = "ai.caption"
)

// ---------------------------------------------------------------------------
// Router + AssetLookup interfaces — narrow dependencies for testing
// ---------------------------------------------------------------------------

// TagRouter is the narrow surface the tag handler needs from the AI
// router. *ai.Router satisfies it.
type TagRouter interface {
	Tag(ctx context.Context, asset ai.AssetRef, opts ai.TagOpts, privacy ai.PrivacyClass) ([]ai.Tag, error)
}

// CaptionRouter is the narrow surface the caption handler needs.
type CaptionRouter interface {
	Caption(ctx context.Context, asset ai.AssetRef, opts ai.CaptionOpts, privacy ai.PrivacyClass) (string, error)
}

// AssetLookup resolves an asset id to the AssetRef the router needs
// plus the sensitivity tier the privacy gate consumes. Defined as
// an interface so the handler doesn't import the assets package
// (which would create a cycle since assets enqueues the jobs).
type AssetLookup interface {
	LookupForAI(ctx context.Context, id uuid.UUID) (asset ai.AssetRef, sensitivity ai.SensitivityTier, found bool, err error)
}

// TagWriter persists generated tags onto an asset. assets.Handler
// will implement this; for v1 the handler signature carries the
// minimal data the writer needs (provenance metadata too so the
// audit chain stays intact).
type TagWriter interface {
	SetTagsFromAI(ctx context.Context, assetID uuid.UUID, tags []ai.Tag, prov Provenance) error
}

// CaptionWriter persists a generated caption.
type CaptionWriter interface {
	SetCaptionFromAI(ctx context.Context, assetID uuid.UUID, caption string, prov Provenance) error
}

// Provenance is the per-write metadata the assets-side persistence
// stores so the asset detail UI can show "this caption was AI-
// generated by Claude on 2026-06-20 via the v1.0 template".
type Provenance struct {
	Provider      string
	PromptVersion string
}

// ---------------------------------------------------------------------------
// Tag handler
// ---------------------------------------------------------------------------

// TagPayload is the JSON shape callers serialise into the job
// payload. AssetID is required; PromptVersion + MaxTags are
// optional (defaults from the registry / opts).
type TagPayload struct {
	AssetID       uuid.UUID `json:"asset_id"`
	PromptVersion string    `json:"prompt_version,omitempty"`
	MaxTags       int       `json:"max_tags,omitempty"`
}

// TagHandler implements jobs.Handler for ai.tag.
type TagHandler struct {
	Router  TagRouter
	Assets  AssetLookup
	Writer  TagWriter
	Privacy ai.PrivacyPolicy // captured at boot; classifies the asset's sensitivity
}

// NewTagHandler builds a handler. All dependencies are required at
// production wiring; for tests a stub TagRouter + AssetLookup +
// TagWriter is sufficient.
func NewTagHandler(router TagRouter, assets AssetLookup, writer TagWriter, policy ai.PrivacyPolicy) *TagHandler {
	return &TagHandler{Router: router, Assets: assets, Writer: writer, Privacy: policy}
}

// Type returns the dispatch identifier.
func (h *TagHandler) Type() jobs.JobType { return JobTypeTag }

// Handle runs the tag-generation flow for one asset.
//
// Error mapping:
//   - JSON parse failure → TerminalError (corrupt payload won't fix)
//   - AssetLookup miss → TerminalError (asset gone; re-fanout would re-fail)
//   - Router permanent / budget / privacy → TerminalError (operator
//     must change config; no retry would succeed)
//   - Router transient / rate-limit → plain error (worker retries
//     per the existing jobs retry policy)
func (h *TagHandler) Handle(ctx context.Context, job *jobs.Claim) (json.RawMessage, error) {
	var p TagPayload
	if err := json.Unmarshal(job.Payload, &p); err != nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: parse payload: %w", err)}
	}
	if p.AssetID == uuid.Nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: asset_id required")}
	}

	asset, sensitivity, found, err := h.Assets.LookupForAI(ctx, p.AssetID)
	if err != nil {
		return nil, fmt.Errorf("ai.tag: asset lookup: %w", err)
	}
	if !found {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: asset %s not found", p.AssetID)}
	}

	privacy := ai.ClassifyPrivacy(sensitivity, h.Privacy)
	tags, err := h.Router.Tag(ctx, asset, ai.TagOpts{
		MaxTags:       p.MaxTags,
		PromptVersion: p.PromptVersion,
	}, privacy)
	if err != nil {
		if isPermanentAIError(err) {
			return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: %w", err)}
		}
		return nil, fmt.Errorf("ai.tag: router: %w", err)
	}

	// Persist with provenance. Provider name is "router" since the
	// router picked which actual provider served the call; the
	// per-call audit row in ai_provider_call holds the exact
	// provider identity for the dashboard.
	if err := h.Writer.SetTagsFromAI(ctx, p.AssetID, tags, Provenance{
		Provider:      "router",
		PromptVersion: p.PromptVersion,
	}); err != nil {
		return nil, fmt.Errorf("ai.tag: persist: %w", err)
	}

	// Result is shown in the admin queue UI; keep it small.
	result, _ := json.Marshal(map[string]any{
		"tag_count": len(tags),
	})
	return result, nil
}

// TagIdempotencyKey produces the canonical idempotency key for a
// tag job. Re-enqueuing under the same key while a job is in-flight
// (pending OR running) returns the existing job's id; bumping the
// prompt version produces a different key → fresh job runs.
func TagIdempotencyKey(assetID uuid.UUID, promptVersion string) string {
	return derivedKey("ai.tag", assetID, promptVersion)
}

// ---------------------------------------------------------------------------
// Caption handler
// ---------------------------------------------------------------------------

// CaptionPayload is the JSON shape for caption jobs.
type CaptionPayload struct {
	AssetID       uuid.UUID `json:"asset_id"`
	PromptVersion string    `json:"prompt_version,omitempty"`
	MaxLength     int       `json:"max_length,omitempty"`
	StyleHint     string    `json:"style_hint,omitempty"`
}

// CaptionHandler implements jobs.Handler for ai.caption.
type CaptionHandler struct {
	Router  CaptionRouter
	Assets  AssetLookup
	Writer  CaptionWriter
	Privacy ai.PrivacyPolicy
}

// NewCaptionHandler builds a handler.
func NewCaptionHandler(router CaptionRouter, assets AssetLookup, writer CaptionWriter, policy ai.PrivacyPolicy) *CaptionHandler {
	return &CaptionHandler{Router: router, Assets: assets, Writer: writer, Privacy: policy}
}

func (h *CaptionHandler) Type() jobs.JobType { return JobTypeCaption }

func (h *CaptionHandler) Handle(ctx context.Context, job *jobs.Claim) (json.RawMessage, error) {
	var p CaptionPayload
	if err := json.Unmarshal(job.Payload, &p); err != nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: parse payload: %w", err)}
	}
	if p.AssetID == uuid.Nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: asset_id required")}
	}

	asset, sensitivity, found, err := h.Assets.LookupForAI(ctx, p.AssetID)
	if err != nil {
		return nil, fmt.Errorf("ai.caption: asset lookup: %w", err)
	}
	if !found {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: asset %s not found", p.AssetID)}
	}

	privacy := ai.ClassifyPrivacy(sensitivity, h.Privacy)
	caption, err := h.Router.Caption(ctx, asset, ai.CaptionOpts{
		MaxLength:     p.MaxLength,
		PromptVersion: p.PromptVersion,
		StyleHint:     p.StyleHint,
	}, privacy)
	if err != nil {
		if isPermanentAIError(err) {
			return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: %w", err)}
		}
		return nil, fmt.Errorf("ai.caption: router: %w", err)
	}

	if err := h.Writer.SetCaptionFromAI(ctx, p.AssetID, caption, Provenance{
		Provider:      "router",
		PromptVersion: p.PromptVersion,
	}); err != nil {
		return nil, fmt.Errorf("ai.caption: persist: %w", err)
	}

	result, _ := json.Marshal(map[string]any{
		"caption_length": len(caption),
	})
	return result, nil
}

// CaptionIdempotencyKey produces the canonical idempotency key.
func CaptionIdempotencyKey(assetID uuid.UUID, promptVersion string) string {
	return derivedKey("ai.caption", assetID, promptVersion)
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// derivedKey produces the SHA-256 hex digest of
// `<jobType>|<asset_id>|<prompt_version>`. Stable across binaries
// + across re-enqueues; the partial UNIQUE INDEX on
// (type, idempotency_key) (migration 00009) does the dedup.
func derivedKey(jobType string, assetID uuid.UUID, promptVersion string) string {
	h := sha256.Sum256([]byte(fmt.Sprintf("%s|%s|%s", jobType, assetID, promptVersion)))
	return hex.EncodeToString(h[:])
}

// isPermanentAIError reports whether the router returned a terminal
// error class. Permanent + budget + privacy all mean "no retry
// would succeed" — surface as jobs.TerminalError so the worker
// stops retrying.
func isPermanentAIError(err error) bool {
	pe, ok := ai.AsProviderError(err)
	if !ok {
		return false
	}
	switch pe.Class {
	case ai.ErrClassPermanent, ai.ErrClassBudget, ai.ErrClassPrivacy:
		return true
	}
	return false
}

// Compile-time interface checks.
var _ jobs.Handler = (*TagHandler)(nil)
var _ jobs.Handler = (*CaptionHandler)(nil)
