// Package jobs implements the ai.tag + ai.caption job handlers for
// the Phase 1.14.A inference fan-out. The handlers register with
// the jobs.Service.Registry at boot; assets.Handler enqueues one
// of each type per uploaded image/video as part of the existing
// post-upload fan-out (alongside ai.embed in 1.14.B and ai.transcribe
// in 1.14.C).
//
// Lives under app/internal/ai/ rather than app/internal/jobs/
// because the handler logic depends on ai.Router + the ai concern
// types — putting it in the jobs package would create a cycle
// (jobs is upstream of ai). The router/audit/cost machinery stays
// where it lives.
//
// Both handlers idempotency-key per (asset, prompt version) so
// re-fanout of the same asset under the same prompt version returns
// the existing in-flight job rather than queuing a duplicate. The
// key derivation matches the brief's `SHA-256("ai.tag|"+asset_id+
// "|"+prompt_version)` pattern.
package jobs

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strings"

	"github.com/google/uuid"

	"github.com/mscrnt/artist-alley/app/internal/ai"
	"github.com/mscrnt/artist-alley/app/internal/jobs"
)

// Job type identifiers. These are the canonical strings written
// into the jobs.type column AND the keys the worker pool uses to
// route to handlers.
const (
	JobTypeTag        jobs.JobType = "ai.tag"
	JobTypeCaption    jobs.JobType = "ai.caption"
	JobTypeEmbed      jobs.JobType = "ai.embed"
	JobTypeTranscribe jobs.JobType = "ai.transcribe"
)

// ---------------------------------------------------------------------------
// Router + AssetLookup interfaces — narrow dependencies for testing
// ---------------------------------------------------------------------------

// TagRouter is the narrow surface the tag handler needs from the AI
// router. *ai.Router satisfies it.
type TagRouter interface {
	Tag(ctx context.Context, asset ai.AssetRef, opts ai.TagOpts, privacy ai.PrivacyClass) ([]ai.Tag, error)
}

// CaptionRouter is the narrow surface the caption handler needs.
type CaptionRouter interface {
	Caption(ctx context.Context, asset ai.AssetRef, opts ai.CaptionOpts, privacy ai.PrivacyClass) (string, error)
}

// AssetLookup resolves an asset id to the AssetRef the router needs
// plus the sensitivity tier the privacy gate consumes. Defined as
// an interface so the handler doesn't import the assets package
// (which would create a cycle since assets enqueues the jobs).
type AssetLookup interface {
	LookupForAI(ctx context.Context, id uuid.UUID) (asset ai.AssetRef, sensitivity ai.SensitivityTier, found bool, err error)
}

// TagWriter persists generated tags onto an asset. assets.Handler
// will implement this; for v1 the handler signature carries the
// minimal data the writer needs (provenance metadata too so the
// audit chain stays intact).
type TagWriter interface {
	SetTagsFromAI(ctx context.Context, assetID uuid.UUID, tags []ai.Tag, prov Provenance) error
}

// CaptionWriter persists a generated caption.
type CaptionWriter interface {
	SetCaptionFromAI(ctx context.Context, assetID uuid.UUID, caption string, prov Provenance) error
}

// Provenance is the per-write metadata the assets-side persistence
// stores so the asset detail UI can show "this caption was AI-
// generated by Claude on 2026-06-20 via the v1.0 template".
type Provenance struct {
	Provider      string
	PromptVersion string
}

// ---------------------------------------------------------------------------
// Tag handler
// ---------------------------------------------------------------------------

// TagPayload is the JSON shape callers serialise into the job
// payload. AssetID is required; PromptVersion + MaxTags are
// optional (defaults from the registry / opts).
type TagPayload struct {
	AssetID       uuid.UUID `json:"asset_id"`
	PromptVersion string    `json:"prompt_version,omitempty"`
	MaxTags       int       `json:"max_tags,omitempty"`
}

// TagHandler implements jobs.Handler for ai.tag.
type TagHandler struct {
	Router  TagRouter
	Assets  AssetLookup
	Writer  TagWriter
	Privacy ai.PrivacyPolicy // captured at boot; classifies the asset's sensitivity
}

// NewTagHandler builds a handler. All dependencies are required at
// production wiring; for tests a stub TagRouter + AssetLookup +
// TagWriter is sufficient.
func NewTagHandler(router TagRouter, assets AssetLookup, writer TagWriter, policy ai.PrivacyPolicy) *TagHandler {
	return &TagHandler{Router: router, Assets: assets, Writer: writer, Privacy: policy}
}

// Type returns the dispatch identifier.
func (h *TagHandler) Type() jobs.JobType { return JobTypeTag }

// Handle runs the tag-generation flow for one asset.
//
// Error mapping:
//   - JSON parse failure → TerminalError (corrupt payload won't fix)
//   - AssetLookup miss → TerminalError (asset gone; re-fanout would re-fail)
//   - Router permanent / budget / privacy → TerminalError (operator
//     must change config; no retry would succeed)
//   - Router transient / rate-limit → plain error (worker retries
//     per the existing jobs retry policy)
func (h *TagHandler) Handle(ctx context.Context, job *jobs.Claim) (json.RawMessage, error) {
	var p TagPayload
	if err := json.Unmarshal(job.Payload, &p); err != nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: parse payload: %w", err)}
	}
	if p.AssetID == uuid.Nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: asset_id required")}
	}

	asset, sensitivity, found, err := h.Assets.LookupForAI(ctx, p.AssetID)
	if err != nil {
		return nil, fmt.Errorf("ai.tag: asset lookup: %w", err)
	}
	if !found {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: asset %s not found", p.AssetID)}
	}

	privacy := ai.ClassifyPrivacy(sensitivity, h.Privacy)
	tags, err := h.Router.Tag(ctx, asset, ai.TagOpts{
		MaxTags:       p.MaxTags,
		PromptVersion: p.PromptVersion,
	}, privacy)
	if err != nil {
		if isPermanentAIError(err) {
			return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.tag: %w", err)}
		}
		return nil, fmt.Errorf("ai.tag: router: %w", err)
	}

	// Persist with provenance. Provider name is "router" since the
	// router picked which actual provider served the call; the
	// per-call audit row in ai_provider_call holds the exact
	// provider identity for the dashboard.
	if err := h.Writer.SetTagsFromAI(ctx, p.AssetID, tags, Provenance{
		Provider:      "router",
		PromptVersion: p.PromptVersion,
	}); err != nil {
		return nil, fmt.Errorf("ai.tag: persist: %w", err)
	}

	// Result is shown in the admin queue UI; keep it small.
	result, _ := json.Marshal(map[string]any{
		"tag_count": len(tags),
	})
	return result, nil
}

// TagIdempotencyKey produces the canonical idempotency key for a
// tag job. Re-enqueuing under the same key while a job is in-flight
// (pending OR running) returns the existing job's id; bumping the
// prompt version produces a different key → fresh job runs.
func TagIdempotencyKey(assetID uuid.UUID, promptVersion string) string {
	return derivedKey("ai.tag", assetID, promptVersion)
}

// ---------------------------------------------------------------------------
// Caption handler
// ---------------------------------------------------------------------------

// CaptionPayload is the JSON shape for caption jobs.
type CaptionPayload struct {
	AssetID       uuid.UUID `json:"asset_id"`
	PromptVersion string    `json:"prompt_version,omitempty"`
	MaxLength     int       `json:"max_length,omitempty"`
	StyleHint     string    `json:"style_hint,omitempty"`
}

// CaptionHandler implements jobs.Handler for ai.caption.
type CaptionHandler struct {
	Router  CaptionRouter
	Assets  AssetLookup
	Writer  CaptionWriter
	Privacy ai.PrivacyPolicy
}

// NewCaptionHandler builds a handler.
func NewCaptionHandler(router CaptionRouter, assets AssetLookup, writer CaptionWriter, policy ai.PrivacyPolicy) *CaptionHandler {
	return &CaptionHandler{Router: router, Assets: assets, Writer: writer, Privacy: policy}
}

func (h *CaptionHandler) Type() jobs.JobType { return JobTypeCaption }

func (h *CaptionHandler) Handle(ctx context.Context, job *jobs.Claim) (json.RawMessage, error) {
	var p CaptionPayload
	if err := json.Unmarshal(job.Payload, &p); err != nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: parse payload: %w", err)}
	}
	if p.AssetID == uuid.Nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: asset_id required")}
	}

	asset, sensitivity, found, err := h.Assets.LookupForAI(ctx, p.AssetID)
	if err != nil {
		return nil, fmt.Errorf("ai.caption: asset lookup: %w", err)
	}
	if !found {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: asset %s not found", p.AssetID)}
	}

	privacy := ai.ClassifyPrivacy(sensitivity, h.Privacy)
	caption, err := h.Router.Caption(ctx, asset, ai.CaptionOpts{
		MaxLength:     p.MaxLength,
		PromptVersion: p.PromptVersion,
		StyleHint:     p.StyleHint,
	}, privacy)
	if err != nil {
		if isPermanentAIError(err) {
			return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.caption: %w", err)}
		}
		return nil, fmt.Errorf("ai.caption: router: %w", err)
	}

	if err := h.Writer.SetCaptionFromAI(ctx, p.AssetID, caption, Provenance{
		Provider:      "router",
		PromptVersion: p.PromptVersion,
	}); err != nil {
		return nil, fmt.Errorf("ai.caption: persist: %w", err)
	}

	result, _ := json.Marshal(map[string]any{
		"caption_length": len(caption),
	})
	return result, nil
}

// CaptionIdempotencyKey produces the canonical idempotency key.
func CaptionIdempotencyKey(assetID uuid.UUID, promptVersion string) string {
	return derivedKey("ai.caption", assetID, promptVersion)
}

// ---------------------------------------------------------------------------
// Embed handler — Phase 1.14.B
// ---------------------------------------------------------------------------

// EmbedRouter is the narrow surface the embed handler needs from the
// AI router. *ai.Router satisfies it.
type EmbedRouter interface {
	Embed(ctx context.Context, in ai.EmbedInput, privacy ai.PrivacyClass) ([]float32, error)
}

// EmbedAssetLookup resolves an asset id to the rich projection the
// embed handler needs to compose embedding text. ai.AssetLookup
// (the bridge interface) satisfies it; assets.Handler is the
// concrete impl.
type EmbedAssetLookup interface {
	GetAssetForAI(ctx context.Context, id uuid.UUID) (ai.AssetForAI, error)
}

// EmbedWriter persists a vector. ai.EmbeddingWriter (the bridge
// interface) satisfies it.
type EmbedWriter interface {
	UpsertAssetEmbedding(ctx context.Context, in ai.EmbeddingInput) error
}

// EmbedPayload is the JSON shape the asset upload fanout writes
// into the job payload.
type EmbedPayload struct {
	AssetID  uuid.UUID `json:"asset_id"`
	Model    string    `json:"model,omitempty"`    // optional override of ai.embedding.default_model
	Modality string    `json:"modality,omitempty"` // 'text' (default) | 'image' | 'multimodal'
}

// EmbedHandler implements jobs.Handler for ai.embed.
type EmbedHandler struct {
	Router       EmbedRouter
	Assets       EmbedAssetLookup
	Writer       EmbedWriter
	Privacy      ai.PrivacyPolicy
	DefaultModel string // typically "nomic-embed-text"
}

// NewEmbedHandler builds a handler. defaultModel comes from
// system_config.ai.embedding.default_model — operator can override
// per-job via payload.Model.
func NewEmbedHandler(router EmbedRouter, assets EmbedAssetLookup, writer EmbedWriter, policy ai.PrivacyPolicy, defaultModel string) *EmbedHandler {
	return &EmbedHandler{
		Router:       router,
		Assets:       assets,
		Writer:       writer,
		Privacy:      policy,
		DefaultModel: defaultModel,
	}
}

// Type returns the dispatch identifier.
func (h *EmbedHandler) Type() jobs.JobType { return JobTypeEmbed }

// Handle runs the embed flow for one asset.
//
// Composes the embedding text from Title + existing tags. If the
// asset has no embeddable text content (untitled + untagged), we
// skip cleanly — embedding empty text is useless and would bias
// the vector toward whatever the model's default zero-input vector
// is.
//
// Error mapping mirrors TagHandler:
//   - parse failure / missing asset id → TerminalError
//   - asset lookup miss → TerminalError (ai.ErrAssetNotFound)
//   - router permanent / budget / privacy → TerminalError
//   - router transient → plain error (worker retries)
//   - writer ErrAssetNotFound → TerminalError (asset deleted between
//     embed + persist)
func (h *EmbedHandler) Handle(ctx context.Context, job *jobs.Claim) (json.RawMessage, error) {
	var p EmbedPayload
	if err := json.Unmarshal(job.Payload, &p); err != nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.embed: parse payload: %w", err)}
	}
	if p.AssetID == uuid.Nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.embed: asset_id required")}
	}

	asset, err := h.Assets.GetAssetForAI(ctx, p.AssetID)
	if err != nil {
		if errors.Is(err, ai.ErrAssetNotFound) {
			return nil, &jobs.TerminalError{Err: err}
		}
		return nil, fmt.Errorf("ai.embed: asset lookup: %w", err)
	}

	text := composeEmbeddingText(asset)
	if text == "" {
		// Nothing to embed; report success with a skip note rather
		// than persisting a zero-vector that would skew kNN results.
		result, _ := json.Marshal(map[string]any{"skipped": "no_embeddable_text"})
		return result, nil
	}

	model := p.Model
	if model == "" {
		model = h.DefaultModel
	}
	modality := p.Modality
	if modality == "" {
		modality = "text"
	}

	privacy := ai.ClassifyPrivacy(asset.Sensitivity, h.Privacy)
	vec, err := h.Router.Embed(ctx, ai.EmbedInput{
		Text:  text,
		Model: model,
	}, privacy)
	if err != nil {
		if isPermanentAIError(err) {
			return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.embed: %w", err)}
		}
		return nil, fmt.Errorf("ai.embed: router: %w", err)
	}

	err = h.Writer.UpsertAssetEmbedding(ctx, ai.EmbeddingInput{
		AssetID:     p.AssetID,
		Provider:    "router", // the actual provider that served is in ai_provider_call
		Model:       model,
		Modality:    modality,
		Vector:      vec,
		ContentHash: asset.ContentHash,
	})
	if err != nil {
		if errors.Is(err, ai.ErrAssetNotFound) {
			return nil, &jobs.TerminalError{Err: err}
		}
		return nil, fmt.Errorf("ai.embed: persist: %w", err)
	}

	result, _ := json.Marshal(map[string]any{
		"dim":      len(vec),
		"model":    model,
		"modality": modality,
		"text_len": len(text),
	})
	return result, nil
}

// EmbedIdempotencyKey produces the canonical idempotency key. The
// model + asset_id pair drives dedup — re-enqueuing the same asset
// under the same model returns the existing job; bumping the model
// (operator changes ai.embedding.default_model) produces a fresh
// run.
func EmbedIdempotencyKey(assetID uuid.UUID, model string) string {
	return derivedKey("ai.embed", assetID, model)
}

// composeEmbeddingText concatenates Title + existing-tag values into
// the string the embedding model sees. Manual + import tags carry
// operator intent; AI tags from a previous run also feed into the
// vector (they shape the search space).
//
// Tags are joined with commas so the model sees a comma-separated
// list as a natural phrase ("kittens, basket, fluffy") rather than
// a glob.
func composeEmbeddingText(asset ai.AssetForAI) string {
	var parts []string
	if asset.Title != "" {
		parts = append(parts, asset.Title)
	}
	if len(asset.ExistingTags) > 0 {
		tagVals := make([]string, 0, len(asset.ExistingTags))
		for _, t := range asset.ExistingTags {
			if t.Value != "" {
				tagVals = append(tagVals, t.Value)
			}
		}
		if len(tagVals) > 0 {
			parts = append(parts, strings.Join(tagVals, ", "))
		}
	}
	return strings.TrimSpace(strings.Join(parts, ". "))
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// derivedKey produces the SHA-256 hex digest of
// `<jobType>|<asset_id>|<prompt_version>`. Stable across binaries
// + across re-enqueues; the partial UNIQUE INDEX on
// (type, idempotency_key) (migration 00009) does the dedup.
func derivedKey(jobType string, assetID uuid.UUID, promptVersion string) string {
	h := sha256.Sum256([]byte(fmt.Sprintf("%s|%s|%s", jobType, assetID, promptVersion)))
	return hex.EncodeToString(h[:])
}

// isPermanentAIError reports whether the router returned a terminal
// error class. Permanent + budget + privacy all mean "no retry
// would succeed" — surface as jobs.TerminalError so the worker
// stops retrying.
func isPermanentAIError(err error) bool {
	pe, ok := ai.AsProviderError(err)
	if !ok {
		return false
	}
	switch pe.Class {
	case ai.ErrClassPermanent, ai.ErrClassBudget, ai.ErrClassPrivacy:
		return true
	}
	return false
}

// ---------------------------------------------------------------------------
// Transcribe handler — Phase 1.14.C
// ---------------------------------------------------------------------------

// TranscribeOrchestrator is the narrow surface the transcribe job
// handler needs. transcribe.Handler.TranscribeAsset satisfies it
// (consumer-defined; keeps the ai/transcribe package out of this
// one's import graph — handlers depends on transcribe via the boot
// wire injection).
type TranscribeOrchestrator interface {
	TranscribeAsset(ctx context.Context, assetID uuid.UUID, opts TranscribeOrchestratorOpts) (TranscribeOrchestratorResult, error)
}

// TranscribeOrchestratorOpts mirrors transcribe.TranscribeOpts via a
// local type so this package doesn't pull ai/transcribe in. The boot
// wire adapter converts between the two.
type TranscribeOrchestratorOpts struct {
	LanguageHint  string
	ForceModel    string
	SubtitleLabel string
}

// TranscribeOrchestratorResult carries the resulting language for
// the job's result payload. We don't surface the full subtitle row
// because the job's result_json shape stays small.
type TranscribeOrchestratorResult struct {
	Language string
	VTTBytes int
}

// TranscribePayload is the JSON shape the asset upload fanout writes
// into the job payload.
type TranscribePayload struct {
	AssetID    uuid.UUID `json:"asset_id"`
	LangHint   string    `json:"lang_hint,omitempty"`   // operator-supplied override
	ForceModel string    `json:"force_model,omitempty"` // operator-supplied model override
}

// TranscribeHandler implements jobs.Handler for ai.transcribe.
type TranscribeHandler struct {
	Orchestrator TranscribeOrchestrator
}

// NewTranscribeHandler builds a handler.
func NewTranscribeHandler(orch TranscribeOrchestrator) *TranscribeHandler {
	return &TranscribeHandler{Orchestrator: orch}
}

// Type returns the dispatch identifier.
func (h *TranscribeHandler) Type() jobs.JobType { return JobTypeTranscribe }

// Handle runs the transcribe flow for one asset. The orchestrator
// does extract → chunk → router → stitch → marshal VTT → subtitle
// upsert; this handler just wraps payload parsing + error
// classification.
//
// Error mapping mirrors EmbedHandler:
//   - parse failure / missing asset id → TerminalError
//   - asset lookup miss → TerminalError (ai.ErrAssetNotFound)
//   - router permanent / budget / privacy → TerminalError
//   - router transient → plain error (worker retries)
func (h *TranscribeHandler) Handle(ctx context.Context, job *jobs.Claim) (json.RawMessage, error) {
	var p TranscribePayload
	if err := json.Unmarshal(job.Payload, &p); err != nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.transcribe: parse payload: %w", err)}
	}
	if p.AssetID == uuid.Nil {
		return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.transcribe: asset_id required")}
	}

	res, err := h.Orchestrator.TranscribeAsset(ctx, p.AssetID, TranscribeOrchestratorOpts{
		LanguageHint: p.LangHint,
		ForceModel:   p.ForceModel,
	})
	if err != nil {
		if errors.Is(err, ai.ErrAssetNotFound) {
			return nil, &jobs.TerminalError{Err: err}
		}
		if isPermanentAIError(err) {
			return nil, &jobs.TerminalError{Err: fmt.Errorf("ai.transcribe: %w", err)}
		}
		return nil, fmt.Errorf("ai.transcribe: %w", err)
	}

	result, _ := json.Marshal(map[string]any{
		"language":  res.Language,
		"vtt_bytes": res.VTTBytes,
	})
	return result, nil
}

// TranscribeIdempotencyKey produces the canonical idempotency key.
// Model bump → fresh job. Re-fanout for the same asset+model dedups
// against the in-flight row.
func TranscribeIdempotencyKey(assetID uuid.UUID, model string) string {
	return derivedKey("ai.transcribe", assetID, model)
}

// Compile-time interface checks.
var _ jobs.Handler = (*TagHandler)(nil)
var _ jobs.Handler = (*CaptionHandler)(nil)
var _ jobs.Handler = (*EmbedHandler)(nil)
var _ jobs.Handler = (*TranscribeHandler)(nil)
