// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storage

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID             pgtype.UUID
	RsUserID       int64
	Name           string
	TokenHash      []byte
	Scopes         []string
	ExpiresAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
}

type Asset struct {
	ID             pgtype.UUID
	Title          string
	Description    string
	ResourceType   int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Rating         *int32
	UserRating     *float32
	HitCount       int64
	NewHitCount    int64
	RequestCount   int64
	ArchiveState   int32
	Access         int32
	ThumbWidth     *int32
	ThumbHeight    *int32
	ImageRed       *int16
	ImageGreen     *int16
	ImageBlue      *int16
	ColourKey      *string
	GeoLat         *float64
	GeoLong        *float64
	Country        *string
	HasImage       bool
	IsTranscoding  bool
	Metadata       []byte
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type AssetTag struct {
	AssetID pgtype.UUID
	Tag     string
	AddedAt pgtype.Timestamptz
}

type AuditEvent struct {
	ID             pgtype.UUID
	EventType      string
	OccurredAt     pgtype.Timestamptz
	SubjectUserRef *int64
	ActorUserRef   *int64
	Ip             *netip.Addr
	UserAgent      *string
	Metadata       []byte
}

type Capability struct {
	Code        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type ResourceType struct {
	Ref               int64
	Name              *string
	AllowedExtensions *string
	OrderBy           *int64
	ConfigOptions     *string
	PushMetadata      *int64
	Colour            *int64
	Icon              *string
	Tab               *int64
	PullImages        *int64
}

type Role struct {
	ID             pgtype.UUID
	ParentID       pgtype.UUID
	Name           string
	Description    string
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RoleCapability struct {
	RoleID         pgtype.UUID
	CapabilityCode string
}

type Session struct {
	ID             pgtype.UUID
	UserRef        int64
	TokenHash      []byte
	CreatedAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	Ip             *netip.Addr
	UserAgent      *string
	OriginServerID pgtype.UUID
}

type StorageObject struct {
	Hash           string
	SizeBytes      int64
	ContentType    string
	Backend        string
	BackendBucket  *string
	OriginServerID pgtype.UUID
	GcEligibleAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type StoragePin struct {
	ObjectHash     string
	PinSubjectType string
	PinSubjectID   string
	CreatedAt      pgtype.Timestamptz
}

type StorageVariant struct {
	ObjectHash  string
	VariantKey  string
	SizeBytes   int64
	ContentType string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

type SystemConfig struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	Ref                int64
	Username           *string
	Password           *string
	Fullname           *string
	Email              *string
	Usergroup          *int64
	LastActive         pgtype.Timestamptz
	LoggedIn           *int64
	AcceptedTerms      int64
	AccountExpires     pgtype.Timestamptz
	Session            *string
	PasswordLastChange pgtype.Timestamptz
	LoginTries         int64
	LoginLastTry       pgtype.Timestamptz
	Approved           int64
	Lang               *string
	Created            pgtype.Timestamptz
	Origin             *string
	UniqueHash         *string
}

type UserCapabilityGrant struct {
	RsUserID          int64
	CapabilityCode    string
	GrantedAt         pgtype.Timestamptz
	GrantedByRsUserID *int64
	Note              string
}

type UserCapabilityRevoke struct {
	RsUserID          int64
	CapabilityCode    string
	RevokedAt         pgtype.Timestamptz
	RevokedByRsUserID *int64
	Note              string
}

type UserRole struct {
	RsUserID           int64
	RoleID             pgtype.UUID
	AssignedAt         pgtype.Timestamptz
	AssignedByRsUserID *int64
}
