// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package social

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks (blocker_user_ref, blocked_user_ref, reason)
VALUES ($1, $2, $3)
ON CONFLICT (blocker_user_ref, blocked_user_ref) DO UPDATE
    SET reason = EXCLUDED.reason
`

type BlockUserParams struct {
	BlockerUserRef int64
	BlockedUserRef int64
	Reason         *string
}

// Upserts the block edge with an optional reason. The handler also
// runs UnfollowUser in both directions before BlockUser — blocking
// and continuing to follow is a contradictory state, and modern
// social platforms all auto-unfollow on block.
func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerUserRef, arg.BlockedUserRef, arg.Reason)
	return err
}

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*)::BIGINT AS count
FROM user_follows
WHERE followee_user_ref = $1
`

// "X followers" badge on a profile page. The followee-indexed lookup
// (idx_user_follows_followee) makes this a small index-only scan.
func (q *Queries) CountFollowers(ctx context.Context, followeeUserRef int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followeeUserRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFollowing = `-- name: CountFollowing :one
SELECT COUNT(*)::BIGINT AS count
FROM user_follows
WHERE follower_user_ref = $1
`

// "Following Y" badge on a profile page.
func (q *Queries) CountFollowing(ctx context.Context, followerUserRef int64) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowing, followerUserRef)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (
    id, target_kind, target_id, parent_id, root_id, depth,
    author_user_ref, body, body_html, annotation_type, annotation_data
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, target_kind, target_id, parent_id, root_id, depth,
          author_user_ref, body, body_html,
          annotation_type, annotation_data,
          like_count, edited_at, deleted_at,
          origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
`

type CreateCommentParams struct {
	ID             pgtype.UUID
	TargetKind     string
	TargetID       pgtype.UUID
	ParentID       pgtype.UUID
	RootID         pgtype.UUID
	Depth          int32
	AuthorUserRef  *int64
	Body           string
	BodyHtml       string
	AnnotationType *string
	AnnotationData []byte
}

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------
// The Go caller generates the id up front so top-level comments can
// have root_id = id at INSERT time (the column is NOT NULL, so we
// can't post-set it). For replies the caller passes the parent's
// root_id; depth comes from parent.depth + 1.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.TargetKind,
		arg.TargetID,
		arg.ParentID,
		arg.RootID,
		arg.Depth,
		arg.AuthorUserRef,
		arg.Body,
		arg.BodyHtml,
		arg.AnnotationType,
		arg.AnnotationData,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeerID,
		&i.ActorUri,
		&i.ActivityUri,
	)
	return i, err
}

const followUser = `-- name: FollowUser :exec

INSERT INTO user_follows (follower_user_ref, followee_user_ref)
VALUES ($1, $2)
ON CONFLICT (follower_user_ref, followee_user_ref) DO NOTHING
`

type FollowUserParams struct {
	FollowerUserRef int64
	FolloweeUserRef int64
}

// ---------------------------------------------------------------------------
// Social graph: follows + blocks (Phase 1.17.G2)
// ---------------------------------------------------------------------------
// Idempotent — re-following someone you already follow is a no-op
// rather than a primary-key violation, so the handler can return 204
// without distinguishing first-follow from already-following.
func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerUserRef, arg.FolloweeUserRef)
	return err
}

const getComment = `-- name: GetComment :one
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
FROM comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeerID,
		&i.ActorUri,
		&i.ActivityUri,
	)
	return i, err
}

const getCommentAuthorAndContext = `-- name: GetCommentAuthorAndContext :one
SELECT author_user_ref, parent_id, target_kind, target_id
FROM comments
WHERE id = $1 AND deleted_at IS NULL
`

type GetCommentAuthorAndContextRow struct {
	AuthorUserRef *int64
	ParentID      pgtype.UUID
	TargetKind    string
	TargetID      pgtype.UUID
}

// Tiny lookup the comment reply path needs — pulls the comment's
// author + parent_id so we can fire "reply_to_my_comment" against
// the parent comment's author (and skip when there isn't one).
func (q *Queries) GetCommentAuthorAndContext(ctx context.Context, id pgtype.UUID) (GetCommentAuthorAndContextRow, error) {
	row := q.db.QueryRow(ctx, getCommentAuthorAndContext, id)
	var i GetCommentAuthorAndContextRow
	err := row.Scan(
		&i.AuthorUserRef,
		&i.ParentID,
		&i.TargetKind,
		&i.TargetID,
	)
	return i, err
}

const getCommentByActivityURI = `-- name: GetCommentByActivityURI :one
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       peer_id, actor_uri, activity_uri,
       created_at, updated_at
FROM comments
WHERE activity_uri = $1
`

type GetCommentByActivityURIRow struct {
	ID            pgtype.UUID
	TargetKind    string
	TargetID      pgtype.UUID
	ParentID      pgtype.UUID
	RootID        pgtype.UUID
	Depth         int32
	AuthorUserRef *int64
	Body          string
	BodyHtml      string
	PeerID        pgtype.UUID
	ActorUri      *string
	ActivityUri   *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

// Used by the inbox dispatcher to detect a retried delivery —
// if a row already exists for this activity_uri, the dispatcher
// treats it as "already processed" without re-firing the
// notification.
func (q *Queries) GetCommentByActivityURI(ctx context.Context, activityUri *string) (GetCommentByActivityURIRow, error) {
	row := q.db.QueryRow(ctx, getCommentByActivityURI, activityUri)
	var i GetCommentByActivityURIRow
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.PeerID,
		&i.ActorUri,
		&i.ActivityUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPostAuthorAndTitle = `-- name: GetPostAuthorAndTitle :one
SELECT author_user_ref, title
FROM posts
WHERE id = $1 AND deleted_at IS NULL
`

type GetPostAuthorAndTitleRow struct {
	AuthorUserRef int64
	Title         string
}

// Tiny lookup the notification emitter uses to know who to notify
// + populate the inbox card with the post title. Single-row index
// hit on posts.id PK; sub-ms.
func (q *Queries) GetPostAuthorAndTitle(ctx context.Context, id pgtype.UUID) (GetPostAuthorAndTitleRow, error) {
	row := q.db.QueryRow(ctx, getPostAuthorAndTitle, id)
	var i GetPostAuthorAndTitleRow
	err := row.Scan(&i.AuthorUserRef, &i.Title)
	return i, err
}

const hasBlockBetween = `-- name: HasBlockBetween :one
SELECT EXISTS (
    SELECT 1 FROM user_blocks
    WHERE (blocker_user_ref = $1 AND blocked_user_ref = $2)
       OR (blocker_user_ref = $2 AND blocked_user_ref = $1)
) AS blocked
`

type HasBlockBetweenParams struct {
	BlockerUserRef int64
	BlockedUserRef int64
}

// The "are A and B mutually visible?" gate. Returns true if EITHER
// direction of the block edge exists. Consumed by visibility-aware
// writers (notification dispatcher, DM delivery in 1.17.I, mention
// resolution) to short-circuit before doing work.
func (q *Queries) HasBlockBetween(ctx context.Context, arg HasBlockBetweenParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasBlockBetween, arg.BlockerUserRef, arg.BlockedUserRef)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const hasUserLikedTarget = `-- name: HasUserLikedTarget :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE target_kind = $1 AND target_id = $2 AND user_ref = $3
) AS value
`

type HasUserLikedTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	UserRef    *int64
}

func (q *Queries) HasUserLikedTarget(ctx context.Context, arg HasUserLikedTargetParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedTarget, arg.TargetKind, arg.TargetID, arg.UserRef)
	var value bool
	err := row.Scan(&value)
	return value, err
}

const insertRemoteComment = `-- name: InsertRemoteComment :one
INSERT INTO comments (
    id, target_kind, target_id, parent_id, root_id, depth,
    body, body_html,
    peer_id, actor_uri, activity_uri
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, target_kind, target_id, parent_id, root_id, depth,
          author_user_ref, body, body_html,
          annotation_type, annotation_data,
          like_count, edited_at, deleted_at,
          origin_server_id, peer_id, actor_uri, activity_uri,
          created_at, updated_at
`

type InsertRemoteCommentParams struct {
	ID          pgtype.UUID
	TargetKind  string
	TargetID    pgtype.UUID
	ParentID    pgtype.UUID
	RootID      pgtype.UUID
	Depth       int32
	Body        string
	BodyHtml    string
	PeerID      pgtype.UUID
	ActorUri    *string
	ActivityUri *string
}

type InsertRemoteCommentRow struct {
	ID             pgtype.UUID
	TargetKind     string
	TargetID       pgtype.UUID
	ParentID       pgtype.UUID
	RootID         pgtype.UUID
	Depth          int32
	AuthorUserRef  *int64
	Body           string
	BodyHtml       string
	AnnotationType *string
	AnnotationData []byte
	LikeCount      int64
	EditedAt       pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
	PeerID         pgtype.UUID
	ActorUri       *string
	ActivityUri    *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

// Inbound federation Create(Note) — the remote actor posted a
// comment on a target the local instance owns. Idempotent via
// comments_activity_uri_uniq_idx UNIQUE (activity_uri) WHERE
// NOT NULL — a retried dispatch lands as a constraint-violation
// we map to "already saved" rather than a new row.
//
// author_user_ref is NULL for remote rows per the origin CHECK;
// peer_id + actor_uri + activity_uri together identify the
// remote authorship.
func (q *Queries) InsertRemoteComment(ctx context.Context, arg InsertRemoteCommentParams) (InsertRemoteCommentRow, error) {
	row := q.db.QueryRow(ctx, insertRemoteComment,
		arg.ID,
		arg.TargetKind,
		arg.TargetID,
		arg.ParentID,
		arg.RootID,
		arg.Depth,
		arg.Body,
		arg.BodyHtml,
		arg.PeerID,
		arg.ActorUri,
		arg.ActivityUri,
	)
	var i InsertRemoteCommentRow
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.PeerID,
		&i.ActorUri,
		&i.ActivityUri,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRemoteLike = `-- name: InsertRemoteLike :execrows
INSERT INTO likes (target_kind, target_id, peer_id, actor_uri)
VALUES ($1, $2, $3, $4)
ON CONFLICT (target_kind, target_id, peer_id, actor_uri) WHERE peer_id IS NOT NULL DO NOTHING
`

type InsertRemoteLikeParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	PeerID     pgtype.UUID
	ActorUri   *string
}

// Inbound federation Like from a remote actor on a target the
// local instance owns. Idempotent via likes_remote_uniq_idx
// on (target_kind, target_id, peer_id, actor_uri) WHERE peer_id
// IS NOT NULL. ON CONFLICT clause must repeat the partial-index
// WHERE predicate so Postgres can match the right index.
func (q *Queries) InsertRemoteLike(ctx context.Context, arg InsertRemoteLikeParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRemoteLike,
		arg.TargetKind,
		arg.TargetID,
		arg.PeerID,
		arg.ActorUri,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const isBlocking = `-- name: IsBlocking :one
SELECT EXISTS (
    SELECT 1 FROM user_blocks
    WHERE blocker_user_ref = $1
      AND blocked_user_ref = $2
) AS blocking
`

type IsBlockingParams struct {
	BlockerUserRef int64
	BlockedUserRef int64
}

// Single-direction block check, consumed by GetUserRelationship to
// populate the per-direction is_blocked_by_me / is_blocked_by_them
// booleans. HasBlockBetween is the bidirectional visibility gate;
// IsBlocking is for "did THIS user block that one?" reporting.
func (q *Queries) IsBlocking(ctx context.Context, arg IsBlockingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocking, arg.BlockerUserRef, arg.BlockedUserRef)
	var blocking bool
	err := row.Scan(&blocking)
	return blocking, err
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
    SELECT 1 FROM user_follows
    WHERE follower_user_ref = $1
      AND followee_user_ref = $2
) AS following
`

type IsFollowingParams struct {
	FollowerUserRef int64
	FolloweeUserRef int64
}

// The load-bearing check for visibility='followers' posts (wires
// the long-parked posts.handler.go:877 TODO). Single-row EXISTS
// against the PK so it's a sub-ms query.
func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerUserRef, arg.FolloweeUserRef)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const likeTarget = `-- name: LikeTarget :exec


INSERT INTO likes (target_kind, target_id, user_ref)
VALUES ($1, $2, $3)
ON CONFLICT (target_kind, target_id, user_ref) WHERE user_ref IS NOT NULL DO NOTHING
`

type LikeTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	UserRef    *int64
}

// Comments + likes queries. Polymorphic across (target_kind, target_id),
// so one set of queries serves posts, assets, and (later) collections.
// See migration 00020.
// ---------------------------------------------------------------------------
// Likes
// ---------------------------------------------------------------------------
// Idempotent. The partial-UNIQUE index
// likes_local_uniq_idx on (target_kind, target_id, user_ref)
// WHERE user_ref IS NOT NULL means re-inserting a row the same
// LOCAL user already liked is a no-op, and the counter trigger
// doesn't fire a second time.
func (q *Queries) LikeTarget(ctx context.Context, arg LikeTargetParams) error {
	_, err := q.db.Exec(ctx, likeTarget, arg.TargetKind, arg.TargetID, arg.UserRef)
	return err
}

const listAnnotationsForAsset = `-- name: ListAnnotationsForAsset :many
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
FROM comments
WHERE target_kind = 'asset'
  AND target_id = $1
  AND annotation_type IS NOT NULL
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

// Future review-mode UI: fetch every annotation comment on an asset
// for overlay rendering. Only comments with annotation_type set are
// returned — the same table, but the partial index makes this
// cheap.
func (q *Queries) ListAnnotationsForAsset(ctx context.Context, targetID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listAnnotationsForAsset, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PeerID,
			&i.ActorUri,
			&i.ActivityUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocked = `-- name: ListBlocked :many
SELECT u.ref,
       u.username,
       up.display_name,
       up.avatar_url,
       b.reason,
       b.created_at
FROM user_blocks b
JOIN "user" u             ON u.ref = b.blocked_user_ref
LEFT JOIN user_profiles up ON up.user_ref = u.ref
WHERE b.blocker_user_ref = $1
ORDER BY b.created_at DESC, b.blocked_user_ref DESC
LIMIT $2
`

type ListBlockedParams struct {
	BlockerUserRef int64
	Limit          int32
}

type ListBlockedRow struct {
	Ref         int64
	Username    *string
	DisplayName *string
	AvatarUrl   *string
	Reason      *string
	CreatedAt   pgtype.Timestamptz
}

// "Users I've blocked" management page (/account/blocked). Only the
// blocker's perspective — legacy-style "show me who blocked me" is
// deliberately NOT exposed (most platforms hide this for the
// blocker's privacy).
func (q *Queries) ListBlocked(ctx context.Context, arg ListBlockedParams) ([]ListBlockedRow, error) {
	rows, err := q.db.Query(ctx, listBlocked, arg.BlockerUserRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlockedRow
	for rows.Next() {
		var i ListBlockedRow
		if err := rows.Scan(
			&i.Ref,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByAuthor = `-- name: ListCommentsByAuthor :many
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
FROM comments
WHERE author_user_ref = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByAuthorParams struct {
	AuthorUserRef *int64
	Limit         int32
	Offset        int32
}

// "Things X commented on" — used by the user profile page later.
func (q *Queries) ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByAuthor, arg.AuthorUserRef, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PeerID,
			&i.ActorUri,
			&i.ActivityUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.ref,
       u.username,
       up.display_name,
       up.avatar_url,
       f.created_at
FROM user_follows f
JOIN "user" u             ON u.ref = f.follower_user_ref
LEFT JOIN user_profiles up ON up.user_ref = u.ref
WHERE f.followee_user_ref = $1
ORDER BY f.created_at DESC, f.follower_user_ref DESC
LIMIT $2
`

type ListFollowersParams struct {
	FolloweeUserRef int64
	Limit           int32
}

type ListFollowersRow struct {
	Ref         int64
	Username    *string
	DisplayName *string
	AvatarUrl   *string
	CreatedAt   pgtype.Timestamptz
}

// Paginated reverse lookup — who follows the given user. Joined
// against "user" + user_profiles so the response carries enough to
// render the user card without a second round-trip. Cursor uses
// created_at as a stable sort key with PK breakage on ties.
func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.FolloweeUserRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.Ref,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.ref,
       u.username,
       up.display_name,
       up.avatar_url,
       f.created_at
FROM user_follows f
JOIN "user" u             ON u.ref = f.followee_user_ref
LEFT JOIN user_profiles up ON up.user_ref = u.ref
WHERE f.follower_user_ref = $1
ORDER BY f.created_at DESC, f.followee_user_ref DESC
LIMIT $2
`

type ListFollowingParams struct {
	FollowerUserRef int64
	Limit           int32
}

type ListFollowingRow struct {
	Ref         int64
	Username    *string
	DisplayName *string
	AvatarUrl   *string
	CreatedAt   pgtype.Timestamptz
}

// Symmetric to ListFollowers — who the given user follows.
func (q *Queries) ListFollowing(ctx context.Context, arg ListFollowingParams) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, arg.FollowerUserRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowingRow
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.Ref,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikersOfTarget = `-- name: ListLikersOfTarget :many
SELECT user_ref, liked_at
FROM likes
WHERE target_kind = $1 AND target_id = $2
ORDER BY liked_at DESC, user_ref ASC
LIMIT $3 OFFSET $4
`

type ListLikersOfTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	Limit      int32
	Offset     int32
}

type ListLikersOfTargetRow struct {
	UserRef *int64
	LikedAt pgtype.Timestamptz
}

// Used by the post modal's "liked by X, Y, and 17 others" surface.
// Newest likes first; the handler caps at the limit and offers an
// offset cursor for "show more".
func (q *Queries) ListLikersOfTarget(ctx context.Context, arg ListLikersOfTargetParams) ([]ListLikersOfTargetRow, error) {
	rows, err := q.db.Query(ctx, listLikersOfTarget,
		arg.TargetKind,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLikersOfTargetRow
	for rows.Next() {
		var i ListLikersOfTargetRow
		if err := rows.Scan(&i.UserRef, &i.LikedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextAnnotationsForAsset = `-- name: ListTextAnnotationsForAsset :many
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
FROM comments
WHERE target_kind = 'asset'
  AND target_id = $1
  AND annotation_type = 'text-range'
  AND parent_id IS NULL
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

// Doc-viewer review panel: every text-range annotation on an asset,
// newest first. Backed by the comments_text_annotations_idx partial
// index (migration 00036). Replies to an annotation thread under it
// via parent_id and surface through the normal thread query; this
// list returns only the top-level anchors.
func (q *Queries) ListTextAnnotationsForAsset(ctx context.Context, targetID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listTextAnnotationsForAsset, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PeerID,
			&i.ActorUri,
			&i.ActivityUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadForTarget = `-- name: ListThreadForTarget :many
WITH thread_roots AS (
    SELECT cr.id, cr.created_at
    FROM comments cr
    WHERE cr.target_kind = $1 AND cr.target_id = $2
      AND cr.parent_id IS NULL
      AND cr.deleted_at IS NULL
      AND ($3::timestamptz IS NULL
           OR cr.created_at < $3::timestamptz)
    ORDER BY cr.created_at DESC, cr.id ASC
    LIMIT $4::int
)
SELECT c.id, c.target_kind, c.target_id, c.parent_id, c.root_id, c.depth,
       c.author_user_ref, c.body, c.body_html,
       c.annotation_type, c.annotation_data,
       c.like_count, c.edited_at, c.deleted_at,
       c.origin_server_id, c.created_at, c.updated_at,
       c.peer_id, c.actor_uri, c.activity_uri,
       fra.display_name::text AS remote_display_name
FROM comments c
JOIN thread_roots tr ON tr.id = c.root_id
LEFT JOIN federation_remote_actors fra ON fra.actor_uri = c.actor_uri
WHERE c.deleted_at IS NULL
ORDER BY tr.created_at DESC, tr.id ASC, c.depth ASC, c.created_at ASC
`

type ListThreadForTargetParams struct {
	TargetKind          string
	TargetID            pgtype.UUID
	CursorRootCreatedAt pgtype.Timestamptz
	ThreadLimit         int32
}

type ListThreadForTargetRow struct {
	ID                pgtype.UUID
	TargetKind        string
	TargetID          pgtype.UUID
	ParentID          pgtype.UUID
	RootID            pgtype.UUID
	Depth             int32
	AuthorUserRef     *int64
	Body              string
	BodyHtml          string
	AnnotationType    *string
	AnnotationData    []byte
	LikeCount         int64
	EditedAt          pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
	OriginServerID    pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	PeerID            pgtype.UUID
	ActorUri          *string
	ActivityUri       *string
	RemoteDisplayName string
}

// Returns every LIVE comment on (kind, id), sorted by root then
// depth-first within root (so replies appear under their parent).
// The cursor pagination is on root_id alone — we always return a
// whole thread together, so the cursor advances by root.
//
// Ordering: root_created_at DESC (newest threads first), then within
// a thread by (depth ASC, created_at ASC) so the root is first and
// replies follow in chronological order.
//
// ## Caching note (post-1.22.D audit, 2026-06-09)
//
// The LEFT JOIN against federation_remote_actors below denormalises
// the remote actor's display_name into each comment row in one
// query instead of N+1 row-level GetRemoteActor lookups. This is
// the correct pattern when the joined table is:
//   - small (one row per ever-seen remote actor),
//   - indexed (federation_remote_actors uses actor_uri as PK),
//   - low-churn (display fields refresh on inbound activity only),
//   - hot enough to live in Postgres shared_buffers.
//
// A row-level cache on GetRemoteActor would add invalidation
// surface without saving query work — the planner collapses the
// JOIN into a hash lookup against the indexed actor_uri. The
// GetRemoteActor query in federation/remote/queries.sql is
// currently unused; future row-level callers should re-check this
// comment before adding a cache.
//
// If the comments-list endpoint becomes a perf bottleneck during
// dogfood, the right cache then is the COMMENTS-BY-POST page
// result (one entry per target_id + cursor), not the per-actor
// row. Track via cache.Registry following the cacheDomainPostByID
// pattern in posts/handler.go.
func (q *Queries) ListThreadForTarget(ctx context.Context, arg ListThreadForTargetParams) ([]ListThreadForTargetRow, error) {
	rows, err := q.db.Query(ctx, listThreadForTarget,
		arg.TargetKind,
		arg.TargetID,
		arg.CursorRootCreatedAt,
		arg.ThreadLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadForTargetRow
	for rows.Next() {
		var i ListThreadForTargetRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PeerID,
			&i.ActorUri,
			&i.ActivityUri,
			&i.RemoteDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWhiteboardsForPost = `-- name: ListWhiteboardsForPost :many
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
FROM comments
WHERE target_kind = 'post'
  AND target_id = $1
  AND annotation_type = 'whiteboard'
  AND parent_id IS NULL
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// Sidebar "Whiteboards" surface — every whiteboard sketch on a post,
// newest first. Whiteboards are top-level comments
// (parent_id IS NULL) with annotation_type='whiteboard'; reply
// comments to a whiteboard show up via the existing thread query, not
// here. The comments_whiteboards_idx partial index (migration 00029)
// covers this exactly: (target_kind, target_id, created_at DESC)
// WHERE annotation_type='whiteboard' AND deleted_at IS NULL.
func (q *Queries) ListWhiteboardsForPost(ctx context.Context, targetID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listWhiteboardsForPost, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PeerID,
			&i.ActorUri,
			&i.ActivityUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :execrows
UPDATE comments
   SET deleted_at = NOW(),
       body       = '',
       body_html  = '',
       updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Sets deleted_at + clears body so a soft-deleted comment doesn't
// leak its content in admin views. The trigger decrements the
// target's comment_count.
func (q *Queries) SoftDeleteComment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unblockUser = `-- name: UnblockUser :execrows
DELETE FROM user_blocks
WHERE blocker_user_ref = $1
  AND blocked_user_ref = $2
`

type UnblockUserParams struct {
	BlockerUserRef int64
	BlockedUserRef int64
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unblockUser, arg.BlockerUserRef, arg.BlockedUserRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unfollowUser = `-- name: UnfollowUser :execrows
DELETE FROM user_follows
WHERE follower_user_ref = $1
  AND followee_user_ref = $2
`

type UnfollowUserParams struct {
	FollowerUserRef int64
	FolloweeUserRef int64
}

// Rows-affected so the handler can 404 cleanly when the caller
// wasn't following the target. The handler maps "0 rows deleted"
// to 204 anyway (idempotent unfollow) but having the count makes
// audit + metrics writers happy.
func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unfollowUser, arg.FollowerUserRef, arg.FolloweeUserRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlikeTarget = `-- name: UnlikeTarget :execrows
DELETE FROM likes
WHERE target_kind = $1 AND target_id = $2 AND user_ref = $3
`

type UnlikeTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	UserRef    *int64
}

// Returns 1 if a row was removed (and the trigger decremented the
// counter), 0 if the user didn't have a like to remove. Handler maps
// 0 to a 404 so the client knows its optimistic update was wrong.
func (q *Queries) UnlikeTarget(ctx context.Context, arg UnlikeTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlikeTarget, arg.TargetKind, arg.TargetID, arg.UserRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAnnotationData = `-- name: UpdateAnnotationData :one
UPDATE comments SET
    body            = COALESCE($1, body),
    annotation_data = $2,
    edited_at       = CASE WHEN $1 IS NOT NULL THEN NOW() ELSE edited_at END,
    updated_at      = NOW()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, target_kind, target_id, parent_id, root_id, depth,
          author_user_ref, body, body_html,
          annotation_type, annotation_data,
          like_count, edited_at, deleted_at,
          origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
`

type UpdateAnnotationDataParams struct {
	Body           *string
	AnnotationData []byte
	ID             pgtype.UUID
}

// Narrow update for the doc-viewer's "change color / change style /
// toggle resolved / edit comment body" actions. Replaces the full
// annotation_data blob (the panel sends the merged shape it wants)
// and optionally updates the body text. Caller must guarantee the
// comment is an annotation; we don't enforce annotation_type here so
// the same query serves whiteboard PATCH too if needed later.
func (q *Queries) UpdateAnnotationData(ctx context.Context, arg UpdateAnnotationDataParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateAnnotationData, arg.Body, arg.AnnotationData, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeerID,
		&i.ActorUri,
		&i.ActivityUri,
	)
	return i, err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET
    body            = COALESCE($1,            body),
    body_html       = COALESCE($2,       body_html),
    annotation_type = $3,
    annotation_data = $4,
    edited_at       = CASE WHEN $1 IS NOT NULL THEN NOW() ELSE edited_at END,
    updated_at      = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, target_kind, target_id, parent_id, root_id, depth,
          author_user_ref, body, body_html,
          annotation_type, annotation_data,
          like_count, edited_at, deleted_at,
          origin_server_id, created_at, updated_at, peer_id, actor_uri, activity_uri
`

type UpdateCommentParams struct {
	Body           *string
	BodyHtml       *string
	AnnotationType *string
	AnnotationData []byte
	ID             pgtype.UUID
}

// PATCH-style. body update sets edited_at; body_html is recomputed
// by the caller. Empty annotation_type clears the annotation.
func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment,
		arg.Body,
		arg.BodyHtml,
		arg.AnnotationType,
		arg.AnnotationData,
		arg.ID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PeerID,
		&i.ActorUri,
		&i.ActivityUri,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT ref FROM "user" WHERE ref = $1 LIMIT 1
`

// Cheap existence check used by the follow / block handlers to map
// "no such user" to 404 BEFORE the downstream write would surface a
// less intelligible error. The PK lookup is sub-ms.
func (q *Queries) UserExists(ctx context.Context, ref int64) (int64, error) {
	row := q.db.QueryRow(ctx, userExists, ref)
	var ref_2 int64
	err := row.Scan(&ref_2)
	return ref_2, err
}
