// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package social

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one

INSERT INTO comments (
    id, target_kind, target_id, parent_id, root_id, depth,
    author_user_ref, body, body_html, annotation_type, annotation_data
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, target_kind, target_id, parent_id, root_id, depth,
          author_user_ref, body, body_html,
          annotation_type, annotation_data,
          like_count, edited_at, deleted_at,
          origin_server_id, created_at, updated_at
`

type CreateCommentParams struct {
	ID             pgtype.UUID
	TargetKind     string
	TargetID       pgtype.UUID
	ParentID       pgtype.UUID
	RootID         pgtype.UUID
	Depth          int32
	AuthorUserRef  int64
	Body           string
	BodyHtml       string
	AnnotationType *string
	AnnotationData []byte
}

// ---------------------------------------------------------------------------
// Comments
// ---------------------------------------------------------------------------
// The Go caller generates the id up front so top-level comments can
// have root_id = id at INSERT time (the column is NOT NULL, so we
// can't post-set it). For replies the caller passes the parent's
// root_id; depth comes from parent.depth + 1.
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.ID,
		arg.TargetKind,
		arg.TargetID,
		arg.ParentID,
		arg.RootID,
		arg.Depth,
		arg.AuthorUserRef,
		arg.Body,
		arg.BodyHtml,
		arg.AnnotationType,
		arg.AnnotationData,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getComment = `-- name: GetComment :one
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at
FROM comments
WHERE id = $1
`

func (q *Queries) GetComment(ctx context.Context, id pgtype.UUID) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasUserLikedTarget = `-- name: HasUserLikedTarget :one
SELECT EXISTS (
    SELECT 1 FROM likes
    WHERE target_kind = $1 AND target_id = $2 AND rs_user_id = $3
) AS value
`

type HasUserLikedTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	RsUserID   int64
}

func (q *Queries) HasUserLikedTarget(ctx context.Context, arg HasUserLikedTargetParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasUserLikedTarget, arg.TargetKind, arg.TargetID, arg.RsUserID)
	var value bool
	err := row.Scan(&value)
	return value, err
}

const likeTarget = `-- name: LikeTarget :exec


INSERT INTO likes (target_kind, target_id, rs_user_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type LikeTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	RsUserID   int64
}

// Comments + likes queries. Polymorphic across (target_kind, target_id),
// so one set of queries serves posts, assets, and (later) collections.
// See migration 00020.
// ---------------------------------------------------------------------------
// Likes
// ---------------------------------------------------------------------------
// Idempotent. The PRIMARY KEY (target_kind, target_id, rs_user_id)
// means re-inserting a row the same user already liked is a no-op,
// and the counter trigger doesn't fire a second time.
func (q *Queries) LikeTarget(ctx context.Context, arg LikeTargetParams) error {
	_, err := q.db.Exec(ctx, likeTarget, arg.TargetKind, arg.TargetID, arg.RsUserID)
	return err
}

const listAnnotationsForAsset = `-- name: ListAnnotationsForAsset :many
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at
FROM comments
WHERE target_kind = 'asset'
  AND target_id = $1
  AND annotation_type IS NOT NULL
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

// Future review-mode UI: fetch every annotation comment on an asset
// for overlay rendering. Only comments with annotation_type set are
// returned — the same table, but the partial index makes this
// cheap.
func (q *Queries) ListAnnotationsForAsset(ctx context.Context, targetID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listAnnotationsForAsset, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByAuthor = `-- name: ListCommentsByAuthor :many
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at
FROM comments
WHERE author_user_ref = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCommentsByAuthorParams struct {
	AuthorUserRef int64
	Limit         int32
	Offset        int32
}

// "Things X commented on" — used by the user profile page later.
func (q *Queries) ListCommentsByAuthor(ctx context.Context, arg ListCommentsByAuthorParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listCommentsByAuthor, arg.AuthorUserRef, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLikersOfTarget = `-- name: ListLikersOfTarget :many
SELECT rs_user_id, liked_at
FROM likes
WHERE target_kind = $1 AND target_id = $2
ORDER BY liked_at DESC, rs_user_id ASC
LIMIT $3 OFFSET $4
`

type ListLikersOfTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	Limit      int32
	Offset     int32
}

type ListLikersOfTargetRow struct {
	RsUserID int64
	LikedAt  pgtype.Timestamptz
}

// Used by the post modal's "liked by X, Y, and 17 others" surface.
// Newest likes first; the handler caps at the limit and offers an
// offset cursor for "show more".
func (q *Queries) ListLikersOfTarget(ctx context.Context, arg ListLikersOfTargetParams) ([]ListLikersOfTargetRow, error) {
	rows, err := q.db.Query(ctx, listLikersOfTarget,
		arg.TargetKind,
		arg.TargetID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLikersOfTargetRow
	for rows.Next() {
		var i ListLikersOfTargetRow
		if err := rows.Scan(&i.RsUserID, &i.LikedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreadForTarget = `-- name: ListThreadForTarget :many
WITH thread_roots AS (
    SELECT cr.id, cr.created_at
    FROM comments cr
    WHERE cr.target_kind = $1 AND cr.target_id = $2
      AND cr.parent_id IS NULL
      AND cr.deleted_at IS NULL
      AND ($3::timestamptz IS NULL
           OR cr.created_at < $3::timestamptz)
    ORDER BY cr.created_at DESC, cr.id ASC
    LIMIT $4::int
)
SELECT c.id, c.target_kind, c.target_id, c.parent_id, c.root_id, c.depth,
       c.author_user_ref, c.body, c.body_html,
       c.annotation_type, c.annotation_data,
       c.like_count, c.edited_at, c.deleted_at,
       c.origin_server_id, c.created_at, c.updated_at
FROM comments c
JOIN thread_roots tr ON tr.id = c.root_id
WHERE c.deleted_at IS NULL
ORDER BY tr.created_at DESC, tr.id ASC, c.depth ASC, c.created_at ASC
`

type ListThreadForTargetParams struct {
	TargetKind          string
	TargetID            pgtype.UUID
	CursorRootCreatedAt pgtype.Timestamptz
	ThreadLimit         int32
}

// Returns every LIVE comment on (kind, id), sorted by root then
// depth-first within root (so replies appear under their parent).
// The cursor pagination is on root_id alone — we always return a
// whole thread together, so the cursor advances by root.
//
// Ordering: root_created_at DESC (newest threads first), then within
// a thread by (depth ASC, created_at ASC) so the root is first and
// replies follow in chronological order.
func (q *Queries) ListThreadForTarget(ctx context.Context, arg ListThreadForTargetParams) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listThreadForTarget,
		arg.TargetKind,
		arg.TargetID,
		arg.CursorRootCreatedAt,
		arg.ThreadLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWhiteboardsForPost = `-- name: ListWhiteboardsForPost :many
SELECT id, target_kind, target_id, parent_id, root_id, depth,
       author_user_ref, body, body_html,
       annotation_type, annotation_data,
       like_count, edited_at, deleted_at,
       origin_server_id, created_at, updated_at
FROM comments
WHERE target_kind = 'post'
  AND target_id = $1
  AND annotation_type = 'whiteboard'
  AND parent_id IS NULL
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

// Sidebar "Whiteboards" surface — every whiteboard sketch on a post,
// newest first. Whiteboards are top-level comments
// (parent_id IS NULL) with annotation_type='whiteboard'; reply
// comments to a whiteboard show up via the existing thread query, not
// here. The comments_whiteboards_idx partial index (migration 00029)
// covers this exactly: (target_kind, target_id, created_at DESC)
// WHERE annotation_type='whiteboard' AND deleted_at IS NULL.
func (q *Queries) ListWhiteboardsForPost(ctx context.Context, targetID pgtype.UUID) ([]Comment, error) {
	rows, err := q.db.Query(ctx, listWhiteboardsForPost, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TargetKind,
			&i.TargetID,
			&i.ParentID,
			&i.RootID,
			&i.Depth,
			&i.AuthorUserRef,
			&i.Body,
			&i.BodyHtml,
			&i.AnnotationType,
			&i.AnnotationData,
			&i.LikeCount,
			&i.EditedAt,
			&i.DeletedAt,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteComment = `-- name: SoftDeleteComment :execrows
UPDATE comments
   SET deleted_at = NOW(),
       body       = '',
       body_html  = '',
       updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Sets deleted_at + clears body so a soft-deleted comment doesn't
// leak its content in admin views. The trigger decrements the
// target's comment_count.
func (q *Queries) SoftDeleteComment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteComment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlikeTarget = `-- name: UnlikeTarget :execrows
DELETE FROM likes
WHERE target_kind = $1 AND target_id = $2 AND rs_user_id = $3
`

type UnlikeTargetParams struct {
	TargetKind string
	TargetID   pgtype.UUID
	RsUserID   int64
}

// Returns 1 if a row was removed (and the trigger decremented the
// counter), 0 if the user didn't have a like to remove. Handler maps
// 0 to a 404 so the client knows its optimistic update was wrong.
func (q *Queries) UnlikeTarget(ctx context.Context, arg UnlikeTargetParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlikeTarget, arg.TargetKind, arg.TargetID, arg.RsUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET
    body            = COALESCE($1,            body),
    body_html       = COALESCE($2,       body_html),
    annotation_type = $3,
    annotation_data = $4,
    edited_at       = CASE WHEN $1 IS NOT NULL THEN NOW() ELSE edited_at END,
    updated_at      = NOW()
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, target_kind, target_id, parent_id, root_id, depth,
          author_user_ref, body, body_html,
          annotation_type, annotation_data,
          like_count, edited_at, deleted_at,
          origin_server_id, created_at, updated_at
`

type UpdateCommentParams struct {
	Body           *string
	BodyHtml       *string
	AnnotationType *string
	AnnotationData []byte
	ID             pgtype.UUID
}

// PATCH-style. body update sets edited_at; body_html is recomputed
// by the caller. Empty annotation_type clears the annotation.
func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment,
		arg.Body,
		arg.BodyHtml,
		arg.AnnotationType,
		arg.AnnotationData,
		arg.ID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TargetKind,
		&i.TargetID,
		&i.ParentID,
		&i.RootID,
		&i.Depth,
		&i.AuthorUserRef,
		&i.Body,
		&i.BodyHtml,
		&i.AnnotationType,
		&i.AnnotationData,
		&i.LikeCount,
		&i.EditedAt,
		&i.DeletedAt,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
