// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auth

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiToken struct {
	ID             pgtype.UUID
	RsUserID       int64
	Name           string
	TokenHash      []byte
	Scopes         []string
	ExpiresAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
}

type Capability struct {
	Code        string
	Description string
	CreatedAt   pgtype.Timestamptz
}

type ResourceType struct {
	Ref               int64
	Name              *string
	AllowedExtensions *string
	OrderBy           *int64
	ConfigOptions     *string
	PushMetadata      *int64
	Colour            *int64
	Icon              *string
	Tab               *int64
	PullImages        *int64
}

type Role struct {
	ID             pgtype.UUID
	ParentID       pgtype.UUID
	Name           string
	Description    string
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RoleCapability struct {
	RoleID         pgtype.UUID
	CapabilityCode string
}

type User struct {
	Ref                int64
	Username           *string
	Password           *string
	Fullname           *string
	Email              *string
	Usergroup          *int64
	LastActive         pgtype.Timestamptz
	LoggedIn           *int64
	AcceptedTerms      int64
	AccountExpires     pgtype.Timestamptz
	Session            *string
	PasswordLastChange pgtype.Timestamptz
	LoginTries         int64
	LoginLastTry       pgtype.Timestamptz
	Approved           int64
	Lang               *string
	Created            pgtype.Timestamptz
	Origin             *string
	UniqueHash         *string
}

type UserCapabilityGrant struct {
	RsUserID          int64
	CapabilityCode    string
	GrantedAt         pgtype.Timestamptz
	GrantedByRsUserID *int64
	Note              string
}

type UserCapabilityRevoke struct {
	RsUserID          int64
	CapabilityCode    string
	RevokedAt         pgtype.Timestamptz
	RevokedByRsUserID *int64
	Note              string
}

type UserRole struct {
	RsUserID           int64
	RoleID             pgtype.UUID
	AssignedAt         pgtype.Timestamptz
	AssignedByRsUserID *int64
}
