-- artist-alley migration 00013 — RS data seeds.
--
-- Auto-generated from RS's dbstruct/data_*.txt by
-- scripts/gen-rs-seeds.py. Sister to 00007_rs_baseline_tables.sql
-- (which defines the empty tables); this file fills in the rows RS
-- expects to find on a fresh install so the PHP UI can render
-- against our Postgres DB during the strangler-fig phase.
--
-- ON CONFLICT DO NOTHING keeps the seeds idempotent: applying this
-- migration on a DB that already has user-added rows leaves them
-- alone. The IDENTITY sequences are bumped past the seeded refs so
-- new admin-side INSERTs don't collide.
--
-- Do not edit by hand — re-run scripts/gen-rs-seeds.py instead.

-- +goose Up


-- RS denormalises a TEXT column onto `resource` per metadata field.
-- Stock RS adds these via the admin-field-create flow; we add them
-- up front so hardcoded references like r.field{view_title_field}
-- in do_search.php and collections_functions.php resolve.
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field1" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field3" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field8" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field9" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field10" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field12" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field18" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field25" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field29" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field51" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field52" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field54" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field72" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field73" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field74" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field75" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field76" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field77" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field78" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field79" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field80" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field81" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field82" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field83" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field84" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field85" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field86" TEXT;
ALTER TABLE resource ADD COLUMN IF NOT EXISTS "field87" TEXT;

-- resource_type_field (28 rows from dbstruct/data_resource_type_field.txt)
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (1, 'keywords', 'Keywords - Other', 0, 9, 60, 1, 0, 1, NULL, 1, '2#025', NULL, 0, NULL, 'IPTC:Keywords,Subject,XMP:Keywords', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (3, 'country', 'Country', 0, 9, 80, 1, 0, 1, 'country', 1, '2#101', NULL, 0, NULL, 'IPTC:Country-PrimaryLocationName,XMP:Country', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (8, 'title', 'Title', 0, 0, 10, 1, 0, 1, 'title', 0, '2#005', NULL, 1, NULL, 'IPTC:ObjectName,XMP:title', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (9, 'extract', 'Document extract', 0, 1, 7, 0, 0, 0, NULL, 1, NULL, '<div class="RecordStory">
  <h1>[title]</h1>

  <p>[value]</p>

</div>', 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (10, 'credit', 'Credit', 0, 0, 120, 1, 0, 1, NULL, 1, '2#080', NULL, 0, NULL, 'IPTC:Credit,XMP:Credit', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (12, 'date', 'Date', 0, 4, 90, 1, 0, 1, 'creation_date', 1, '2#055', NULL, 0, NULL, 'DateTimeOriginal,IPTC:DateCreated,XMP:DateCreated', 0, 0, NULL, 0, 1, NULL, 0, 0, 'if ($value!=''''){$value=nicedate($value,false);}', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (18, 'caption', 'Caption', 0, 1, 20, 1, 0, 1, NULL, 1, '2#120', '<div class="item"><h3>[title]</h3><p>[value]</p></div>

<div class="clearerleft"> </div>', 0, NULL, 'IPTC:Caption-Abstract,XMP:Description', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (25, 'notes', 'Notes', 0, 1, 130, 0, 0, 1, NULL, 1, '2#103', '<div class="RecordStory">

  <h1>[title]</h1>

  <p>[value]</p>

</div>', 0, NULL, 'JobID', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (29, 'person', 'Named person(s)', 0, 9, 70, 1, 0, 1, NULL, 1, NULL, NULL, 0, NULL, 'XMP:PersonInImage,XMP:People', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (51, 'originalfilename', 'Original filename', 0, 0, 100, 1, 0, 1, 'file_path', 1, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (52, 'camera', 'Camera make / model', 0, 0, 1600, 0, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'Model', 1, 0, NULL, 0, 1, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (54, 'source', 'Source', 0, 3, 1601, 0, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'XMP:FileSource', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (72, 'text', 'Extracted text', 0, 5, 110, 0, 0, 1, NULL, 0, NULL, '<div class="item"><h3>[title]</h3><p>[value]</p></div><div class="clearerleft"> </div>', 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 1, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (73, 'subject', 'Keywords - Subject', 0, 2, 30, 1, 0, 1, NULL, 1, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (74, 'event', 'Keywords - Event', 0, 2, 50, 1, 0, 1, NULL, 1, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (75, 'emotion', 'Keywords - Emotion', 0, 2, 40, 1, 0, 1, NULL, 1, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (76, 'framerate', 'Frame Rate', 0, 0, 0, 1, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'framerate', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (77, 'videobitrate', 'Video Bitrate', 0, 0, 0, 1, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'videobitrate', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (78, 'aspectratio', 'Aspect Ratio', 0, 0, 0, 1, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'aspectratio', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (79, 'videosize', 'Video Size', 0, 0, 0, 0, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'imagesize', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (80, 'duration', 'Duration', 0, 0, 0, 0, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'duration', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (81, 'channelmode', 'Channel Mode', 0, 0, 0, 1, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'channelmode', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (82, 'samplerate', 'Sample Rate', 0, 0, 0, 0, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'samplerate', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (83, 'audiobitrate', 'Audio Bitrate', 0, 0, 0, 1, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'audiobitrate', 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (84, 'recognised', 'Keywords - Recognised', 0, 9, 0, 1, 0, 0, NULL, 1, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (85, 'landmark', 'Keywords - Landmark', 0, 9, 0, 1, 0, 0, NULL, 1, NULL, NULL, 0, NULL, NULL, 1, 0, NULL, 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (86, 'accessibilityalttext', 'Accessibility - Alt Text', 0, 0, 0, 0, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'AltTextAccessibility', 1, 0, 'Enter text describing the appearance of the image from a visual perspective, focusing on details that are relevant to the purpose and meaning of the image.

A maximum of 250 characters can be entered.', 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, '^.{0,250}$', NULL, NULL, NULL, NULL, 0, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO resource_type_field (ref, name, title, field_constraint, "type", order_by, keywords_index, partial_index, global, resource_column, display_field, iptc_equiv, display_template, required, smart_theme_name, exiftool_field, advanced_search, simple_search, help_text, display_as_dropdown, external_user_access, autocomplete_macro, hide_when_uploading, hide_when_restricted, value_filter, exiftool_filter, omit_when_copying, tooltip_text, regexp_filter, display_condition, onchange_macro, linked_data_field, automatic_nodes_ordering, fits_field, personal_data, include_in_csv_export, browse_bar, read_only, active, full_width, tab, complete_index, sort_method, geomapping) VALUES (87, 'accessibilityextend', 'Accessibility - Extended Description', 0, 1, 0, 0, 0, 0, NULL, 1, NULL, NULL, 0, NULL, 'ExtDescrAccessibility', 1, 0, 'Enter the text describing the appearance of an image from a visual perspective, focusing on relevant details that further describe the meaning and purpose of the image.', 0, 1, NULL, 0, 0, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, 0, 1, 1, 1, 0, 0, 0, 0, NULL) ON CONFLICT (ref) DO NOTHING;
SELECT setval(pg_get_serial_sequence('resource_type_field', 'ref'),
              COALESCE((SELECT MAX(ref) FROM resource_type_field), 1),
              true) WHERE pg_get_serial_sequence('resource_type_field', 'ref') IS NOT NULL;

-- resource_type_field_resource_type (15 rows from dbstruct/data_resource_type_field_resource_type.txt)
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (9, 2) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (52, 1) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (54, 1) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (76, 3) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (77, 3) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (78, 3) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (79, 3) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (80, 4) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (81, 4) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (82, 4) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (83, 4) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (84, 1) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (85, 1) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (86, 1) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;
INSERT INTO resource_type_field_resource_type (resource_type_field, resource_type) VALUES (87, 1) ON CONFLICT (resource_type_field, resource_type) DO NOTHING;

-- tab (1 rows from dbstruct/data_tab.txt)
INSERT INTO tab (ref, name, order_by) VALUES (1, 'Default', 10) ON CONFLICT (ref) DO NOTHING;
SELECT setval(pg_get_serial_sequence('tab', 'ref'),
              COALESCE((SELECT MAX(ref) FROM tab), 1),
              true) WHERE pg_get_serial_sequence('tab', 'ref') IS NOT NULL;

-- usergroup (6 rows from dbstruct/data_usergroup.txt)
INSERT INTO usergroup (ref, name, permissions, parent, search_filter, edit_filter, derestrict_filter, ip_restrict, resource_defaults, config_options, welcome_message, request_mode, allow_registration_selection, group_specific_logo, inherit_flags, search_filter_id, download_limit, download_log_days, edit_filter_id, derestrict_filter_id, group_specific_logo_dark) VALUES (1, 'Administrators', 's,g,c,t,h,r,u,i,e-2,e-1,e0,e1,e3,v,o,m,q,f*,j*,k,R,Ra,Rb,x,hdta,lm,cm', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO usergroup (ref, name, permissions, parent, search_filter, edit_filter, derestrict_filter, ip_restrict, resource_defaults, config_options, welcome_message, request_mode, allow_registration_selection, group_specific_logo, inherit_flags, search_filter_id, download_limit, download_log_days, edit_filter_id, derestrict_filter_id, group_specific_logo_dark) VALUES (2, 'General Users', 's,e-1,e-2,g,d,q,f*,j*,z1,z2,z3', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO usergroup (ref, name, permissions, parent, search_filter, edit_filter, derestrict_filter, ip_restrict, resource_defaults, config_options, welcome_message, request_mode, allow_registration_selection, group_specific_logo, inherit_flags, search_filter_id, download_limit, download_log_days, edit_filter_id, derestrict_filter_id, group_specific_logo_dark) VALUES (3, 'Super Admin', 's,g,c,a,t,h,hdt_ug,u,r,i,e-2,e-1,e0,e1,e2,e3,o,m,g,v,q,f*,j*,k,R,Ra,x,ex', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO usergroup (ref, name, permissions, parent, search_filter, edit_filter, derestrict_filter, ip_restrict, resource_defaults, config_options, welcome_message, request_mode, allow_registration_selection, group_specific_logo, inherit_flags, search_filter_id, download_limit, download_log_days, edit_filter_id, derestrict_filter_id, group_specific_logo_dark) VALUES (4, 'Archivists', 's,g,c,t,h,r,u,i,e1,e2,e3,v,q,f*,j*', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO usergroup (ref, name, permissions, parent, search_filter, edit_filter, derestrict_filter, ip_restrict, resource_defaults, config_options, welcome_message, request_mode, allow_registration_selection, group_specific_logo, inherit_flags, search_filter_id, download_limit, download_log_days, edit_filter_id, derestrict_filter_id, group_specific_logo_dark) VALUES (5, 'Restricted User - Requests Emailed (manual fulfilment)', 's,f*,j*,q,dtu,z1,z2,z3', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL) ON CONFLICT (ref) DO NOTHING;
INSERT INTO usergroup (ref, name, permissions, parent, search_filter, edit_filter, derestrict_filter, ip_restrict, resource_defaults, config_options, welcome_message, request_mode, allow_registration_selection, group_specific_logo, inherit_flags, search_filter_id, download_limit, download_log_days, edit_filter_id, derestrict_filter_id, group_specific_logo_dark) VALUES (6, 'Restricted User - Requests Managed', 's,f*,j*,q,dtu,z1,z2,z3', 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, NULL, NULL, NULL, 0, 0, NULL, NULL, NULL) ON CONFLICT (ref) DO NOTHING;
SELECT setval(pg_get_serial_sequence('usergroup', 'ref'),
              COALESCE((SELECT MAX(ref) FROM usergroup), 1),
              true) WHERE pg_get_serial_sequence('usergroup', 'ref') IS NOT NULL;

-- preview_size (6 rows from dbstruct/data_preview_size.txt)
INSERT INTO preview_size (ref, id, width, height, padtosize, name, internal, allow_preview, allow_restricted, quality) VALUES (1, 'thm', 200, 200, 0, 'Thumbnail', 1, 0, 0, 0) ON CONFLICT (ref) DO NOTHING;
INSERT INTO preview_size (ref, id, width, height, padtosize, name, internal, allow_preview, allow_restricted, quality) VALUES (2, 'pre', 900, 540, 0, 'Preview', 1, 0, 1, 0) ON CONFLICT (ref) DO NOTHING;
INSERT INTO preview_size (ref, id, width, height, padtosize, name, internal, allow_preview, allow_restricted, quality) VALUES (3, 'scr', 1400, 800, 0, 'Screen', 0, 1, 0, 0) ON CONFLICT (ref) DO NOTHING;
INSERT INTO preview_size (ref, id, width, height, padtosize, name, internal, allow_preview, allow_restricted, quality) VALUES (4, 'lpr', 2000, 2000, 0, 'Low resolution print', 0, 0, 0, 0) ON CONFLICT (ref) DO NOTHING;
INSERT INTO preview_size (ref, id, width, height, padtosize, name, internal, allow_preview, allow_restricted, quality) VALUES (5, 'hpr', 999999, 999999, 0, 'High resolution print', 0, 0, 0, 0) ON CONFLICT (ref) DO NOTHING;
INSERT INTO preview_size (ref, id, width, height, padtosize, name, internal, allow_preview, allow_restricted, quality) VALUES (6, 'col', 100, 75, 0, 'Collection', 1, 0, 0, 0) ON CONFLICT (ref) DO NOTHING;
SELECT setval(pg_get_serial_sequence('preview_size', 'ref'),
              COALESCE((SELECT MAX(ref) FROM preview_size), 1),
              true) WHERE pg_get_serial_sequence('preview_size', 'ref') IS NOT NULL;


-- +goose Down

-- Seed removal is a destructive operation that would break the PHP
-- layer until the data is re-seeded. Drop the goose version manually
-- if you really need to roll this back.
SELECT 1;
