// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package metadata

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAssetFieldValueHistory = `-- name: AppendAssetFieldValueHistory :exec

INSERT INTO asset_field_value_history (
    asset_id, field_id, old_value, new_value, set_by, changed_by_user_ref
) VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendAssetFieldValueHistoryParams struct {
	AssetID          pgtype.UUID
	FieldID          pgtype.UUID
	OldValue         []byte
	NewValue         []byte
	SetBy            string
	ChangedByUserRef *int64
}

// ---------------------------------------------------------------------------
// asset_field_value_history — append-only audit
// ---------------------------------------------------------------------------
func (q *Queries) AppendAssetFieldValueHistory(ctx context.Context, arg AppendAssetFieldValueHistoryParams) error {
	_, err := q.db.Exec(ctx, appendAssetFieldValueHistory,
		arg.AssetID,
		arg.FieldID,
		arg.OldValue,
		arg.NewValue,
		arg.SetBy,
		arg.ChangedByUserRef,
	)
	return err
}

const appendCollectionFieldValueHistory = `-- name: AppendCollectionFieldValueHistory :exec

INSERT INTO collection_field_value_history (
    collection_id, field_id, old_value, new_value, set_by, changed_by_user_ref
) VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendCollectionFieldValueHistoryParams struct {
	CollectionID     pgtype.UUID
	FieldID          pgtype.UUID
	OldValue         []byte
	NewValue         []byte
	SetBy            string
	ChangedByUserRef *int64
}

// ---------------------------------------------------------------------------
// collection_field_value_history — append-only audit (Phase 1.9.B).
// Same JSONB pair shape as asset_field_value_history; handler is
// responsible for serialising values before writing.
// ---------------------------------------------------------------------------
func (q *Queries) AppendCollectionFieldValueHistory(ctx context.Context, arg AppendCollectionFieldValueHistoryParams) error {
	_, err := q.db.Exec(ctx, appendCollectionFieldValueHistory,
		arg.CollectionID,
		arg.FieldID,
		arg.OldValue,
		arg.NewValue,
		arg.SetBy,
		arg.ChangedByUserRef,
	)
	return err
}

const archiveFieldDefinition = `-- name: ArchiveFieldDefinition :exec
UPDATE field_definition
   SET status = 'archived', updated_at = NOW(), updated_by_user_ref = $2
 WHERE id = $1 AND status <> 'archived'
`

type ArchiveFieldDefinitionParams struct {
	ID               pgtype.UUID
	UpdatedByUserRef *int64
}

// Soft-archive — keeps the row and any historic values so audit
// trails stay readable. Use a UPDATE that bumps status; we never
// DELETE field defs in normal flow.
func (q *Queries) ArchiveFieldDefinition(ctx context.Context, arg ArchiveFieldDefinitionParams) error {
	_, err := q.db.Exec(ctx, archiveFieldDefinition, arg.ID, arg.UpdatedByUserRef)
	return err
}

const createFieldDefinition = `-- name: CreateFieldDefinition :one
INSERT INTO field_definition (
    code, label, description, type, options, required, searchable,
    applies_to, read_capability, write_capability,
    display_order, display_group, status,
    created_by_user_ref, updated_by_user_ref, subject_kind, default_value,
    open_vocabulary
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14,$15,$16,$17)
RETURNING id, code, label, description, type, options, required, searchable,
          applies_to, read_capability, write_capability,
          display_order, display_group, status,
          deprecated_replacement_id, origin_server_id,
          created_at, updated_at, created_by_user_ref, updated_by_user_ref,
          subject_kind, extraction_source, extraction_mode, default_value,
          open_vocabulary, mirrors_column, show_on_card,
          show_in_advanced_search, show_on_upload, edit_tab,
          read_only, regexp_filter
`

type CreateFieldDefinitionParams struct {
	Code             string
	Label            string
	Description      string
	Type             string
	Options          []byte
	Required         bool
	Searchable       bool
	AppliesTo        []int64
	ReadCapability   *string
	WriteCapability  *string
	DisplayOrder     int32
	DisplayGroup     string
	Status           string
	CreatedByUserRef *int64
	SubjectKind      string
	DefaultValue     []byte
	OpenVocabulary   bool
}

func (q *Queries) CreateFieldDefinition(ctx context.Context, arg CreateFieldDefinitionParams) (FieldDefinition, error) {
	row := q.db.QueryRow(ctx, createFieldDefinition,
		arg.Code,
		arg.Label,
		arg.Description,
		arg.Type,
		arg.Options,
		arg.Required,
		arg.Searchable,
		arg.AppliesTo,
		arg.ReadCapability,
		arg.WriteCapability,
		arg.DisplayOrder,
		arg.DisplayGroup,
		arg.Status,
		arg.CreatedByUserRef,
		arg.SubjectKind,
		arg.DefaultValue,
		arg.OpenVocabulary,
	)
	var i FieldDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.Searchable,
		&i.AppliesTo,
		&i.ReadCapability,
		&i.WriteCapability,
		&i.DisplayOrder,
		&i.DisplayGroup,
		&i.Status,
		&i.DeprecatedReplacementID,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserRef,
		&i.UpdatedByUserRef,
		&i.SubjectKind,
		&i.ExtractionSource,
		&i.ExtractionMode,
		&i.DefaultValue,
		&i.OpenVocabulary,
		&i.MirrorsColumn,
		&i.ShowOnCard,
		&i.ShowInAdvancedSearch,
		&i.ShowOnUpload,
		&i.EditTab,
		&i.ReadOnly,
		&i.RegexpFilter,
	)
	return i, err
}

const deleteAssetFieldValue = `-- name: DeleteAssetFieldValue :exec
DELETE FROM asset_field_value WHERE asset_id = $1 AND field_id = $2
`

type DeleteAssetFieldValueParams struct {
	AssetID pgtype.UUID
	FieldID pgtype.UUID
}

func (q *Queries) DeleteAssetFieldValue(ctx context.Context, arg DeleteAssetFieldValueParams) error {
	_, err := q.db.Exec(ctx, deleteAssetFieldValue, arg.AssetID, arg.FieldID)
	return err
}

const deleteCollectionFieldValue = `-- name: DeleteCollectionFieldValue :exec
DELETE FROM collection_field_value
WHERE collection_id = $1 AND field_id = $2
`

type DeleteCollectionFieldValueParams struct {
	CollectionID pgtype.UUID
	FieldID      pgtype.UUID
}

func (q *Queries) DeleteCollectionFieldValue(ctx context.Context, arg DeleteCollectionFieldValueParams) error {
	_, err := q.db.Exec(ctx, deleteCollectionFieldValue, arg.CollectionID, arg.FieldID)
	return err
}

const deleteFieldDefaultOverride = `-- name: DeleteFieldDefaultOverride :execrows
DELETE FROM field_default_override WHERE field_id = $1 AND team_id = $2
`

type DeleteFieldDefaultOverrideParams struct {
	FieldID pgtype.UUID
	TeamID  pgtype.UUID
}

func (q *Queries) DeleteFieldDefaultOverride(ctx context.Context, arg DeleteFieldDefaultOverrideParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFieldDefaultOverride, arg.FieldID, arg.TeamID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssetFieldValue = `-- name: GetAssetFieldValue :one
SELECT v.asset_id, v.field_id, v.value_text, v.value_num, v.value_date,
       v.value_options, v.value_ref, v.set_by, v.set_at, v.set_by_user_ref,
       f.code, f.type
FROM asset_field_value v
JOIN field_definition f ON f.id = v.field_id
WHERE v.asset_id = $1 AND v.field_id = $2
`

type GetAssetFieldValueParams struct {
	AssetID pgtype.UUID
	FieldID pgtype.UUID
}

type GetAssetFieldValueRow struct {
	AssetID      pgtype.UUID
	FieldID      pgtype.UUID
	ValueText    *string
	ValueNum     *float64
	ValueDate    pgtype.Timestamptz
	ValueOptions []string
	ValueRef     pgtype.UUID
	SetBy        string
	SetAt        pgtype.Timestamptz
	SetByUserRef *int64
	Code         string
	Type         string
}

func (q *Queries) GetAssetFieldValue(ctx context.Context, arg GetAssetFieldValueParams) (GetAssetFieldValueRow, error) {
	row := q.db.QueryRow(ctx, getAssetFieldValue, arg.AssetID, arg.FieldID)
	var i GetAssetFieldValueRow
	err := row.Scan(
		&i.AssetID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueNum,
		&i.ValueDate,
		&i.ValueOptions,
		&i.ValueRef,
		&i.SetBy,
		&i.SetAt,
		&i.SetByUserRef,
		&i.Code,
		&i.Type,
	)
	return i, err
}

const getAssetMirrorSubject = `-- name: GetAssetMirrorSubject :one
SELECT owner_user_ref, team_id
  FROM assets
 WHERE id = $1 AND deleted_at IS NULL
`

type GetAssetMirrorSubjectRow struct {
	OwnerUserRef *int64
	TeamID       pgtype.UUID
}

// The authorisation probe for a mirrored write. A mirrored field's
// payload is an `assets` column, so the gate that binds is the COLUMN's
// (owner / team-scoped assets.admin / global), not the field plane's
// "any authenticated caller". Deliberately the same projection
// assets.GetAssetMutationSubject reads, for the same reason: the gate
// needs a nullable owner alongside team_id and must answer for a row the
// caller may not be entitled to read.
func (q *Queries) GetAssetMirrorSubject(ctx context.Context, id pgtype.UUID) (GetAssetMirrorSubjectRow, error) {
	row := q.db.QueryRow(ctx, getAssetMirrorSubject, id)
	var i GetAssetMirrorSubjectRow
	err := row.Scan(&i.OwnerUserRef, &i.TeamID)
	return i, err
}

const getCollectionFieldValue = `-- name: GetCollectionFieldValue :one
SELECT v.collection_id, v.field_id, v.value_text, v.value_num, v.value_date,
       v.value_options, v.value_ref, v.set_by, v.set_at, v.set_by_user_ref,
       f.code, f.label, f.type, f.options,
       r.id AS ref_asset_id,
       COALESCE(r.title, '')::TEXT AS ref_asset_title
FROM collection_field_value v
JOIN field_definition f ON f.id = v.field_id
LEFT JOIN assets r ON r.id = v.value_ref AND r.deleted_at IS NULL
WHERE v.collection_id = $1 AND v.field_id = $2
`

type GetCollectionFieldValueParams struct {
	CollectionID pgtype.UUID
	FieldID      pgtype.UUID
}

type GetCollectionFieldValueRow struct {
	CollectionID  pgtype.UUID
	FieldID       pgtype.UUID
	ValueText     *string
	ValueNum      *float64
	ValueDate     pgtype.Timestamptz
	ValueOptions  []string
	ValueRef      pgtype.UUID
	SetBy         string
	SetAt         pgtype.Timestamptz
	SetByUserRef  *int64
	Code          string
	Label         string
	Type          string
	Options       []byte
	RefAssetID    pgtype.UUID
	RefAssetTitle string
}

// Same joins as ListCollectionFieldValues, for the single-row read the
// write path snapshots against — code/label/type/options and the
// reference title all resolve here too (#840).
func (q *Queries) GetCollectionFieldValue(ctx context.Context, arg GetCollectionFieldValueParams) (GetCollectionFieldValueRow, error) {
	row := q.db.QueryRow(ctx, getCollectionFieldValue, arg.CollectionID, arg.FieldID)
	var i GetCollectionFieldValueRow
	err := row.Scan(
		&i.CollectionID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueNum,
		&i.ValueDate,
		&i.ValueOptions,
		&i.ValueRef,
		&i.SetBy,
		&i.SetAt,
		&i.SetByUserRef,
		&i.Code,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.RefAssetID,
		&i.RefAssetTitle,
	)
	return i, err
}

const getDefaultUserDisplay = `-- name: GetDefaultUserDisplay :one
SELECT COALESCE(NULLIF(fullname, ''), username, '')::TEXT AS display
FROM "user" WHERE ref = $1
`

// Display name for the `uploading_user` context value. fullname when
// the user set one, username otherwise — the same fallback every other
// surface shows, so a default matches what the byline says.
func (q *Queries) GetDefaultUserDisplay(ctx context.Context, ref int64) (string, error) {
	row := q.db.QueryRow(ctx, getDefaultUserDisplay, ref)
	var display string
	err := row.Scan(&display)
	return display, err
}

const getFieldDefinitionByCode = `-- name: GetFieldDefinitionByCode :one
SELECT id, code, label, description, type, options, required, searchable,
       applies_to, read_capability, write_capability,
       display_order, display_group, status,
       deprecated_replacement_id, origin_server_id,
       created_at, updated_at, created_by_user_ref, updated_by_user_ref,
       subject_kind, extraction_source, extraction_mode, default_value,
       open_vocabulary, mirrors_column, show_on_card,
       show_in_advanced_search, show_on_upload, edit_tab,
       read_only, regexp_filter
FROM field_definition WHERE code = $1
`

func (q *Queries) GetFieldDefinitionByCode(ctx context.Context, code string) (FieldDefinition, error) {
	row := q.db.QueryRow(ctx, getFieldDefinitionByCode, code)
	var i FieldDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.Searchable,
		&i.AppliesTo,
		&i.ReadCapability,
		&i.WriteCapability,
		&i.DisplayOrder,
		&i.DisplayGroup,
		&i.Status,
		&i.DeprecatedReplacementID,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserRef,
		&i.UpdatedByUserRef,
		&i.SubjectKind,
		&i.ExtractionSource,
		&i.ExtractionMode,
		&i.DefaultValue,
		&i.OpenVocabulary,
		&i.MirrorsColumn,
		&i.ShowOnCard,
		&i.ShowInAdvancedSearch,
		&i.ShowOnUpload,
		&i.EditTab,
		&i.ReadOnly,
		&i.RegexpFilter,
	)
	return i, err
}

const getFieldDefinitionByID = `-- name: GetFieldDefinitionByID :one
SELECT id, code, label, description, type, options, required, searchable,
       applies_to, read_capability, write_capability,
       display_order, display_group, status,
       deprecated_replacement_id, origin_server_id,
       created_at, updated_at, created_by_user_ref, updated_by_user_ref,
       subject_kind, extraction_source, extraction_mode, default_value,
       open_vocabulary, mirrors_column, show_on_card,
       show_in_advanced_search, show_on_upload, edit_tab,
       read_only, regexp_filter
FROM field_definition WHERE id = $1
`

func (q *Queries) GetFieldDefinitionByID(ctx context.Context, id pgtype.UUID) (FieldDefinition, error) {
	row := q.db.QueryRow(ctx, getFieldDefinitionByID, id)
	var i FieldDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.Searchable,
		&i.AppliesTo,
		&i.ReadCapability,
		&i.WriteCapability,
		&i.DisplayOrder,
		&i.DisplayGroup,
		&i.Status,
		&i.DeprecatedReplacementID,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserRef,
		&i.UpdatedByUserRef,
		&i.SubjectKind,
		&i.ExtractionSource,
		&i.ExtractionMode,
		&i.DefaultValue,
		&i.OpenVocabulary,
		&i.MirrorsColumn,
		&i.ShowOnCard,
		&i.ShowInAdvancedSearch,
		&i.ShowOnUpload,
		&i.EditTab,
		&i.ReadOnly,
		&i.RegexpFilter,
	)
	return i, err
}

const getFieldMirrorColumn = `-- name: GetFieldMirrorColumn :one
SELECT mirrors_column FROM field_definition WHERE id = $1
`

// Just the declaration, for a caller that holds a field id and no row —
// the extraction writer adapter, which is handed a bare field id by the
// applier.
func (q *Queries) GetFieldMirrorColumn(ctx context.Context, id pgtype.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getFieldMirrorColumn, id)
	var mirrors_column *string
	err := row.Scan(&mirrors_column)
	return mirrors_column, err
}

const getReferencedAsset = `-- name: GetReferencedAsset :one
SELECT a.id, a.title
FROM assets a
WHERE a.id = $1 AND a.deleted_at IS NULL
`

type GetReferencedAssetRow struct {
	ID    pgtype.UUID
	Title string
}

// The resolve-one counterpart of ListAssetFieldValues' LEFT JOIN, for
// the upsert path — which returns a single AssetFieldValue and has no
// join to ride along on.
//
// It exists so SetAssetFieldValue's 200 body carries the same
// resolved_reference the list path does. #775 is the precedent and the
// warning: buildAssetValue was created because one consumer resolved
// and another printed the slug, and shipping a DTO field that only one
// of two endpoints ever populates rebuilds that exact asymmetry.
//
// Same visibility rule as the join, for the same reason (see above).
func (q *Queries) GetReferencedAsset(ctx context.Context, id pgtype.UUID) (GetReferencedAssetRow, error) {
	row := q.db.QueryRow(ctx, getReferencedAsset, id)
	var i GetReferencedAssetRow
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getTeamForDefaultOverride = `-- name: GetTeamForDefaultOverride :one
SELECT id, slug, name FROM teams WHERE id = $1 AND deleted_at IS NULL
`

type GetTeamForDefaultOverrideRow struct {
	ID   pgtype.UUID
	Slug string
	Name string
}

func (q *Queries) GetTeamForDefaultOverride(ctx context.Context, id pgtype.UUID) (GetTeamForDefaultOverrideRow, error) {
	row := q.db.QueryRow(ctx, getTeamForDefaultOverride, id)
	var i GetTeamForDefaultOverrideRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const insertAssetFieldValueIfAbsent = `-- name: InsertAssetFieldValueIfAbsent :execrows
INSERT INTO asset_field_value (
    asset_id, field_id,
    value_text, value_num, value_date, value_options, value_ref,
    set_by, set_at
) VALUES (
    $1, $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    'default', NOW()
)
ON CONFLICT (asset_id, field_id) DO NOTHING
`

type InsertAssetFieldValueIfAbsentParams struct {
	AssetID      pgtype.UUID
	FieldID      pgtype.UUID
	ValueText    *string
	ValueNum     *float64
	ValueDate    pgtype.Timestamptz
	ValueOptions []string
	ValueRef     pgtype.UUID
}

// The defaults writer. ON CONFLICT DO NOTHING makes "a default never
// overwrites a value that is already set" a property of the STATEMENT
// rather than of the order the caller happens to do things in. The
// caller today runs at asset creation, where by construction there is
// nothing to overwrite; encoding the rule here means a future caller
// (a re-apply action, a backfill) cannot reintroduce the clobber by
// being placed differently in the sequence.
//
// set_by is hard-wired to 'default' — this statement exists only for
// the defaults path, and a provenance the applier can recognise is the
// whole reason it can tell "a default is sitting here" from "a human
// typed this".
func (q *Queries) InsertAssetFieldValueIfAbsent(ctx context.Context, arg InsertAssetFieldValueIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAssetFieldValueIfAbsent,
		arg.AssetID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueNum,
		arg.ValueDate,
		arg.ValueOptions,
		arg.ValueRef,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAssetDefaultCandidates = `-- name: ListAssetDefaultCandidates :many

SELECT f.id, f.code, f.type, f.options, f.default_value, f.mirrors_column,
       o.team_id, o.default_value AS override_value
FROM field_definition f
LEFT JOIN field_default_override o
       ON o.field_id = f.id
      AND o.team_id = ANY($1::UUID[])
WHERE f.subject_kind = 'asset'
  AND f.status = 'active'
  AND (cardinality(f.applies_to) = 0 OR $2::BIGINT = ANY(f.applies_to))
  AND (f.default_value IS NOT NULL OR o.default_value IS NOT NULL)
ORDER BY f.code
`

type ListAssetDefaultCandidatesParams struct {
	TeamIds []pgtype.UUID
	Rt      int64
}

type ListAssetDefaultCandidatesRow struct {
	ID            pgtype.UUID
	Code          string
	Type          string
	Options       []byte
	DefaultValue  []byte
	MirrorsColumn *string
	TeamID        pgtype.UUID
	OverrideValue []byte
}

// ---------------------------------------------------------------------------
// Upload defaults (#793) — ADR 0081 §3
// ---------------------------------------------------------------------------
// Every asset field that carries a default OR has one overridden by a
// team the uploader belongs to, for the asset type being created.
//
// The LEFT JOIN is what makes both halves of the precedence chain
// readable in ONE query: a field with only a field default comes back
// once with a NULL override, a field a team has overridden comes back
// with the override alongside, and a field whose ONLY default is a team
// override still comes back (the WHERE accepts either side). Emitting
// one row per matching override rather than picking a winner in SQL is
// deliberate — Go can then see that two of the uploader's teams both
// override the same field, which is the case that has no correct answer
// and must not be silently resolved by an ORDER BY.
//
// applies_to is honoured here: a field that does not apply to this asset
// type has no business defaulting onto it.
//
// f.mirrors_column rides along because a default on a MIRRORED field
// (#822) fills the COLUMN, not asset_field_value — the guard trigger
// refuses the latter — and this pass has to know which it is holding
// before it writes.
func (q *Queries) ListAssetDefaultCandidates(ctx context.Context, arg ListAssetDefaultCandidatesParams) ([]ListAssetDefaultCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAssetDefaultCandidates, arg.TeamIds, arg.Rt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetDefaultCandidatesRow
	for rows.Next() {
		var i ListAssetDefaultCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Type,
			&i.Options,
			&i.DefaultValue,
			&i.MirrorsColumn,
			&i.TeamID,
			&i.OverrideValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetFieldValueHistory = `-- name: ListAssetFieldValueHistory :many
SELECT id, asset_id, field_id, old_value, new_value,
       changed_at, changed_by_user_ref, set_by
FROM asset_field_value_history
WHERE asset_id = $1
  AND ($2::UUID IS NULL OR field_id = $2::UUID)
ORDER BY changed_at DESC
LIMIT $3::INTEGER
`

type ListAssetFieldValueHistoryParams struct {
	AssetID  pgtype.UUID
	FieldID  pgtype.UUID
	RowLimit int32
}

// Newest-first. Bounded by limit; callers paginate via cursor on
// changed_at if/when this gets big.
func (q *Queries) ListAssetFieldValueHistory(ctx context.Context, arg ListAssetFieldValueHistoryParams) ([]AssetFieldValueHistory, error) {
	rows, err := q.db.Query(ctx, listAssetFieldValueHistory, arg.AssetID, arg.FieldID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetFieldValueHistory
	for rows.Next() {
		var i AssetFieldValueHistory
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.FieldID,
			&i.OldValue,
			&i.NewValue,
			&i.ChangedAt,
			&i.ChangedByUserRef,
			&i.SetBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetFieldValues = `-- name: ListAssetFieldValues :many

SELECT v.field_id, v.value_text, v.value_num, v.value_date, v.value_options, v.value_ref,
       v.set_by, v.set_at, v.set_by_user_ref,
       f.code, f.label, f.type, f.status, f.options,
       f.display_group, f.display_order,
       r.id AS ref_asset_id,
       -- COALESCE rather than a bare r.title: sqlc infers a LEFT-joined
       -- NOT NULL column as non-nullable and would scan a NULL into a
       -- string. Presence is carried by ref_asset_id.Valid instead,
       -- which is unambiguous — and an empty title is a real state
       -- (assets.title DEFAULT '') that the client renders as the id.
       COALESCE(r.title, '')::TEXT AS ref_asset_title
FROM asset_field_value v
JOIN field_definition f ON f.id = v.field_id
LEFT JOIN assets r ON r.id = v.value_ref AND r.deleted_at IS NULL
WHERE v.asset_id = $1
ORDER BY f.display_group, f.display_order, f.code
`

type ListAssetFieldValuesRow struct {
	FieldID       pgtype.UUID
	ValueText     *string
	ValueNum      *float64
	ValueDate     pgtype.Timestamptz
	ValueOptions  []string
	ValueRef      pgtype.UUID
	SetBy         string
	SetAt         pgtype.Timestamptz
	SetByUserRef  *int64
	Code          string
	Label         string
	Type          string
	Status        string
	Options       []byte
	DisplayGroup  string
	DisplayOrder  int32
	RefAssetID    pgtype.UUID
	RefAssetTitle string
}

// ---------------------------------------------------------------------------
// asset_field_value — the actual values
// ---------------------------------------------------------------------------
// All field values for an asset, joined with the field def so the
// handler can normalise the typed columns to a single JSON shape
// per field type. Filtered to active fields (deprecated ones still
// return so the UI can show "this value was set on a deprecated
// field; please re-enter").
// f.options rides along so the handler can resolve a stored select
// slug to its label and lifecycle without a second query: the join to
// field_definition is already here for the code/label/type, so the
// column is free.
//
// The LEFT JOIN to assets does the same job for `reference` values
// (#817): value_ref stores a bare UUID, so without it every reference
// field renders as a raw id. One join, no extra round trip, no N+1 —
// and because it is a LEFT join, a value that does not resolve simply
// yields NULLs and the handler omits resolved_reference.
//
// `r.deleted_at IS NULL` IS THE VISIBILITY RULE, not an incidental
// tidy-up. It is exactly visibility.Predicate for (EntityAsset,
// authenticated) — see ADR 0063/0064: a title is row-plane metadata,
// and for an authenticated caller the asset row predicate is
// soft-delete and nothing else. The anonymous branch of that predicate
// (status/sensitivity/processing) is deliberately NOT reproduced here
// because it is unreachable: GetAssetFields 401s a nil identity, so no
// anonymous caller ever executes this query. reference_value_e2e_test.go
// asserts both halves of that claim, so if the authenticated predicate
// ever tightens (#210's sensitivity rule) or this endpoint is ever
// opened to anonymous callers, the test fails and points here.
// `f.display_group` / `f.display_order` ride along because a MIRRORED
// field's value never appears in this result — the guard trigger from
// migration 00044 refuses it a row in asset_field_value at all — so
// ListAssetMirroredValues supplies those rows separately and the
// handler merges the two lists. A merge needs the sort keys, and the
// ORDER BY below could not hand them over.
func (q *Queries) ListAssetFieldValues(ctx context.Context, assetID pgtype.UUID) ([]ListAssetFieldValuesRow, error) {
	rows, err := q.db.Query(ctx, listAssetFieldValues, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetFieldValuesRow
	for rows.Next() {
		var i ListAssetFieldValuesRow
		if err := rows.Scan(
			&i.FieldID,
			&i.ValueText,
			&i.ValueNum,
			&i.ValueDate,
			&i.ValueOptions,
			&i.ValueRef,
			&i.SetBy,
			&i.SetAt,
			&i.SetByUserRef,
			&i.Code,
			&i.Label,
			&i.Type,
			&i.Status,
			&i.Options,
			&i.DisplayGroup,
			&i.DisplayOrder,
			&i.RefAssetID,
			&i.RefAssetTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetMirroredValues = `-- name: ListAssetMirroredValues :many

SELECT f.id AS field_id,
       public.asset_mirror_read(a.id, f.mirrors_column) AS value_text,
       f.code, f.label, f.type, f.status, f.options,
       f.display_group, f.display_order,
       a.updated_at AS set_at
  FROM field_definition f
  CROSS JOIN assets a
 WHERE a.id = $1
   AND a.deleted_at IS NULL
   AND f.mirrors_column IS NOT NULL
   AND f.subject_kind = 'asset'
   AND f.status <> 'archived'
   AND coalesce(public.asset_mirror_read(a.id, f.mirrors_column), '') <> ''
 ORDER BY f.display_group, f.display_order, f.code
`

type ListAssetMirroredValuesRow struct {
	FieldID      pgtype.UUID
	ValueText    string
	Code         string
	Label        string
	Type         string
	Status       string
	Options      []byte
	DisplayGroup string
	DisplayOrder int32
	SetAt        pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// MIRRORED fields — a definition that declares `mirrors_column` is a VIEW
// onto that column of `assets`, not storage of its own (#822, migration
// 00044).
//
// Every query below obtains the column from `field_definition.mirrors_column`
// and hands it to the accessor functions the migration installs. NOTHING in
// this file, or in Go, names `title` or `description`: the CHECK constraint on
// the column is the only enumeration of what is mirrorable, so widening the
// set is a migration and not a sweep through the query layer.
// ---------------------------------------------------------------------------
// The mirrored half of ListAssetFieldValues. Those rows cannot come from
// that query because they do not exist in asset_field_value and never
// will — the guard trigger refuses them — so they are projected from the
// column here and merged by the handler on (display_group, display_order,
// code), the same order the stored half arrives in.
//
// An EMPTY column yields no row, which is the same contract the stored
// half honours: a field nobody has set has no entry, and the mirrorable
// columns default to the empty string, which is how they say "unset".
// Without this a mirrored field would appear on every asset in the
// catalogue carrying a blank value.
//
// Archived fields are excluded. The stored half returns them (a value on
// an archived field is still data an editor must be able to see and
// clear); a mirrored field has nothing of its own to strand, so an
// archived one is simply off.
//
// The soft-delete rule is asset_mirror_read's, so it is stated once — see
// ListAssetFieldValues' note on why row-plane visibility for an
// authenticated caller reduces to deleted_at IS NULL.
func (q *Queries) ListAssetMirroredValues(ctx context.Context, id pgtype.UUID) ([]ListAssetMirroredValuesRow, error) {
	rows, err := q.db.Query(ctx, listAssetMirroredValues, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetMirroredValuesRow
	for rows.Next() {
		var i ListAssetMirroredValuesRow
		if err := rows.Scan(
			&i.FieldID,
			&i.ValueText,
			&i.Code,
			&i.Label,
			&i.Type,
			&i.Status,
			&i.Options,
			&i.DisplayGroup,
			&i.DisplayOrder,
			&i.SetAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardFieldValues = `-- name: ListCardFieldValues :many
SELECT a.id AS asset_id,
       f.id AS field_id,
       f.code,
       f.label,
       f.type,
       f.options,
       f.display_group,
       f.display_order,
       -- coalesced to '' rather than left nullable: the two states this
       -- query can produce for "nothing here" — no asset_field_value row and
       -- an empty mirrored column — are one answer to the card, which drops
       -- the entry either way. (It also keeps sqlc from typing a CASE with
       -- NULL branches as interface{}.)
       coalesce(
           CASE WHEN f.mirrors_column IS NOT NULL
                THEN public.asset_mirror_read(a.id, f.mirrors_column)
                ELSE v.value_text
           END, '')::TEXT AS value_text,
       v.value_num,
       v.value_date,
       v.value_options
  FROM assets a
  CROSS JOIN field_definition f
  LEFT JOIN asset_field_value v ON v.asset_id = a.id AND v.field_id = f.id
 WHERE a.id = ANY($1::UUID[])
   AND a.deleted_at IS NULL
   AND f.show_on_card
   AND f.subject_kind = 'asset'
   AND f.status <> 'archived'
   AND (cardinality(f.applies_to) = 0 OR a.asset_type = ANY(f.applies_to))
 ORDER BY a.id, f.display_group, f.display_order, f.code
`

type ListCardFieldValuesRow struct {
	AssetID      pgtype.UUID
	FieldID      pgtype.UUID
	Code         string
	Label        string
	Type         string
	Options      []byte
	DisplayGroup string
	DisplayOrder int32
	ValueText    string
	ValueNum     *float64
	ValueDate    pgtype.Timestamptz
	ValueOptions []string
}

// The at-a-glance field values for a PAGE of assets (#552).
//
// It lives HERE, not in `assets`, since #1133. The collection member
// grid renders the same tiles from the same flag and had never rendered
// one, because /collections/{id}/resources builds its rows in a package
// that cannot import `assets` (assets -> posts -> collections is an
// import cycle) and so had no way to reach this. Restating it there
// would have been a second projection of one display rule — the #665
// defect shape. `metadata` is where the rule it feeds already lives
// (DisplayValue, ADR 0012), and both surfaces now reach it through
// metadata.CardFieldsForAssets.
//
// One query for the whole page, not one per asset. The card is a browse
// surface: an N+1 here is 50 round trips per scroll, and the existing
// per-row ListAssetTags call is the precedent NOT to follow.
//
// Both halves of a field's storage are covered, and the caller cannot tell
// them apart — which is the point of #822's mirror. An ordinary field's
// value comes from asset_field_value; a MIRRORED field's comes from the
// column it declares, because it has no row here and the guard trigger
// guarantees it never will.
//
// The flag is a DISPLAY HINT and nothing here treats it otherwise: it
// SELECTS which fields are candidates and takes no part in deciding which
// assets or which values a caller may see. Row visibility was already
// decided by the caller's own gated page query — ListAssetsPageGated for
// browse, ListCollectionResourcesPageGated for the member grid — before
// this runs, and only readable rows are passed in; a withheld
// placeholder is dropped by id before the call. Gated fields cannot reach the card at all — the CHECK
// constraint in migration 00045 refuses `show_on_card` on a field carrying
// a read_capability, so this query needs no capability argument and cannot
// acquire one by accident.
//
// Typed columns come back raw rather than formatted: metadata.DisplayValue
// resolves a vocabulary slug to its label, and doing that in SQL would be a
// second implementation of a rule ADR 0012 keeps in one place.
func (q *Queries) ListCardFieldValues(ctx context.Context, assetIds []pgtype.UUID) ([]ListCardFieldValuesRow, error) {
	rows, err := q.db.Query(ctx, listCardFieldValues, assetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCardFieldValuesRow
	for rows.Next() {
		var i ListCardFieldValuesRow
		if err := rows.Scan(
			&i.AssetID,
			&i.FieldID,
			&i.Code,
			&i.Label,
			&i.Type,
			&i.Options,
			&i.DisplayGroup,
			&i.DisplayOrder,
			&i.ValueText,
			&i.ValueNum,
			&i.ValueDate,
			&i.ValueOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionFieldValueHistory = `-- name: ListCollectionFieldValueHistory :many
SELECT id, collection_id, field_id, old_value, new_value,
       changed_at, changed_by_user_ref, set_by
FROM collection_field_value_history
WHERE collection_id = $1
  AND ($2::UUID IS NULL OR field_id = $2::UUID)
ORDER BY changed_at DESC
LIMIT $3::INTEGER
`

type ListCollectionFieldValueHistoryParams struct {
	CollectionID pgtype.UUID
	FieldID      pgtype.UUID
	RowLimit     int32
}

type ListCollectionFieldValueHistoryRow struct {
	ID               pgtype.UUID
	CollectionID     pgtype.UUID
	FieldID          pgtype.UUID
	OldValue         []byte
	NewValue         []byte
	ChangedAt        pgtype.Timestamptz
	ChangedByUserRef *int64
	SetBy            string
}

func (q *Queries) ListCollectionFieldValueHistory(ctx context.Context, arg ListCollectionFieldValueHistoryParams) ([]ListCollectionFieldValueHistoryRow, error) {
	rows, err := q.db.Query(ctx, listCollectionFieldValueHistory, arg.CollectionID, arg.FieldID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionFieldValueHistoryRow
	for rows.Next() {
		var i ListCollectionFieldValueHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CollectionID,
			&i.FieldID,
			&i.OldValue,
			&i.NewValue,
			&i.ChangedAt,
			&i.ChangedByUserRef,
			&i.SetBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionFieldValues = `-- name: ListCollectionFieldValues :many

SELECT v.collection_id, v.field_id, v.value_text, v.value_num, v.value_date,
       v.value_options, v.value_ref, v.set_by, v.set_at, v.set_by_user_ref,
       f.code, f.label, f.type, f.options,
       r.id AS ref_asset_id,
       COALESCE(r.title, '')::TEXT AS ref_asset_title
FROM collection_field_value v
JOIN field_definition f ON f.id = v.field_id
LEFT JOIN assets r ON r.id = v.value_ref AND r.deleted_at IS NULL
WHERE v.collection_id = $1
ORDER BY f.display_group, f.display_order, f.code
`

type ListCollectionFieldValuesRow struct {
	CollectionID  pgtype.UUID
	FieldID       pgtype.UUID
	ValueText     *string
	ValueNum      *float64
	ValueDate     pgtype.Timestamptz
	ValueOptions  []string
	ValueRef      pgtype.UUID
	SetBy         string
	SetAt         pgtype.Timestamptz
	SetByUserRef  *int64
	Code          string
	Label         string
	Type          string
	Options       []byte
	RefAssetID    pgtype.UUID
	RefAssetTitle string
}

// ---------------------------------------------------------------------------
// collection_field_value — typed-value storage for collection metadata
// (Phase 1.9.B). Mirrors the asset_field_value pattern one-for-one;
// the value path is identical so debuggers see one shape, not two.
// ---------------------------------------------------------------------------
// The collection sibling of ListAssetFieldValues (#840). It carried NO
// join at all until now, so collection metadata rendered raw slugs and
// bare reference UUIDs where the asset path rendered labels and linked
// titles. The two joins here close that gap and cost nothing extra:
//   - JOIN field_definition brings code/label/type AND f.options, so the
//     handler resolves a stored `select` slug to its label without a
//     second query (exactly what ListAssetFieldValues does).
//   - LEFT JOIN assets resolves a `reference` value's title (#817).
//     `r.deleted_at IS NULL` IS the authenticated-asset visibility rule
//     (ADR 0063/0064), the SAME predicate ListAssetFieldValues' join
//     hard-codes — see that query and
//     TestCollectionReferenceJoinMatchesAuthenticatedAssetPredicate. A
//     target that does not resolve yields NULLs and the handler omits
//     resolved_reference, degrading to the bare id (#839).
func (q *Queries) ListCollectionFieldValues(ctx context.Context, collectionID pgtype.UUID) ([]ListCollectionFieldValuesRow, error) {
	rows, err := q.db.Query(ctx, listCollectionFieldValues, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionFieldValuesRow
	for rows.Next() {
		var i ListCollectionFieldValuesRow
		if err := rows.Scan(
			&i.CollectionID,
			&i.FieldID,
			&i.ValueText,
			&i.ValueNum,
			&i.ValueDate,
			&i.ValueOptions,
			&i.ValueRef,
			&i.SetBy,
			&i.SetAt,
			&i.SetByUserRef,
			&i.Code,
			&i.Label,
			&i.Type,
			&i.Options,
			&i.RefAssetID,
			&i.RefAssetTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDefaultTeamsForUser = `-- name: ListDefaultTeamsForUser :many
SELECT t.id, t.name
FROM team_memberships m
JOIN teams t ON t.id = m.team_id
WHERE m.user_ref = $1
  AND t.deleted_at IS NULL
ORDER BY t.name, t.id
`

type ListDefaultTeamsForUserRow struct {
	ID   pgtype.UUID
	Name string
}

// The uploader's DIRECT team memberships. Not the closure: an ancestor
// team is a permission scope, not a place someone uploads to, and
// expanding it would make a parent team's override apply to uploads it
// never sees.
func (q *Queries) ListDefaultTeamsForUser(ctx context.Context, userRef int64) ([]ListDefaultTeamsForUserRow, error) {
	rows, err := q.db.Query(ctx, listDefaultTeamsForUser, userRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDefaultTeamsForUserRow
	for rows.Next() {
		var i ListDefaultTeamsForUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldDefaultOverrides = `-- name: ListFieldDefaultOverrides :many
SELECT o.field_id, o.team_id, t.slug AS team_slug, t.name AS team_name,
       o.default_value, o.created_at, o.updated_at, o.updated_by_user_ref
FROM field_default_override o
JOIN teams t ON t.id = o.team_id
WHERE o.field_id = $1 AND t.deleted_at IS NULL
ORDER BY t.name, t.id
`

type ListFieldDefaultOverridesRow struct {
	FieldID          pgtype.UUID
	TeamID           pgtype.UUID
	TeamSlug         string
	TeamName         string
	DefaultValue     []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	UpdatedByUserRef *int64
}

func (q *Queries) ListFieldDefaultOverrides(ctx context.Context, fieldID pgtype.UUID) ([]ListFieldDefaultOverridesRow, error) {
	rows, err := q.db.Query(ctx, listFieldDefaultOverrides, fieldID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFieldDefaultOverridesRow
	for rows.Next() {
		var i ListFieldDefaultOverridesRow
		if err := rows.Scan(
			&i.FieldID,
			&i.TeamID,
			&i.TeamSlug,
			&i.TeamName,
			&i.DefaultValue,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedByUserRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldDefinitions = `-- name: ListFieldDefinitions :many

SELECT id, code, label, description, type, options, required, searchable,
       applies_to, read_capability, write_capability,
       display_order, display_group, status,
       deprecated_replacement_id, origin_server_id,
       created_at, updated_at, created_by_user_ref, updated_by_user_ref,
       subject_kind, extraction_source, extraction_mode, default_value,
       open_vocabulary, mirrors_column, show_on_card,
       show_in_advanced_search, show_on_upload, edit_tab,
       read_only, regexp_filter
FROM field_definition
WHERE (
        CASE WHEN $1::TEXT IS NULL
             THEN status <> 'archived'
             ELSE status = $1::TEXT
        END
      )
  AND ($2::TEXT IS NULL OR subject_kind = $2::TEXT)
ORDER BY display_group, display_order, code
`

type ListFieldDefinitionsParams struct {
	Status      *string
	SubjectKind *string
}

// ---------------------------------------------------------------------------
// field_definition — admin-managed schema for what fields exist
// ---------------------------------------------------------------------------
// Returns field defs ordered by group + display_order. Caller can
// post-filter by applies_to in the handler since GIN array membership
// doesn't compose well with our other filters.
//
// Status semantics (#528): an explicit `status` is an equality filter
// (so `status=archived` still surfaces soft-deleted fields for anyone
// who opts in). With no `status`, archived fields are EXCLUDED — they're
// tombstones, and editors that just want "the live schema" (e.g. the
// collection edit modal) must not render them. Active + deprecated stay
// visible by default; deprecated fields can still hold values on
// existing rows, so hiding them would drop live data from the editor.
func (q *Queries) ListFieldDefinitions(ctx context.Context, arg ListFieldDefinitionsParams) ([]FieldDefinition, error) {
	rows, err := q.db.Query(ctx, listFieldDefinitions, arg.Status, arg.SubjectKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldDefinition
	for rows.Next() {
		var i FieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.Description,
			&i.Type,
			&i.Options,
			&i.Required,
			&i.Searchable,
			&i.AppliesTo,
			&i.ReadCapability,
			&i.WriteCapability,
			&i.DisplayOrder,
			&i.DisplayGroup,
			&i.Status,
			&i.DeprecatedReplacementID,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUserRef,
			&i.UpdatedByUserRef,
			&i.SubjectKind,
			&i.ExtractionSource,
			&i.ExtractionMode,
			&i.DefaultValue,
			&i.OpenVocabulary,
			&i.MirrorsColumn,
			&i.ShowOnCard,
			&i.ShowInAdvancedSearch,
			&i.ShowOnUpload,
			&i.EditTab,
			&i.ReadOnly,
			&i.RegexpFilter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFieldDefinitionsForAssetType = `-- name: ListFieldDefinitionsForAssetType :many
SELECT id, code, label, description, type, options, required, searchable,
       applies_to, read_capability, write_capability,
       display_order, display_group, status,
       deprecated_replacement_id, origin_server_id,
       created_at, updated_at, created_by_user_ref, updated_by_user_ref,
       subject_kind, extraction_source, extraction_mode, default_value,
       open_vocabulary, mirrors_column, show_on_card,
       show_in_advanced_search, show_on_upload, edit_tab,
       read_only, regexp_filter
FROM field_definition
WHERE status = 'active'
  AND subject_kind = 'asset'
  AND (cardinality(applies_to) = 0 OR $1::BIGINT = ANY(applies_to))
ORDER BY display_group, display_order, code
`

// Like ListFieldDefinitions but only fields whose applies_to is
// empty (applies to all) OR contains the given asset_type ref.
func (q *Queries) ListFieldDefinitionsForAssetType(ctx context.Context, rt int64) ([]FieldDefinition, error) {
	rows, err := q.db.Query(ctx, listFieldDefinitionsForAssetType, rt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FieldDefinition
	for rows.Next() {
		var i FieldDefinition
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.Description,
			&i.Type,
			&i.Options,
			&i.Required,
			&i.Searchable,
			&i.AppliesTo,
			&i.ReadCapability,
			&i.WriteCapability,
			&i.DisplayOrder,
			&i.DisplayGroup,
			&i.Status,
			&i.DeprecatedReplacementID,
			&i.OriginServerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByUserRef,
			&i.UpdatedByUserRef,
			&i.SubjectKind,
			&i.ExtractionSource,
			&i.ExtractionMode,
			&i.DefaultValue,
			&i.OpenVocabulary,
			&i.MirrorsColumn,
			&i.ShowOnCard,
			&i.ShowInAdvancedSearch,
			&i.ShowOnUpload,
			&i.EditTab,
			&i.ReadOnly,
			&i.RegexpFilter,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequiredCollectionFields = `-- name: ListRequiredCollectionFields :many

SELECT id, code, label, type
FROM field_definition
WHERE subject_kind = 'collection'
  AND status = 'active'
  AND required = TRUE
ORDER BY display_order ASC, label ASC
`

type ListRequiredCollectionFieldsRow struct {
	ID    pgtype.UUID
	Code  string
	Label string
	Type  string
}

// ---------------------------------------------------------------------------
// Required collection-field probe — used by collections.Create to
// gate creation when operators have required collection fields.
// ---------------------------------------------------------------------------
func (q *Queries) ListRequiredCollectionFields(ctx context.Context) ([]ListRequiredCollectionFieldsRow, error) {
	rows, err := q.db.Query(ctx, listRequiredCollectionFields)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequiredCollectionFieldsRow
	for rows.Next() {
		var i ListRequiredCollectionFieldsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFieldDefinitionVocabulary = `-- name: LockFieldDefinitionVocabulary :one
SELECT options, type, open_vocabulary
  FROM field_definition
 WHERE id = $1
   FOR UPDATE
`

type LockFieldDefinitionVocabularyRow struct {
	Options        []byte
	Type           string
	OpenVocabulary bool
}

// Reads the live options document under a ROW LOCK, for the
// accept-and-create path on an open vocabulary (#830).
//
// FOR UPDATE is the whole point. Adding a term rewrites the WHOLE
// options document, so two concurrent writes each minting a different
// new term would both read the pre-write document and the second
// UPDATE would discard the first's term — the last-write-wins gap #737
// records for the admin options editor, except here it happens on an
// ordinary value save that no operator would think of as an edit to the
// field. The lock serialises the read-modify-write; the loser re-reads
// the winner's document inside its own transaction and appends to it.
//
// Reads the row rather than trusting the caller's copy for a second
// reason: the field-by-id LRU can hand back an options document that is
// one write old, and resolving against a stale document is how a term
// gets minted twice.
func (q *Queries) LockFieldDefinitionVocabulary(ctx context.Context, id pgtype.UUID) (LockFieldDefinitionVocabularyRow, error) {
	row := q.db.QueryRow(ctx, lockFieldDefinitionVocabulary, id)
	var i LockFieldDefinitionVocabularyRow
	err := row.Scan(&i.Options, &i.Type, &i.OpenVocabulary)
	return i, err
}

const readAssetMirroredValue = `-- name: ReadAssetMirroredValue :one
SELECT coalesce(public.asset_mirror_read($1, $2), '')::TEXT AS value
`

type ReadAssetMirroredValueParams struct {
	AssetID       pgtype.UUID
	MirrorsColumn string
}

// One mirrored field's value, for the extraction pipeline's skip_if_set
// probe. Empty means unset, and an absent or soft-deleted asset reads
// empty too: both answers are "there is nothing here to preserve", which
// is the only question the probe asks.
func (q *Queries) ReadAssetMirroredValue(ctx context.Context, arg ReadAssetMirroredValueParams) (string, error) {
	row := q.db.QueryRow(ctx, readAssetMirroredValue, arg.AssetID, arg.MirrorsColumn)
	var value string
	err := row.Scan(&value)
	return value, err
}

const rebuildAssetSearchTextForField = `-- name: RebuildAssetSearchTextForField :exec
SELECT rebuild_asset_search_text(p.asset_id)
  FROM asset_field_value p
 WHERE p.field_id = $1
`

// Re-derives `assets.search_text` for every asset holding a value of
// this field (#1016).
//
// `rebuild_asset_search_text` folds a field's values into the document
// only while `f.searchable = TRUE AND f.status = 'active'`, and the
// trigger that calls it fires on writes to asset_field_value — not on
// writes to field_definition. So flipping `searchable` off changed what
// the rule SAID and nothing about what was already indexed: the field's
// values kept answering text queries until something happened to touch
// each asset. An operator who unticks the box has every reason to
// believe they excluded the field, which is precisely the lie #1016
// refused to let a UI toggle ship on top of.
//
// Runs for a status change too, since `status = 'active'` is the other
// conjunct of the same WHERE.
func (q *Queries) RebuildAssetSearchTextForField(ctx context.Context, fieldID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, rebuildAssetSearchTextForField, fieldID)
	return err
}

const rewriteAssetValuesForMergedOption = `-- name: RewriteAssetValuesForMergedOption :execrows

WITH affected AS (
    SELECT p.asset_id, p.field_id, p.value_text AS old_text, p.value_options AS old_options
      FROM asset_field_value p
     WHERE p.field_id = $3
       AND (p.value_text = $4::text OR $4::text = ANY(p.value_options))
     ORDER BY p.asset_id
       FOR UPDATE
), updated AS (
    UPDATE asset_field_value v
       SET value_text = CASE WHEN v.value_text = $4::text THEN $5::text ELSE v.value_text END,
           value_options = CASE
               WHEN v.value_options IS NULL THEN NULL
               ELSE (
                   SELECT array_agg(d.slug ORDER BY d.ord)
                     FROM (
                         SELECT DISTINCT ON (u.slug) u.slug, u.ord
                           FROM unnest(array_replace(v.value_options, $4::text, $5::text))
                                WITH ORDINALITY AS u(slug, ord)
                          ORDER BY u.slug, u.ord
                     ) d
               )
           END
      FROM affected a
     WHERE v.asset_id = a.asset_id AND v.field_id = a.field_id
    RETURNING v.asset_id, v.field_id, v.value_text AS new_text, v.value_options AS new_options,
              a.old_text, a.old_options
)
INSERT INTO asset_field_value_history
    (asset_id, field_id, old_value, new_value, set_by, changed_by_user_ref)
SELECT u.asset_id, u.field_id,
       jsonb_build_object('type', $1::text, 'value',
           CASE WHEN u.old_text IS NOT NULL THEN to_jsonb(u.old_text) ELSE to_jsonb(u.old_options) END),
       jsonb_build_object('type', $1::text, 'value',
           CASE WHEN u.new_text IS NOT NULL THEN to_jsonb(u.new_text) ELSE to_jsonb(u.new_options) END),
       'computed', $2::bigint
  FROM updated u
`

type RewriteAssetValuesForMergedOptionParams struct {
	FieldType    string
	ActorUserRef *int64
	FieldID      pgtype.UUID
	Source       string
	Target       string
}

// ---------------------------------------------------------------------------
// Vocabulary curation — merge (ADR 0092 §4, #789)
// ---------------------------------------------------------------------------
// Points every asset value naming @source at @target, and writes the
// change into the per-value history in the same statement.
//
// ## Why one statement rather than a loop in Go
//
// A merge on a real vocabulary touches thousands of rows. Reading them
// into Go, rewriting each and issuing an UPDATE apiece is thousands of
// round trips inside one transaction, holding locks for the duration —
// and the loop would still have to reimplement the array rewrite the
// expression below does once.
//
// ## Why the history row is not optional
//
// A merge is the ONE vocabulary operation that edits records whose
// owners did not touch them. Skipping the history entry would leave
// `asset_field_value_history` describing a value the asset no longer
// holds, and the audit event for the merge itself cannot fill that gap:
// it says a merge happened, not what any particular asset now says. So
// the same INSERT the ordinary write path performs runs here, sourced
// from the CTE's before-and-after — which is also what makes :execrows
// a truthful count, since one history row is inserted per value
// rewritten.
//
// set_by is 'computed': no human typed this value, and the VALUE row's
// own set_by is deliberately left alone — a keyword that arrived from
// IPTC is still an IPTC keyword after the term it names is renamed.
//
// ## The array rewrite
//
// array_replace alone is wrong when a row already holds BOTH terms:
// {uk, gb} would become {gb, gb}. The unnest/DISTINCT ON/array_agg
// sandwich keeps first-occurrence order and drops the duplicate, which
// is the same shape the write path's slug dedupe produces.
//
// The `search_text` TSVECTOR needs no help here: the AFTER UPDATE
// trigger on asset_field_value rebuilds it per row.
func (q *Queries) RewriteAssetValuesForMergedOption(ctx context.Context, arg RewriteAssetValuesForMergedOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewriteAssetValuesForMergedOption,
		arg.FieldType,
		arg.ActorUserRef,
		arg.FieldID,
		arg.Source,
		arg.Target,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rewriteCollectionValuesForMergedOption = `-- name: RewriteCollectionValuesForMergedOption :execrows
WITH affected AS (
    SELECT p.collection_id, p.field_id, p.value_text AS old_text, p.value_options AS old_options
      FROM collection_field_value p
     WHERE p.field_id = $3
       AND (p.value_text = $4::text OR $4::text = ANY(p.value_options))
     ORDER BY p.collection_id
       FOR UPDATE
), updated AS (
    UPDATE collection_field_value v
       SET value_text = CASE WHEN v.value_text = $4::text THEN $5::text ELSE v.value_text END,
           value_options = CASE
               WHEN v.value_options IS NULL THEN NULL
               ELSE (
                   SELECT array_agg(d.slug ORDER BY d.ord)
                     FROM (
                         SELECT DISTINCT ON (u.slug) u.slug, u.ord
                           FROM unnest(array_replace(v.value_options, $4::text, $5::text))
                                WITH ORDINALITY AS u(slug, ord)
                          ORDER BY u.slug, u.ord
                     ) d
               )
           END
      FROM affected a
     WHERE v.collection_id = a.collection_id AND v.field_id = a.field_id
    RETURNING v.collection_id, v.field_id, v.value_text AS new_text, v.value_options AS new_options,
              a.old_text, a.old_options
)
INSERT INTO collection_field_value_history
    (collection_id, field_id, old_value, new_value, set_by, changed_by_user_ref)
SELECT u.collection_id, u.field_id,
       jsonb_build_object('type', $1::text, 'value',
           CASE WHEN u.old_text IS NOT NULL THEN to_jsonb(u.old_text) ELSE to_jsonb(u.old_options) END),
       jsonb_build_object('type', $1::text, 'value',
           CASE WHEN u.new_text IS NOT NULL THEN to_jsonb(u.new_text) ELSE to_jsonb(u.new_options) END),
       'computed', $2::bigint
  FROM updated u
`

type RewriteCollectionValuesForMergedOptionParams struct {
	FieldType    string
	ActorUserRef *int64
	FieldID      pgtype.UUID
	Source       string
	Target       string
}

// The collection twin of RewriteAssetValuesForMergedOption. Same
// rewrite, same history guarantee, on the collection tables — a merge
// that fixed assets and left collections naming a tombstoned term
// would have moved the drift rather than removed it.
func (q *Queries) RewriteCollectionValuesForMergedOption(ctx context.Context, arg RewriteCollectionValuesForMergedOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rewriteCollectionValuesForMergedOption,
		arg.FieldType,
		arg.ActorUserRef,
		arg.FieldID,
		arg.Source,
		arg.Target,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setFieldDefinitionOptions = `-- name: SetFieldDefinitionOptions :exec
UPDATE field_definition
   SET options = $2, updated_at = NOW()
 WHERE id = $1
`

type SetFieldDefinitionOptionsParams struct {
	ID      pgtype.UUID
	Options []byte
}

// Writes back an options document that gained terms. Deliberately
// narrow — it touches options and nothing else — so it cannot be
// mistaken for the admin editor's whole-definition update.
func (q *Queries) SetFieldDefinitionOptions(ctx context.Context, arg SetFieldDefinitionOptionsParams) error {
	_, err := q.db.Exec(ctx, setFieldDefinitionOptions, arg.ID, arg.Options)
	return err
}

const setFieldExtractionConfig = `-- name: SetFieldExtractionConfig :one
UPDATE field_definition
   SET extraction_source = $2,
       extraction_mode   = $3,
       updated_at        = NOW(),
       updated_by_user_ref = $4
 WHERE id = $1
RETURNING id, code, label, description, type, options, required, searchable,
          applies_to, read_capability, write_capability,
          display_order, display_group, status,
          deprecated_replacement_id, origin_server_id,
          created_at, updated_at, created_by_user_ref, updated_by_user_ref,
          subject_kind, extraction_source, extraction_mode, default_value,
          open_vocabulary, mirrors_column, show_on_card,
          show_in_advanced_search, show_on_upload, edit_tab,
          read_only, regexp_filter
`

type SetFieldExtractionConfigParams struct {
	ID               pgtype.UUID
	ExtractionSource string
	ExtractionMode   string
	UpdatedByUserRef *int64
}

// Phase 1.18.A-2. Wires (or unwires) the metadata-extraction
// pipeline against one field. source=” clears the wiring;
// mode=” is normalised to skip_if_set by the caller.
func (q *Queries) SetFieldExtractionConfig(ctx context.Context, arg SetFieldExtractionConfigParams) (FieldDefinition, error) {
	row := q.db.QueryRow(ctx, setFieldExtractionConfig,
		arg.ID,
		arg.ExtractionSource,
		arg.ExtractionMode,
		arg.UpdatedByUserRef,
	)
	var i FieldDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.Searchable,
		&i.AppliesTo,
		&i.ReadCapability,
		&i.WriteCapability,
		&i.DisplayOrder,
		&i.DisplayGroup,
		&i.Status,
		&i.DeprecatedReplacementID,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserRef,
		&i.UpdatedByUserRef,
		&i.SubjectKind,
		&i.ExtractionSource,
		&i.ExtractionMode,
		&i.DefaultValue,
		&i.OpenVocabulary,
		&i.MirrorsColumn,
		&i.ShowOnCard,
		&i.ShowInAdvancedSearch,
		&i.ShowOnUpload,
		&i.EditTab,
		&i.ReadOnly,
		&i.RegexpFilter,
	)
	return i, err
}

const updateFieldDefinition = `-- name: UpdateFieldDefinition :one
UPDATE field_definition SET
    label                     = COALESCE($1,                     label),
    description               = COALESCE($2,               description),
    options                   = COALESCE($3,                   options),
    required                  = COALESCE($4,                  required),
    searchable                = COALESCE($5,                searchable),
    applies_to                = COALESCE($6,                applies_to),
    read_capability           = COALESCE($7,           read_capability),
    write_capability          = COALESCE($8,          write_capability),
    display_order             = COALESCE($9,             display_order),
    display_group             = COALESCE($10,             display_group),
    open_vocabulary           = COALESCE($11,           open_vocabulary),
    show_on_card              = COALESCE($12,              show_on_card),
    show_in_advanced_search   = COALESCE($13,   show_in_advanced_search),
    show_on_upload            = COALESCE($14,            show_on_upload),
    -- ` + "`" + `edit_tab` + "`" + ` needs a CLEAR path for the same reason ` + "`" + `default_value` + "`" + `
    -- does, and it is the only participation flag that does: the other
    -- two are booleans, where "off" is a value COALESCE can carry, while
    -- "this field belongs to no tab" is NULL — indistinguishable from
    -- "leave it alone" everywhere else in this statement. The explicit
    -- boolean makes un-assigning a tab a deliberate act rather than an
    -- ambiguity in the absence of a value.
    edit_tab                  = CASE WHEN $15::BOOLEAN THEN NULL
                                     ELSE COALESCE($16, edit_tab) END,
    read_only                 = COALESCE($17,                 read_only),
    -- ` + "`" + `regexp_filter` + "`" + ` is the third column needing a CLEAR path, and the
    -- only one of the three that is a PATTERN rather than a label. NULL
    -- is the single canonical "no constraint" (the CHECK refuses ''),
    -- and NULL is also what "leave it alone" looks like to COALESCE —
    -- so removal has to be said out loud, exactly as ` + "`" + `edit_tab` + "`" + ` and
    -- ` + "`" + `default_value` + "`" + ` say it. The handler refuses the two together.
    regexp_filter             = CASE WHEN $18::BOOLEAN THEN NULL
                                     ELSE COALESCE($19, regexp_filter) END,
    status                    = COALESCE($20,                    status),
    deprecated_replacement_id = COALESCE($21, deprecated_replacement_id),
    -- default_value needs a CLEAR path, which COALESCE cannot express:
    -- passing NULL means "leave it alone" everywhere else in this
    -- statement, so "remove the default" would be unsayable. The
    -- explicit boolean makes removal a deliberate act rather than an
    -- ambiguity in the absence of a value.
    default_value             = CASE WHEN $22::BOOLEAN THEN NULL
                                     ELSE COALESCE($23, default_value) END,
    updated_at                = NOW(),
    updated_by_user_ref       = $24
WHERE id = $25
RETURNING id, code, label, description, type, options, required, searchable,
          applies_to, read_capability, write_capability,
          display_order, display_group, status,
          deprecated_replacement_id, origin_server_id,
          created_at, updated_at, created_by_user_ref, updated_by_user_ref,
          subject_kind, extraction_source, extraction_mode, default_value,
          open_vocabulary, mirrors_column, show_on_card,
          show_in_advanced_search, show_on_upload, edit_tab,
          read_only, regexp_filter
`

type UpdateFieldDefinitionParams struct {
	Label                   *string
	Description             *string
	Options                 []byte
	Required                *bool
	Searchable              *bool
	AppliesTo               []int64
	ReadCapability          *string
	WriteCapability         *string
	DisplayOrder            *int32
	DisplayGroup            *string
	OpenVocabulary          *bool
	ShowOnCard              *bool
	ShowInAdvancedSearch    *bool
	ShowOnUpload            *bool
	ClearEditTab            bool
	EditTab                 *string
	ReadOnly                *bool
	ClearRegexpFilter       bool
	RegexpFilter            *string
	Status                  *string
	DeprecatedReplacementID pgtype.UUID
	ClearDefault            bool
	DefaultValue            []byte
	UpdatedByUserRef        *int64
	ID                      pgtype.UUID
}

// COALESCE pattern: NULL args keep current value. `applies_to` is a
// non-nullable column, so it always replaces when the caller
// intends to update it; the handler decides whether to pass NULL or
// an explicit empty array.
func (q *Queries) UpdateFieldDefinition(ctx context.Context, arg UpdateFieldDefinitionParams) (FieldDefinition, error) {
	row := q.db.QueryRow(ctx, updateFieldDefinition,
		arg.Label,
		arg.Description,
		arg.Options,
		arg.Required,
		arg.Searchable,
		arg.AppliesTo,
		arg.ReadCapability,
		arg.WriteCapability,
		arg.DisplayOrder,
		arg.DisplayGroup,
		arg.OpenVocabulary,
		arg.ShowOnCard,
		arg.ShowInAdvancedSearch,
		arg.ShowOnUpload,
		arg.ClearEditTab,
		arg.EditTab,
		arg.ReadOnly,
		arg.ClearRegexpFilter,
		arg.RegexpFilter,
		arg.Status,
		arg.DeprecatedReplacementID,
		arg.ClearDefault,
		arg.DefaultValue,
		arg.UpdatedByUserRef,
		arg.ID,
	)
	var i FieldDefinition
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Label,
		&i.Description,
		&i.Type,
		&i.Options,
		&i.Required,
		&i.Searchable,
		&i.AppliesTo,
		&i.ReadCapability,
		&i.WriteCapability,
		&i.DisplayOrder,
		&i.DisplayGroup,
		&i.Status,
		&i.DeprecatedReplacementID,
		&i.OriginServerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedByUserRef,
		&i.UpdatedByUserRef,
		&i.SubjectKind,
		&i.ExtractionSource,
		&i.ExtractionMode,
		&i.DefaultValue,
		&i.OpenVocabulary,
		&i.MirrorsColumn,
		&i.ShowOnCard,
		&i.ShowInAdvancedSearch,
		&i.ShowOnUpload,
		&i.EditTab,
		&i.ReadOnly,
		&i.RegexpFilter,
	)
	return i, err
}

const upsertAssetFieldValue = `-- name: UpsertAssetFieldValue :one
INSERT INTO asset_field_value (
    asset_id, field_id,
    value_text, value_num, value_date, value_options, value_ref,
    set_by, set_at, set_by_user_ref
) VALUES (
    $1, $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    NOW(),
    $9
)
ON CONFLICT (asset_id, field_id) DO UPDATE SET
    value_text      = EXCLUDED.value_text,
    value_num       = EXCLUDED.value_num,
    value_date      = EXCLUDED.value_date,
    value_options   = EXCLUDED.value_options,
    value_ref       = EXCLUDED.value_ref,
    set_by          = EXCLUDED.set_by,
    set_at          = NOW(),
    set_by_user_ref = EXCLUDED.set_by_user_ref
RETURNING asset_id, field_id, value_text, value_num, value_date,
          value_options, value_ref, set_by, set_at, set_by_user_ref
`

type UpsertAssetFieldValueParams struct {
	AssetID      pgtype.UUID
	FieldID      pgtype.UUID
	ValueText    *string
	ValueNum     *float64
	ValueDate    pgtype.Timestamptz
	ValueOptions []string
	ValueRef     pgtype.UUID
	SetBy        string
	SetByUserRef *int64
}

// INSERT-or-UPDATE. Exactly one of the value_* columns is populated
// per field type; the handler clears the others.
func (q *Queries) UpsertAssetFieldValue(ctx context.Context, arg UpsertAssetFieldValueParams) (AssetFieldValue, error) {
	row := q.db.QueryRow(ctx, upsertAssetFieldValue,
		arg.AssetID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueNum,
		arg.ValueDate,
		arg.ValueOptions,
		arg.ValueRef,
		arg.SetBy,
		arg.SetByUserRef,
	)
	var i AssetFieldValue
	err := row.Scan(
		&i.AssetID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueNum,
		&i.ValueDate,
		&i.ValueOptions,
		&i.ValueRef,
		&i.SetBy,
		&i.SetAt,
		&i.SetByUserRef,
	)
	return i, err
}

const upsertCollectionFieldValue = `-- name: UpsertCollectionFieldValue :one
INSERT INTO collection_field_value (
    collection_id, field_id,
    value_text, value_num, value_date, value_options, value_ref,
    set_by, set_at, set_by_user_ref
) VALUES (
    $1,  $2,
    $3,    $4,
    $5,    $6,
    $7,
    $8,         NOW(),
    $9
)
ON CONFLICT (collection_id, field_id) DO UPDATE SET
    value_text      = EXCLUDED.value_text,
    value_num       = EXCLUDED.value_num,
    value_date      = EXCLUDED.value_date,
    value_options   = EXCLUDED.value_options,
    value_ref       = EXCLUDED.value_ref,
    set_by          = EXCLUDED.set_by,
    set_at          = NOW(),
    set_by_user_ref = EXCLUDED.set_by_user_ref
RETURNING collection_id, field_id, value_text, value_num, value_date,
          value_options, value_ref, set_by, set_at, set_by_user_ref
`

type UpsertCollectionFieldValueParams struct {
	CollectionID pgtype.UUID
	FieldID      pgtype.UUID
	ValueText    *string
	ValueNum     *float64
	ValueDate    pgtype.Timestamptz
	ValueOptions []string
	ValueRef     pgtype.UUID
	SetBy        string
	SetByUserRef *int64
}

// Cache invalidation MUST follow at handler layer.
// History row MUST follow in the same transaction.
func (q *Queries) UpsertCollectionFieldValue(ctx context.Context, arg UpsertCollectionFieldValueParams) (CollectionFieldValue, error) {
	row := q.db.QueryRow(ctx, upsertCollectionFieldValue,
		arg.CollectionID,
		arg.FieldID,
		arg.ValueText,
		arg.ValueNum,
		arg.ValueDate,
		arg.ValueOptions,
		arg.ValueRef,
		arg.SetBy,
		arg.SetByUserRef,
	)
	var i CollectionFieldValue
	err := row.Scan(
		&i.CollectionID,
		&i.FieldID,
		&i.ValueText,
		&i.ValueNum,
		&i.ValueDate,
		&i.ValueOptions,
		&i.ValueRef,
		&i.SetBy,
		&i.SetAt,
		&i.SetByUserRef,
	)
	return i, err
}

const upsertFieldDefaultOverride = `-- name: UpsertFieldDefaultOverride :one
INSERT INTO field_default_override (field_id, team_id, default_value, updated_by_user_ref)
VALUES ($1, $2, $3, $4)
ON CONFLICT (field_id, team_id) DO UPDATE
   SET default_value = EXCLUDED.default_value,
       updated_at = NOW(),
       updated_by_user_ref = EXCLUDED.updated_by_user_ref
RETURNING field_id, team_id, default_value, created_at, updated_at, updated_by_user_ref
`

type UpsertFieldDefaultOverrideParams struct {
	FieldID          pgtype.UUID
	TeamID           pgtype.UUID
	DefaultValue     []byte
	UpdatedByUserRef *int64
}

func (q *Queries) UpsertFieldDefaultOverride(ctx context.Context, arg UpsertFieldDefaultOverrideParams) (FieldDefaultOverride, error) {
	row := q.db.QueryRow(ctx, upsertFieldDefaultOverride,
		arg.FieldID,
		arg.TeamID,
		arg.DefaultValue,
		arg.UpdatedByUserRef,
	)
	var i FieldDefaultOverride
	err := row.Scan(
		&i.FieldID,
		&i.TeamID,
		&i.DefaultValue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByUserRef,
	)
	return i, err
}
