// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package audit

import (
	"context"
	"net/netip"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (
    event_type,
    subject_user_ref,
    actor_user_ref,
    ip,
    user_agent,
    metadata
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditEventParams struct {
	EventType      string
	SubjectUserRef *int64
	ActorUserRef   *int64
	Ip             *netip.Addr
	UserAgent      *string
	Metadata       []byte
}

// Append-only write of a single audit event. Callers build the event
// through audit.Recorder, which knows the per-event-type metadata shape.
func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.EventType,
		arg.SubjectUserRef,
		arg.ActorUserRef,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	return err
}

const recentAuditEventsForUser = `-- name: RecentAuditEventsForUser :many
SELECT id,
       event_type,
       occurred_at,
       subject_user_ref,
       actor_user_ref,
       ip,
       user_agent,
       metadata
FROM audit_events
WHERE subject_user_ref = $1
ORDER BY occurred_at DESC
LIMIT $2
`

type RecentAuditEventsForUserParams struct {
	SubjectUserRef *int64
	Limit          int32
}

// Powers "your recent activity" surfaces. The partial index on
// (subject_user_ref, occurred_at DESC) keeps this fast.
func (q *Queries) RecentAuditEventsForUser(ctx context.Context, arg RecentAuditEventsForUserParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, recentAuditEventsForUser, arg.SubjectUserRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.OccurredAt,
			&i.SubjectUserRef,
			&i.ActorUserRef,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
