// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Kenneth Blossom

package ai

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
)

// Bridge defines the contract between AI workflows and the rest of
// the artist-alley domain. AI handlers depend only on these
// interfaces; concrete implementations live in
// app/internal/assets/ (TagWriter today; CaptionWriter when the
// caption schema lands), app/internal/subtitles/ (TranscriptWriter
// when 1.14.C ships), and app/internal/ai/embeddings/ (EmbeddingWriter
// when 1.14.B ships).
//
// Per ADR pattern: consumer-defines-interface. The bridge interfaces
// live in this file so any AI handler (router callsites, job
// handlers) can grep for them in one place; concrete implementations
// satisfy them in their own packages.
//
// # Why one file
//
// All five interfaces in bridge.go (one file) so a future bridge
// consumer can grep for "what does AI need from the rest of the
// app" in one shot. The split between Reader (AssetLookup) and the
// four Writers is the natural boundary; each Writer covers one AI
// concern and corresponds to one job handler.
//
// # Stub policy
//
// EmbeddingWriter, TranscriptWriter, and CaptionWriter ship as
// stubs in this PR (see stub_implementations.go). The interfaces
// are declared NOW so the AI package surface doesn't drift across
// 1.14.B / 1.14.C / the caption-schema follow-up. When each
// concrete implementation lands, the boot wire swaps the stub for
// the real impl — single line change per phase.

// ---------------------------------------------------------------------------
// Sentinel errors
// ---------------------------------------------------------------------------

var (
	// ErrAssetNotFound is returned by AssetLookup.GetAssetForAI when
	// the requested asset doesn't exist. Job handlers should map
	// this to a terminal job error (no retry — the asset isn't
	// coming back into existence).
	ErrAssetNotFound = errors.New("ai: asset not found")

	// ErrAssetKindNotSupported is returned when an AI operation is
	// invoked against an asset kind that doesn't support it
	// (e.g. transcription against an image). Job handlers should map
	// this to terminal (operator changed asset type post-enqueue or
	// fan-out emitted a job for an inappropriate kind).
	ErrAssetKindNotSupported = errors.New("ai: asset kind doesn't support this AI operation")

	// ErrNotImplementedYet is returned by stub bridge implementations
	// until the providing phase ships its concrete impl. Distinct
	// from ErrAssetKindNotSupported so audit + monitoring can tell
	// the two apart in dashboards.
	ErrNotImplementedYet = errors.New("ai: bridge implementation not yet shipped")
)

// ---------------------------------------------------------------------------
// AssetLookup — read side
// ---------------------------------------------------------------------------

// AssetLookup is the read-side bridge. Returns the minimal
// projection (AssetForAI) the AI handlers need; the handlers never
// touch the live asset row.
type AssetLookup interface {
	GetAssetForAI(ctx context.Context, id uuid.UUID) (AssetForAI, error)
}

// AssetForAI is the typed projection AI handlers consume. Value
// type — the handler can't mutate state via the lookup. Per-kind
// fields populate as documented:
//
//   - image:  PreviewURL + OriginalURL → source image renditions
//   - video:  PreviewURL → first-frame; OriginalURL → source video
//   - audio:  PreviewURL → cover art (if any); OriginalURL → audio file
//   - other:  both may be empty; AI handler should return
//     ErrAssetKindNotSupported
//
// ExistingTags carries the asset's current tags + their source so
// the AI handler can include them as prompt context (don't re-
// suggest operator-set tags). Empty slice when no tags exist.
type AssetForAI struct {
	ID           uuid.UUID
	MimeType     string
	Sensitivity  SensitivityTier
	OwningTeamID *uuid.UUID
	PreviewURL   string
	OriginalURL  string
	Title        string
	ExistingTags []TagInput
	ContentHash  string // for embedding cache key + idempotency
}

// TagInput is one existing tag passed as prompt context. Source
// tells the AI what to do — manual tags should NOT be re-suggested
// (they're operator decisions); existing AI tags can be refreshed.
type TagInput struct {
	Value  string
	Source TagSource
}

// TagSource is the typed enum matching the asset_tag.source CHECK
// constraint from migration 00010.
type TagSource string

const (
	// TagSourceManual — operator wrote this tag in the UI. Sacred:
	// AI re-runs never overwrite or remove these.
	TagSourceManual TagSource = "manual"

	// TagSourceAI — generated by an AI tag job. Replaceable by
	// later AI runs; coexists with manual tags on the same asset.
	TagSourceAI TagSource = "ai"

	// TagSourceImport — generated by a bulk import (CSV / EXIF /
	// upstream system). Treated like manual for merge purposes —
	// AI doesn't overwrite import tags.
	TagSourceImport TagSource = "import"
)

// Valid reports whether s is one of the three known values.
func (s TagSource) Valid() bool {
	switch s {
	case TagSourceManual, TagSourceAI, TagSourceImport:
		return true
	}
	return false
}

// ---------------------------------------------------------------------------
// TagWriter — write side for tags
// ---------------------------------------------------------------------------

// TagWriter persists AI-generated tags to an asset.
//
// # Merge semantics (preserve_manual)
//
//   - Tags with Source=TagSourceManual are PRESERVED unchanged.
//   - Tags with Source=TagSourceImport are PRESERVED unchanged.
//   - Tags with Source=TagSourceAI are REPLACED — every existing
//     ai-source row for the asset is deleted, then the new ones
//     inserted in the same transaction.
//
// This protects operator-set data: even an aggressive AI re-run
// can't clobber tags the operator manually applied. The two sets
// coexist on the asset; UI rendering decides how to layer them.
//
// Implementations MUST wrap the delete + insert pair in a single
// transaction so a partial write can't leave the asset with no
// tags during the gap.
type TagWriter interface {
	SetAITagsForAsset(ctx context.Context, assetID uuid.UUID, tags []TagOutput, prov AIProvenance) error
}

// TagOutput is one AI-produced tag. Confidence is in [0,1] when
// the provider supplies one; zero when the provider doesn't
// (the UI threshold filter then shows the tag unconditionally).
type TagOutput struct {
	Value      string
	Confidence float64
}

// ---------------------------------------------------------------------------
// CaptionWriter — write side for captions
// ---------------------------------------------------------------------------

// CaptionWriter persists an AI-generated caption to an asset.
//
// # Replace semantics
//
// Captions are single-valued. The AI write overwrites the existing
// caption regardless of its source — including a manual one. The
// caption_source column (added by a future migration alongside the
// caption column itself) records whether the current value is AI
// or operator-set so the UI can warn operators about overwrite.
//
// # Status in 1.14.A-bridge
//
// The caption column on the assets table does not exist yet (audit-
// first finding). The stub implementation registered at boot
// returns ErrNotImplementedYet; the ai.caption job handler maps
// that to TerminalError so the job doesn't loop. A follow-up PR
// will add the caption schema + the concrete writer.
type CaptionWriter interface {
	SetAICaptionForAsset(ctx context.Context, assetID uuid.UUID, caption string, prov AIProvenance) error
}

// ---------------------------------------------------------------------------
// EmbeddingWriter — write side for vectors (1.14.B)
// ---------------------------------------------------------------------------

// EmbeddingWriter persists a CLIP-style embedding to the
// asset_embedding table. Stub in 1.14.A-bridge; concrete impl
// lands in 1.14.B alongside the pgvector schema and HNSW index.
//
// Key (AssetID, Provider, Model, Modality) is idempotent — re-
// running embedding for the same key replaces the existing vector.
type EmbeddingWriter interface {
	UpsertAssetEmbedding(ctx context.Context, in EmbeddingInput) error
}

// EmbeddingInput is the typed payload the writer consumes.
type EmbeddingInput struct {
	AssetID     uuid.UUID
	Provider    string
	Model       string
	Modality    string // 'image' | 'text' | 'multimodal'
	Vector      []float32
	ContentHash string // cache-validation against AssetForAI.ContentHash
}

// ---------------------------------------------------------------------------
// TranscriptWriter — write side for transcripts (1.14.C)
// ---------------------------------------------------------------------------

// TranscriptWriter persists an AI-generated transcript as a WebVTT
// subtitle track on the asset. Stub in 1.14.A-bridge; concrete
// impl in 1.14.C delegates to subtitles.Handler.UpsertSubtitleTrack
// with source_format='whisper'.
type TranscriptWriter interface {
	SetAITranscriptForAsset(ctx context.Context, in TranscriptInput) error
}

// TranscriptInput is the typed payload.
type TranscriptInput struct {
	AssetID    uuid.UUID
	Language   string // detected or operator-supplied (RFC 5646)
	VTTContent []byte // already marshalled WebVTT
	Confidence float64
	Model      string
	Provider   string
}

// ---------------------------------------------------------------------------
// AIProvenance — shared across all writes
// ---------------------------------------------------------------------------

// AIProvenance accompanies every AI write. Flows into:
//
//  1. The destination row's per-source provenance columns
//     (e.g. asset_tag.created_by_provider).
//  2. The ai_provider_call audit table (the JobID links the
//     write back to the inference call that produced it).
//
// JobID is nil when the write originates from a direct admin
// action (the "regenerate tags for this asset" button) rather than
// the queued fanout. Audit dashboards distinguish job-emitted
// writes from admin-triggered ones via this field.
type AIProvenance struct {
	Provider      string
	Model         string
	PromptVersion string
	JobID         *uuid.UUID
	TriggeredAt   time.Time
}

// ---------------------------------------------------------------------------
// Bridge — convenience aggregator
// ---------------------------------------------------------------------------

// Bridge is the optional convenience grouping that boot wiring
// passes to handler constructors. Each field is the bridge
// interface; consumers can take individual interfaces if they
// prefer (testing patterns vary).
//
// Wiring:
//
//	bridge := ai.Bridge{
//	    Lookup:           assetsHandler,                // concrete
//	    TagWriter:        assetsHandler,                // concrete
//	    CaptionWriter:    ai.NewStubCaptionWriter(),    // stub until follow-up
//	    EmbeddingWriter:  ai.NewStubEmbeddingWriter(),  // stub until 1.14.B
//	    TranscriptWriter: ai.NewStubTranscriptWriter(), // stub until 1.14.C
//	}
type Bridge struct {
	Lookup           AssetLookup
	TagWriter        TagWriter
	CaptionWriter    CaptionWriter
	EmbeddingWriter  EmbeddingWriter
	TranscriptWriter TranscriptWriter
}
