// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package peer

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendPeerNote = `-- name: AppendPeerNote :one
UPDATE federation_peers
SET notes      = CASE WHEN notes = '' THEN $2 ELSE notes || E'\n' || $2 END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, instance_url, display_name, instance_public_key,
          trust_tier, encryption_policy, enabled, status,
          handshake_at, handshake_by_user_ref, last_seen_at,
          notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
`

type AppendPeerNoteParams struct {
	ID    pgtype.UUID
	Notes string
}

// Internal: append a timestamped line to the notes column so
// the admin UI surfaces transient handshake failures (offer POST
// timed out, peer 5xx, etc.). $2 is the pre-stamped line.
func (q *Queries) AppendPeerNote(ctx context.Context, arg AppendPeerNoteParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, appendPeerNote, arg.ID, arg.Notes)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.Status,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.ShareInVisibleList,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesNegotiatedAt,
	)
	return i, err
}

const completeOutboundHandshake = `-- name: CompleteOutboundHandshake :one
UPDATE federation_peers
SET instance_public_key = $2,
    status              = 'connected',
    updated_at          = NOW()
WHERE id = $1 AND status = 'pending_outbound'
RETURNING id, instance_url, display_name, instance_public_key,
          trust_tier, encryption_policy, enabled, status,
          handshake_at, handshake_by_user_ref, last_seen_at,
          notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
`

type CompleteOutboundHandshakeParams struct {
	ID                pgtype.UUID
	InstancePublicKey string
}

// Atomically replaces the pending_outbound placeholder pubkey
// with the peer's real key (delivered in the confirm envelope)
// + flips status to connected. The atomic write is important —
// a separate UPDATE-pubkey-then-UPDATE-status sequence could
// leave us with the new key but still pending_outbound on a
// mid-flight crash.
func (q *Queries) CompleteOutboundHandshake(ctx context.Context, arg CompleteOutboundHandshakeParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, completeOutboundHandshake, arg.ID, arg.InstancePublicKey)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.Status,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.ShareInVisibleList,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesNegotiatedAt,
	)
	return i, err
}

const deletePeer = `-- name: DeletePeer :exec
DELETE FROM federation_peers WHERE id = $1
`

// Defederation. Per ADR 0043 §"Trust model" the receiving side
// of this should cascade-delete federation_shares rows targeting
// the peer (FK ON DELETE CASCADE on that table, Phase 1.22.C);
// the audit emission + final aa:Unshare delivery to the peer is
// the dispatcher's job (Phase 1.22.D).
func (q *Queries) DeletePeer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePeer, id)
	return err
}

const getPeerByID = `-- name: GetPeerByID :one
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled, status,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
FROM federation_peers
WHERE id = $1
`

// Admin detail view + the auth path that resolves "which peer
// is this inbound activity from?" once we have a UUID.
func (q *Queries) GetPeerByID(ctx context.Context, id pgtype.UUID) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, getPeerByID, id)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.Status,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.ShareInVisibleList,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesNegotiatedAt,
	)
	return i, err
}

const getPeerByInstanceURL = `-- name: GetPeerByInstanceURL :one
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled, status,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
FROM federation_peers
WHERE instance_url = $1
`

// Hot read on the inbound federation path: every signed request
// from a peer arrives addressed-by-URL; we look up the row to
// (a) authenticate the request via instance_public_key, (b) check
// the enabled flag + status, (c) update last_seen_at. Cache-
// fronted at the package layer.
func (q *Queries) GetPeerByInstanceURL(ctx context.Context, instanceUrl string) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, getPeerByInstanceURL, instanceUrl)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.Status,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.ShareInVisibleList,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesNegotiatedAt,
	)
	return i, err
}

const insertPeer = `-- name: InsertPeer :one
INSERT INTO federation_peers (
    instance_url,
    display_name,
    instance_public_key,
    trust_tier,
    encryption_policy,
    enabled,
    status,
    handshake_by_user_ref,
    notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, instance_url, display_name, instance_public_key,
          trust_tier, encryption_policy, enabled, status,
          handshake_at, handshake_by_user_ref, last_seen_at,
          notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
`

type InsertPeerParams struct {
	InstanceUrl        string
	DisplayName        string
	InstancePublicKey  string
	TrustTier          string
	EncryptionPolicy   string
	Enabled            bool
	Status             string
	HandshakeByUserRef int64
	Notes              string
}

// Manual admin entry (1.22.B-a) + handshake landing (1.22.B-b)
// both insert here. UNIQUE on instance_url forces the operator
// to think before re-pairing — the upsert variant
// (UpdatePeerAfterHandshake) handles re-keying explicitly.
//
// Status param defaults to 'connected' (manual entry) but the
// handshake flow passes 'pending_outbound' or 'pending_inbound'
// per v1.md §11 state machine.
func (q *Queries) InsertPeer(ctx context.Context, arg InsertPeerParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, insertPeer,
		arg.InstanceUrl,
		arg.DisplayName,
		arg.InstancePublicKey,
		arg.TrustTier,
		arg.EncryptionPolicy,
		arg.Enabled,
		arg.Status,
		arg.HandshakeByUserRef,
		arg.Notes,
	)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.Status,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.ShareInVisibleList,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesNegotiatedAt,
	)
	return i, err
}

const listEnabledPeers = `-- name: ListEnabledPeers :many
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled, status,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
FROM federation_peers
WHERE enabled = TRUE AND status = 'connected'
ORDER BY instance_url
`

// Hot read on the outbound delivery path: the federation outbox
// worker (Phase 1.22.D) iterates this set to know who can
// receive activities. Partial index federation_peers_enabled_idx
// (revised in migration 00052 to gate on status='connected') means
// this is sub-ms even with hundreds of peers — and pending
// peers are excluded so we never deliver to a half-paired peer.
func (q *Queries) ListEnabledPeers(ctx context.Context) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listEnabledPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationPeer
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.InstanceUrl,
			&i.DisplayName,
			&i.InstancePublicKey,
			&i.TrustTier,
			&i.EncryptionPolicy,
			&i.Enabled,
			&i.Status,
			&i.HandshakeAt,
			&i.HandshakeByUserRef,
			&i.LastSeenAt,
			&i.Notes,
			&i.ShareInVisibleList,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Capabilities,
			&i.CapabilitiesNegotiatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeers = `-- name: ListPeers :many
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled, status,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
FROM federation_peers
ORDER BY handshake_at DESC, id DESC
LIMIT $1
`

// Admin audit/list surface. All peers, newest-handshake-first.
// Bounded LIMIT — admins with thousands of peers would page; v1
// expects dozens at most.
func (q *Queries) ListPeers(ctx context.Context, limit int32) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listPeers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationPeer
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.InstanceUrl,
			&i.DisplayName,
			&i.InstancePublicKey,
			&i.TrustTier,
			&i.EncryptionPolicy,
			&i.Enabled,
			&i.Status,
			&i.HandshakeAt,
			&i.HandshakeByUserRef,
			&i.LastSeenAt,
			&i.Notes,
			&i.ShareInVisibleList,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Capabilities,
			&i.CapabilitiesNegotiatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeersMissingCapabilities = `-- name: ListPeersMissingCapabilities :many
SELECT id, instance_url, display_name
  FROM federation_peers
 WHERE capabilities_negotiated_at IS NULL
 ORDER BY instance_url
`

type ListPeersMissingCapabilitiesRow struct {
	ID          pgtype.UUID
	InstanceUrl string
	DisplayName string
}

// Operator observability: peers paired before I-d that haven't
// been re-negotiated. Surfaced on the admin federation page so
// the operator can trigger re-pairing. Backed by the
// federation_peers_unnegotiated_idx partial index from migration
// 00009 so this query stays cheap regardless of total peer count.
func (q *Queries) ListPeersMissingCapabilities(ctx context.Context) ([]ListPeersMissingCapabilitiesRow, error) {
	rows, err := q.db.Query(ctx, listPeersMissingCapabilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeersMissingCapabilitiesRow
	for rows.Next() {
		var i ListPeersMissingCapabilitiesRow
		if err := rows.Scan(&i.ID, &i.InstanceUrl, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInboundPeers = `-- name: ListPendingInboundPeers :many
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled, status,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
FROM federation_peers
WHERE status = 'pending_inbound'
ORDER BY handshake_at DESC, id DESC
`

// Admin "requests awaiting your approval" feed (1.22.B-b).
// Backed by the federation_peers_pending_inbound_idx partial
// index so this stays cheap regardless of total table size.
func (q *Queries) ListPendingInboundPeers(ctx context.Context) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listPendingInboundPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationPeer
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.InstanceUrl,
			&i.DisplayName,
			&i.InstancePublicKey,
			&i.TrustTier,
			&i.EncryptionPolicy,
			&i.Enabled,
			&i.Status,
			&i.HandshakeAt,
			&i.HandshakeByUserRef,
			&i.LastSeenAt,
			&i.Notes,
			&i.ShareInVisibleList,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Capabilities,
			&i.CapabilitiesNegotiatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisiblePeers = `-- name: ListVisiblePeers :many
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled, status,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
FROM federation_peers
WHERE enabled = TRUE AND status = 'connected' AND share_in_visible_list = TRUE
ORDER BY instance_url
`

// The set returned by GET /federation/peers/visible — peers we've
// opted to expose to anyone who asks. Backed by the partial index
// federation_peers_visible_idx (enabled AND status=connected AND
// share_in_visible_list).
func (q *Queries) ListVisiblePeers(ctx context.Context) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listVisiblePeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationPeer
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.InstanceUrl,
			&i.DisplayName,
			&i.InstancePublicKey,
			&i.TrustTier,
			&i.EncryptionPolicy,
			&i.Enabled,
			&i.Status,
			&i.HandshakeAt,
			&i.HandshakeByUserRef,
			&i.LastSeenAt,
			&i.Notes,
			&i.ShareInVisibleList,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Capabilities,
			&i.CapabilitiesNegotiatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPeerCapabilities = `-- name: SetPeerCapabilities :exec

UPDATE federation_peers
   SET capabilities = $2,
       capabilities_negotiated_at = NOW()
 WHERE id = $1
`

type SetPeerCapabilitiesParams struct {
	ID           pgtype.UUID
	Capabilities []byte
}

// --- Phase 1.22.I-d — capability negotiation ------------------------
// Writes the bilateral intersection produced by the handshake
// engine. The intersection — NOT either side's raw advertised set
// — is what we record, so the I-e/I-g dispatch gates can rely on
// "this peer supports X" without re-doing the intersection at
// every check site. capabilities_negotiated_at moves to NOW() so
// ListPeersMissingCapabilities stops surfacing this peer.
func (q *Queries) SetPeerCapabilities(ctx context.Context, arg SetPeerCapabilitiesParams) error {
	_, err := q.db.Exec(ctx, setPeerCapabilities, arg.ID, arg.Capabilities)
	return err
}

const setPeerStatus = `-- name: SetPeerStatus :one
UPDATE federation_peers
SET status     = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, instance_url, display_name, instance_public_key,
          trust_tier, encryption_policy, enabled, status,
          handshake_at, handshake_by_user_ref, last_seen_at,
          notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
`

type SetPeerStatusParams struct {
	ID     pgtype.UUID
	Status string
}

// Internal handshake state transition: pending_outbound →
// connected, pending_inbound → connected, etc. Bypasses
// UpdatePeer because the public PATCH endpoint doesn't expose
// status changes — those are protocol-driven, not admin-driven.
func (q *Queries) SetPeerStatus(ctx context.Context, arg SetPeerStatusParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, setPeerStatus, arg.ID, arg.Status)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.Status,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.ShareInVisibleList,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesNegotiatedAt,
	)
	return i, err
}

const touchPeerLastSeen = `-- name: TouchPeerLastSeen :exec
UPDATE federation_peers
SET last_seen_at = NOW()
WHERE instance_url = $1
`

// Phase 1.22.D inbox path: best-effort bump of last_seen_at when
// a valid signed request arrives. No row returned; failure
// (e.g. peer disabled between auth + this write) is logged-and-
// ignored.
func (q *Queries) TouchPeerLastSeen(ctx context.Context, instanceUrl string) error {
	_, err := q.db.Exec(ctx, touchPeerLastSeen, instanceUrl)
	return err
}

const updatePeer = `-- name: UpdatePeer :one
UPDATE federation_peers
SET display_name          = COALESCE($2::TEXT,       display_name),
    trust_tier            = COALESCE($3::TEXT,         trust_tier),
    encryption_policy     = COALESCE($4::TEXT,  encryption_policy),
    enabled               = COALESCE($5::BOOLEAN,          enabled),
    notes                 = COALESCE($6::TEXT,               notes),
    share_in_visible_list = COALESCE($7::BOOLEAN, share_in_visible_list),
    updated_at            = NOW()
WHERE id = $1
RETURNING id, instance_url, display_name, instance_public_key,
          trust_tier, encryption_policy, enabled, status,
          handshake_at, handshake_by_user_ref, last_seen_at,
          notes, share_in_visible_list, created_at, updated_at, capabilities, capabilities_negotiated_at
`

type UpdatePeerParams struct {
	ID                 pgtype.UUID
	DisplayName        *string
	TrustTier          *string
	EncryptionPolicy   *string
	Enabled            *bool
	Notes              *string
	ShareInVisibleList *bool
}

// Admin edit: change display_name / trust_tier / encryption_policy
// / enabled / notes. Does NOT change instance_url or
// instance_public_key — those require defederate+repair (the
// public_key change in particular signals re-handshake).
func (q *Queries) UpdatePeer(ctx context.Context, arg UpdatePeerParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, updatePeer,
		arg.ID,
		arg.DisplayName,
		arg.TrustTier,
		arg.EncryptionPolicy,
		arg.Enabled,
		arg.Notes,
		arg.ShareInVisibleList,
	)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.Status,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.ShareInVisibleList,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Capabilities,
		&i.CapabilitiesNegotiatedAt,
	)
	return i, err
}
