// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package peer

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePeer = `-- name: DeletePeer :exec
DELETE FROM federation_peers WHERE id = $1
`

// Defederation. Per ADR 0043 §"Trust model" the receiving side
// of this should cascade-delete federation_shares rows targeting
// the peer (FK ON DELETE CASCADE on that table, Phase 1.22.C);
// the audit emission + final aa:Unshare delivery to the peer is
// the dispatcher's job (Phase 1.22.D).
func (q *Queries) DeletePeer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePeer, id)
	return err
}

const getPeerByID = `-- name: GetPeerByID :one
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, created_at, updated_at
FROM federation_peers
WHERE id = $1
`

// Admin detail view + the auth path that resolves "which peer
// is this inbound activity from?" once we have a UUID.
func (q *Queries) GetPeerByID(ctx context.Context, id pgtype.UUID) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, getPeerByID, id)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPeerByInstanceURL = `-- name: GetPeerByInstanceURL :one
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, created_at, updated_at
FROM federation_peers
WHERE instance_url = $1
`

// Hot read on the inbound federation path: every signed request
// from a peer arrives addressed-by-URL; we look up the row to
// (a) authenticate the request via instance_public_key, (b) check
// the enabled flag, (c) update last_seen_at. Cache-fronted at
// the package layer.
func (q *Queries) GetPeerByInstanceURL(ctx context.Context, instanceUrl string) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, getPeerByInstanceURL, instanceUrl)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPeer = `-- name: InsertPeer :one
INSERT INTO federation_peers (
    instance_url,
    display_name,
    instance_public_key,
    trust_tier,
    encryption_policy,
    enabled,
    handshake_by_user_ref,
    notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, instance_url, display_name, instance_public_key,
          trust_tier, encryption_policy, enabled,
          handshake_at, handshake_by_user_ref, last_seen_at,
          notes, created_at, updated_at
`

type InsertPeerParams struct {
	InstanceUrl        string
	DisplayName        string
	InstancePublicKey  string
	TrustTier          string
	EncryptionPolicy   string
	Enabled            bool
	HandshakeByUserRef int64
	Notes              string
}

// Manual admin entry (1.22.B-a) + handshake landing (1.22.B-b)
// both insert here. UNIQUE on instance_url forces the operator
// to think before re-pairing — the upsert variant
// (UpdatePeerAfterHandshake) handles re-keying explicitly.
func (q *Queries) InsertPeer(ctx context.Context, arg InsertPeerParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, insertPeer,
		arg.InstanceUrl,
		arg.DisplayName,
		arg.InstancePublicKey,
		arg.TrustTier,
		arg.EncryptionPolicy,
		arg.Enabled,
		arg.HandshakeByUserRef,
		arg.Notes,
	)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPeers = `-- name: ListEnabledPeers :many
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, created_at, updated_at
FROM federation_peers
WHERE enabled = TRUE
ORDER BY instance_url
`

// Hot read on the outbound delivery path: the federation outbox
// worker (Phase 1.22.D) iterates this set to know who can
// receive activities. Partial index federation_peers_enabled_idx
// means this is sub-ms even with hundreds of peers.
func (q *Queries) ListEnabledPeers(ctx context.Context) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listEnabledPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationPeer
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.InstanceUrl,
			&i.DisplayName,
			&i.InstancePublicKey,
			&i.TrustTier,
			&i.EncryptionPolicy,
			&i.Enabled,
			&i.HandshakeAt,
			&i.HandshakeByUserRef,
			&i.LastSeenAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeers = `-- name: ListPeers :many
SELECT id, instance_url, display_name, instance_public_key,
       trust_tier, encryption_policy, enabled,
       handshake_at, handshake_by_user_ref, last_seen_at,
       notes, created_at, updated_at
FROM federation_peers
ORDER BY handshake_at DESC, id DESC
LIMIT $1
`

// Admin audit/list surface. All peers, newest-handshake-first.
// Bounded LIMIT — admins with thousands of peers would page; v1
// expects dozens at most.
func (q *Queries) ListPeers(ctx context.Context, limit int32) ([]FederationPeer, error) {
	rows, err := q.db.Query(ctx, listPeers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationPeer
	for rows.Next() {
		var i FederationPeer
		if err := rows.Scan(
			&i.ID,
			&i.InstanceUrl,
			&i.DisplayName,
			&i.InstancePublicKey,
			&i.TrustTier,
			&i.EncryptionPolicy,
			&i.Enabled,
			&i.HandshakeAt,
			&i.HandshakeByUserRef,
			&i.LastSeenAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchPeerLastSeen = `-- name: TouchPeerLastSeen :exec
UPDATE federation_peers
SET last_seen_at = NOW()
WHERE instance_url = $1
`

// Phase 1.22.D inbox path: best-effort bump of last_seen_at when
// a valid signed request arrives. No row returned; failure
// (e.g. peer disabled between auth + this write) is logged-and-
// ignored.
func (q *Queries) TouchPeerLastSeen(ctx context.Context, instanceUrl string) error {
	_, err := q.db.Exec(ctx, touchPeerLastSeen, instanceUrl)
	return err
}

const updatePeer = `-- name: UpdatePeer :one
UPDATE federation_peers
SET display_name     = COALESCE($2::TEXT,     display_name),
    trust_tier       = COALESCE($3::TEXT,       trust_tier),
    encryption_policy = COALESCE($4::TEXT, encryption_policy),
    enabled          = COALESCE($5::BOOLEAN,        enabled),
    notes            = COALESCE($6::TEXT,             notes),
    updated_at       = NOW()
WHERE id = $1
RETURNING id, instance_url, display_name, instance_public_key,
          trust_tier, encryption_policy, enabled,
          handshake_at, handshake_by_user_ref, last_seen_at,
          notes, created_at, updated_at
`

type UpdatePeerParams struct {
	ID               pgtype.UUID
	DisplayName      *string
	TrustTier        *string
	EncryptionPolicy *string
	Enabled          *bool
	Notes            *string
}

// Admin edit: change display_name / trust_tier / encryption_policy
// / enabled / notes. Does NOT change instance_url or
// instance_public_key — those require defederate+repair (the
// public_key change in particular signals re-handshake).
func (q *Queries) UpdatePeer(ctx context.Context, arg UpdatePeerParams) (FederationPeer, error) {
	row := q.db.QueryRow(ctx, updatePeer,
		arg.ID,
		arg.DisplayName,
		arg.TrustTier,
		arg.EncryptionPolicy,
		arg.Enabled,
		arg.Notes,
	)
	var i FederationPeer
	err := row.Scan(
		&i.ID,
		&i.InstanceUrl,
		&i.DisplayName,
		&i.InstancePublicKey,
		&i.TrustTier,
		&i.EncryptionPolicy,
		&i.Enabled,
		&i.HandshakeAt,
		&i.HandshakeByUserRef,
		&i.LastSeenAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
