// Package comfyuimcp is the ComfyUI-via-MCP implementation of
// [aiedit.ImageEditProvider]. It does NOT speak to ComfyUI directly
// — the operator runs a thin Python bridge (see
// tools/comfyui-mcp-bridge/) that translates MCP tools/call
// invocations into ComfyUI workflow runs. From AA's perspective
// this is just another MCP server registered through Phase 1.53.A's
// admin UI, and the only thing the Go side cares about is the
// JSON-RPC contract the bridge exposes.
//
// # Locked contract (matches docs/operator/comfyui-mcp-bridge-setup.md)
//
// Bridge advertises an "img2img" tool via tools/list with input
// schema {prompt, source_image_url, denoise_strength, steps, seed}.
//
// Bridge's tools/call response carries an MCP-spec content array:
//
//	{
//	  "content": [
//	    {"type": "image", "data": "<base64-png>", "mimeType": "image/png"},
//	    {"type": "text",  "text": "{\"prompt\":\"...\",\"seed_used\":42,...}"}
//	  ]
//	}
//
// The provider decodes content[image] as the generated bytes and
// parses content[text].text as JSON metadata for the lineage row.
// Order within the array is irrelevant; the provider scans for the
// first matching type of each.
//
// # Why we wrap mcpdispatch, not the raw provider
//
// mcpdispatch.Dispatcher.Invoke runs the 6-step guard chain
// (capability → tool whitelist → privacy → budget → invoke → audit).
// Bypassing it would re-invent every gate.

package comfyuimcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"

	"github.com/mscrnt/artist-alley/app/internal/ai"
	mcpdispatch "github.com/mscrnt/artist-alley/app/internal/ai/mcp_dispatch"
	"github.com/mscrnt/artist-alley/app/internal/aiedit"
	"github.com/mscrnt/artist-alley/app/internal/auth"
)

// Name is the stable provider identifier recorded in audit rows.
const Name = "comfyuimcp"

// ToolImg2Img is the canonical tool name the bridge advertises.
// Operator-side this MUST match the per-server tool whitelist entry
// at /admin/ai/mcp-clients/{id}/tools — case-sensitive.
const ToolImg2Img = "img2img"

// Dispatcher is the narrow surface this provider needs from
// mcpdispatch.Dispatcher. *mcpdispatch.Dispatcher satisfies it;
// tests pass an in-memory stub.
type Dispatcher interface {
	Invoke(ctx context.Context, opts mcpdispatch.InvokeOpts) (json.RawMessage, error)
}

// Provider is the ComfyUI-via-MCP ImageEditProvider.
//
// Construction wires the dispatcher + the operator-configured server
// name. The provider re-reads neither across calls — operators who
// re-point at a different MCP server need a process restart (same
// shape as the rest of the AI provider registry in 1.14.A).
type Provider struct {
	disp       Dispatcher
	serverName string
}

// NewProvider builds the provider. serverName is the operator-set
// MCP registration name (e.g. "comfyui-lan"); when empty the
// provider returns aiedit.ErrServerNotConfigured from every op.
func NewProvider(disp Dispatcher, serverName string) *Provider {
	return &Provider{disp: disp, serverName: serverName}
}

// Name implements [aiedit.ImageEditProvider].
func (p *Provider) Name() string { return Name }

// Capabilities implements [aiedit.ImageEditProvider]. E-1 ships only
// Img2Img; E-2 flips the other four as their bridge sides ship.
func (p *Provider) Capabilities() aiedit.Capabilities {
	return aiedit.Capabilities{Img2Img: true}
}

// Img2Img dispatches the operator-whitelisted img2img tool against
// the configured MCP server, decodes the bridge response, and
// returns the typed result the caller writes to the lineage row +
// the storage layer.
func (p *Provider) Img2Img(ctx context.Context, req aiedit.Img2ImgRequest) (aiedit.Img2ImgResult, error) {
	if p.serverName == "" {
		return aiedit.Img2ImgResult{}, aiedit.ErrServerNotConfigured
	}

	args := map[string]any{
		"prompt":           req.Prompt,
		"source_image_url": req.SourceImageURL,
	}
	// Zero-value knobs let the bridge apply its default; only forward
	// non-zero values so operator-configured workflow defaults
	// (denoise_strength 0.7, steps 20) stay authoritative when the
	// caller didn't override.
	if req.DenoiseStrength > 0 {
		args["denoise_strength"] = req.DenoiseStrength
	}
	if req.Steps > 0 {
		args["steps"] = req.Steps
	}
	if req.Seed != 0 {
		args["seed"] = req.Seed
	}

	raw, err := p.disp.Invoke(ctx, mcpdispatch.InvokeOpts{
		ServerName:  p.serverName,
		Tool:        ToolImg2Img,
		Arguments:   args,
		Caller:      callerFromContext(ctx),
		Sensitivity: sensitivityFromContext(ctx),
		AssetID:     req.SourceAssetID,
	})
	if err != nil {
		return aiedit.Img2ImgResult{}, err
	}

	return decodeImg2ImgResponse(raw)
}

// InPaint — E-2.
func (p *Provider) InPaint(ctx context.Context, req aiedit.InPaintRequest) (aiedit.Img2ImgResult, error) {
	return aiedit.Img2ImgResult{}, aiedit.ErrUnsupportedOp
}

// OutPaint — E-2.
func (p *Provider) OutPaint(ctx context.Context, req aiedit.OutPaintRequest) (aiedit.Img2ImgResult, error) {
	return aiedit.Img2ImgResult{}, aiedit.ErrUnsupportedOp
}

// Variations — E-2.
func (p *Provider) Variations(ctx context.Context, req aiedit.VariationsRequest) (aiedit.VariationsResult, error) {
	return aiedit.VariationsResult{}, aiedit.ErrUnsupportedOp
}

// RemoveBackground — E-2.
func (p *Provider) RemoveBackground(ctx context.Context, req aiedit.RemoveBgRequest) (aiedit.Img2ImgResult, error) {
	return aiedit.Img2ImgResult{}, aiedit.ErrUnsupportedOp
}

// Compile-time assertions.
var _ aiedit.ImageEditProvider = (*Provider)(nil)

// ---------------------------------------------------------------------------
// Response decoding
// ---------------------------------------------------------------------------

// toolsCallResult mirrors the MCP-spec tools/call result envelope.
// We only deserialize the fields we need — extra keys (e.g. isError)
// are tolerated to forward-compat with bridge upgrades.
type toolsCallResult struct {
	Content []contentItem `json:"content"`
}

// contentItem is one entry in the content array. Type discriminates
// the payload shape: "image" carries base64 + mimeType; "text"
// carries text (JSON-encoded metadata in our contract).
type contentItem struct {
	Type     string `json:"type"`
	Text     string `json:"text,omitempty"`
	Data     string `json:"data,omitempty"`
	MimeType string `json:"mimeType,omitempty"`
}

// decodeImg2ImgResponse parses the bridge response. Returns
// [aiedit.ErrBridgeResponseMalformed] when the contract isn't
// satisfied; the job layer maps that to a transient retry because
// bridges sometimes ship upgrades mid-call and a single bad
// response shouldn't fail a job permanently.
func decodeImg2ImgResponse(raw json.RawMessage) (aiedit.Img2ImgResult, error) {
	var env toolsCallResult
	if err := json.Unmarshal(raw, &env); err != nil {
		return aiedit.Img2ImgResult{}, fmt.Errorf("%w: %v", aiedit.ErrBridgeResponseMalformed, err)
	}
	if len(env.Content) == 0 {
		return aiedit.Img2ImgResult{}, fmt.Errorf("%w: empty content array", aiedit.ErrBridgeResponseMalformed)
	}

	var (
		imageBytes []byte
		mimeType   string
		metaText   string
	)
	for _, item := range env.Content {
		switch item.Type {
		case "image":
			if imageBytes != nil {
				// Multiple images in one response not supported in
				// v1 — first wins; rest ignored. E-2 variations op
				// will introduce a separate code path for fan-out.
				continue
			}
			b, err := base64.StdEncoding.DecodeString(item.Data)
			if err != nil {
				return aiedit.Img2ImgResult{}, fmt.Errorf("%w: base64 decode: %v", aiedit.ErrBridgeResponseMalformed, err)
			}
			imageBytes = b
			mimeType = item.MimeType
			if mimeType == "" {
				mimeType = "image/png"
			}
		case "text":
			if metaText == "" {
				metaText = item.Text
			}
		}
	}
	if imageBytes == nil {
		return aiedit.Img2ImgResult{}, fmt.Errorf("%w: no image content part", aiedit.ErrBridgeResponseMalformed)
	}

	out := aiedit.Img2ImgResult{
		ImageBytes:  imageBytes,
		ContentType: mimeType,
	}

	// Metadata is best-effort — a bridge that omits it loses
	// reproducibility info but doesn't fail the call. The lineage
	// row still gets the typed fields the provider knows about.
	if metaText != "" {
		var meta map[string]any
		if err := json.Unmarshal([]byte(metaText), &meta); err == nil {
			out.GenerationMetadata = meta
			if v, ok := meta["seed_used"].(float64); ok {
				out.SeedUsed = int64(v)
			}
			if v, ok := meta["prompt"].(string); ok {
				out.PromptUsed = v
			}
			if v, ok := meta["model"].(string); ok {
				out.ModelUsed = v
			}
		}
	}

	return out, nil
}

// ---------------------------------------------------------------------------
// Context plumbing — caller identity + asset sensitivity ride the
// context so the provider doesn't need a wider request shape.
// ---------------------------------------------------------------------------

// callerCtxKey + sensitivityCtxKey are unexported so external
// callers can't accidentally collide; the handler sets them via
// WithCaller / WithSensitivity below.
type callerCtxKeyT struct{}
type sensitivityCtxKeyT struct{}

var callerCtxKey callerCtxKeyT
var sensitivityCtxKey sensitivityCtxKeyT

// WithCaller attaches the calling identity to ctx. The provider
// forwards it to [mcpdispatch.InvokeOpts.Caller] for the cap gate.
func WithCaller(ctx context.Context, id *auth.Identity) context.Context {
	return context.WithValue(ctx, callerCtxKey, id)
}

// WithSensitivity attaches the source asset's sensitivity tier so
// the dispatcher's privacy gate can clamp restricted/embargo bytes
// to local-only MCP servers.
func WithSensitivity(ctx context.Context, tier ai.SensitivityTier) context.Context {
	return context.WithValue(ctx, sensitivityCtxKey, tier)
}

func callerFromContext(ctx context.Context) *auth.Identity {
	v := ctx.Value(callerCtxKey)
	id, _ := v.(*auth.Identity)
	return id
}

func sensitivityFromContext(ctx context.Context) ai.SensitivityTier {
	v := ctx.Value(sensitivityCtxKey)
	tier, _ := v.(ai.SensitivityTier)
	return tier
}

// Static guards so the unused-uuid import doesn't drift if a future
// refactor drops the asset ID forwarding.
var _ = uuid.Nil
