-- artist-alley schema, as sqlc sees it.
--
-- The runtime schema is created by RS's CheckDBStruct() emitter (see
-- include/database_functions.php), which produces Postgres DDL from
-- dbstruct/*.txt. This file is the *Go-side* declaration: it must
-- mirror what CheckDBStruct emits closely enough for sqlc's compile-
-- time checker to type queries correctly.
--
-- Add only the tables Go code reads or writes. Each table is a small
-- block with a comment pointing at its dbstruct counterpart.
--
-- When CheckDBStruct is retired and Go owns the schema outright, this
-- file becomes the authoritative source and goose migrations under
-- app/migrations/ take over from CheckDBStruct.

-- table_resource_type.txt
CREATE TABLE resource_type (
    ref                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name                VARCHAR(200),
    allowed_extensions  TEXT,
    order_by            BIGINT,
    config_options      TEXT,
    push_metadata       BIGINT,
    colour              BIGINT,
    icon                TEXT,
    tab                 BIGINT,
    pull_images         BIGINT
);

-- table_user.txt — the columns Go's auth layer reads/writes. "user" is
-- a Postgres reserved word, hence the quoting; everything else handles
-- it identically.
CREATE TABLE "user" (
    ref                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    username             VARCHAR(50),
    password             VARCHAR(255),
    fullname             VARCHAR(100),
    email                VARCHAR(100),
    usergroup            BIGINT,
    last_active          TIMESTAMPTZ,
    logged_in            BIGINT,
    accepted_terms       BIGINT NOT NULL DEFAULT 0,
    account_expires      TIMESTAMPTZ,
    session              VARCHAR(50),
    password_last_change TIMESTAMPTZ,
    login_tries          BIGINT NOT NULL DEFAULT 0,
    login_last_try       TIMESTAMPTZ,
    approved             BIGINT NOT NULL DEFAULT 1,
    lang                 VARCHAR(11),
    created              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    origin               VARCHAR(50),
    unique_hash          VARCHAR(50)
);

-- migrations/00001_api_tokens.sql — owned outright by Go (goose).
CREATE TABLE api_tokens (
    id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    rs_user_id    BIGINT       NOT NULL,
    name          TEXT         NOT NULL,
    token_hash    BYTEA        NOT NULL UNIQUE,
    scopes        TEXT[]       NOT NULL DEFAULT '{}',
    expires_at    TIMESTAMPTZ  NULL,
    last_used_at  TIMESTAMPTZ  NULL,
    revoked_at    TIMESTAMPTZ  NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);
