-- artist-alley schema, as sqlc sees it.
--
-- The runtime schema is created by RS's CheckDBStruct() emitter (see
-- include/database_functions.php), which produces Postgres DDL from
-- dbstruct/*.txt. This file is the *Go-side* declaration: it must
-- mirror what CheckDBStruct emits closely enough for sqlc's compile-
-- time checker to type queries correctly.
--
-- Add only the tables Go code reads or writes. Each table is a small
-- block with a comment pointing at its dbstruct counterpart.
--
-- When CheckDBStruct is retired and Go owns the schema outright, this
-- file becomes the authoritative source and goose migrations under
-- app/migrations/ take over from CheckDBStruct.

-- table_resource_type.txt
CREATE TABLE resource_type (
    ref                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name                VARCHAR(200),
    allowed_extensions  TEXT,
    order_by            BIGINT,
    config_options      TEXT,
    push_metadata       BIGINT,
    colour              BIGINT,
    icon                TEXT,
    tab                 BIGINT,
    pull_images         BIGINT
);
