-- artist-alley schema, as sqlc sees it.
--
-- The runtime schema is created by RS's CheckDBStruct() emitter (see
-- include/database_functions.php), which produces Postgres DDL from
-- dbstruct/*.txt. This file is the *Go-side* declaration: it must
-- mirror what CheckDBStruct emits closely enough for sqlc's compile-
-- time checker to type queries correctly.
--
-- Add only the tables Go code reads or writes. Each table is a small
-- block with a comment pointing at its dbstruct counterpart.
--
-- When CheckDBStruct is retired and Go owns the schema outright, this
-- file becomes the authoritative source and goose migrations under
-- app/migrations/ take over from CheckDBStruct.

-- table_resource_type.txt
CREATE TABLE resource_type (
    ref                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name                VARCHAR(200),
    allowed_extensions  TEXT,
    order_by            BIGINT,
    config_options      TEXT,
    push_metadata       BIGINT,
    colour              BIGINT,
    icon                TEXT,
    tab                 BIGINT,
    pull_images         BIGINT
);

-- table_user.txt — the columns Go's auth layer reads/writes. "user" is
-- a Postgres reserved word, hence the quoting; everything else handles
-- it identically.
CREATE TABLE "user" (
    ref                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    username             VARCHAR(50),
    password             VARCHAR(255),
    fullname             VARCHAR(100),
    email                VARCHAR(100),
    usergroup            BIGINT,
    last_active          TIMESTAMPTZ,
    logged_in            BIGINT,
    accepted_terms       BIGINT NOT NULL DEFAULT 0,
    account_expires      TIMESTAMPTZ,
    session              VARCHAR(50),
    password_last_change TIMESTAMPTZ,
    login_tries          BIGINT NOT NULL DEFAULT 0,
    login_last_try       TIMESTAMPTZ,
    approved             BIGINT NOT NULL DEFAULT 1,
    lang                 VARCHAR(11),
    created              TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    origin               VARCHAR(50),
    unique_hash          VARCHAR(50)
);

-- migrations/00001_api_tokens.sql + 00003_api_tokens_origin_server.sql.
-- Owned outright by Go (goose).
CREATE TABLE api_tokens (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    rs_user_id       BIGINT       NOT NULL,
    name             TEXT         NOT NULL,
    token_hash       BYTEA        NOT NULL UNIQUE,
    scopes           TEXT[]       NOT NULL DEFAULT '{}',
    expires_at       TIMESTAMPTZ  NULL,
    last_used_at     TIMESTAMPTZ  NULL,
    revoked_at       TIMESTAMPTZ  NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    origin_server_id UUID         NULL
);

-- migrations/00002_capabilities_roles.sql — authorization model.
CREATE TABLE capabilities (
    code        TEXT PRIMARY KEY,
    description TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE roles (
    id               UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    parent_id        UUID         NULL REFERENCES roles(id) ON DELETE SET NULL,
    name             TEXT         NOT NULL UNIQUE,
    description      TEXT         NOT NULL DEFAULT '',
    origin_server_id UUID         NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE role_capabilities (
    role_id         UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    capability_code TEXT NOT NULL REFERENCES capabilities(code) ON DELETE CASCADE,
    PRIMARY KEY (role_id, capability_code)
);

CREATE TABLE user_role (
    rs_user_id             BIGINT       NOT NULL PRIMARY KEY,
    role_id                UUID         NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    assigned_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    assigned_by_rs_user_id BIGINT       NULL
);

CREATE TABLE user_capability_grants (
    rs_user_id            BIGINT       NOT NULL,
    capability_code       TEXT         NOT NULL REFERENCES capabilities(code) ON DELETE CASCADE,
    granted_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    granted_by_rs_user_id BIGINT       NULL,
    note                  TEXT         NOT NULL DEFAULT '',
    PRIMARY KEY (rs_user_id, capability_code)
);

CREATE TABLE user_capability_revokes (
    rs_user_id            BIGINT       NOT NULL,
    capability_code       TEXT         NOT NULL REFERENCES capabilities(code) ON DELETE CASCADE,
    revoked_at            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    revoked_by_rs_user_id BIGINT       NULL,
    note                  TEXT         NOT NULL DEFAULT '',
    PRIMARY KEY (rs_user_id, capability_code)
);

-- migrations/00004_storage.sql — content-addressed storage layer.
-- See docs/adr/0008-storage-architecture.md.

CREATE TABLE storage_objects (
    hash             TEXT         PRIMARY KEY,
    size_bytes       BIGINT       NOT NULL,
    content_type     TEXT         NOT NULL DEFAULT 'application/octet-stream',
    backend          TEXT         NOT NULL,
    backend_bucket   TEXT         NULL,
    origin_server_id UUID         NULL,
    gc_eligible_at   TIMESTAMPTZ  NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE storage_variants (
    object_hash  TEXT         NOT NULL REFERENCES storage_objects(hash) ON DELETE CASCADE,
    variant_key  TEXT         NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    content_type TEXT         NOT NULL DEFAULT 'application/octet-stream',
    metadata     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (object_hash, variant_key)
);

CREATE TABLE storage_pins (
    object_hash      TEXT         NOT NULL REFERENCES storage_objects(hash) ON DELETE RESTRICT,
    pin_subject_type TEXT         NOT NULL,
    pin_subject_id   TEXT         NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (object_hash, pin_subject_type, pin_subject_id)
);
