#!/usr/bin/env python3
"""
The published archive is the MAINTAINED DATASET for preserved roots (#1319).

WHY THIS MODULE EXISTS
----------------------
ADR 0097 was written when the pipeline had two ends: a source dataset the
repository was built against, and a published archive that was purely an
OUTPUT. Every safety rule followed from that shape: the destination is
never an input, a disagreement means the profile is stale, and the fix is
always to correct the profile.

That shape is gone. The old `$DATASET_SRC`
(`/mnt/d/Projects/unraid_management/artist-alley_dataset`) has been
permanently retired and no longer exists, and the maintained datasets are
the ones under `/mnt/blackbox_archives/datasets/artist_alley`. For the
`local` root the archive is now the ONLY copy of the bytes, measured on
the committed profiles:

    site_a `local` 696 records, site_b `local` 552
      0 carry `metadata.media_url`   (nothing to re-fetch from)
      0 carry `metadata.source_archive` (no attested upstream member)
      2 carry `metadata.sha256`     (the two unpublished authored plates)

So `local` cannot be re-derived from anywhere. `hq` and `pack` still can:
`hq` renders from the Kenney pack through the committed
`seed/upgrades/kenney-hq-pool.json`, and `pack` copies or extracts
members verified against `metadata.source_archive.sha256` (378 of 378
carry one). They stay SOURCE-BACKED, and that is not a preference. The
published trees disagree with the profiles on `file_size_bytes` for 1
record (site_a) and 392 (site_b), every one of them `hq`, because the
share holds an older pool build. Reclassifying `hq` as measurable would
turn all 393 into `CORRUPTED_MEASUREMENT` and refuse every publish.

AUTHORITY IS PER ROOT, AND THE PRESERVED CLAIM IS THE WEAKER ONE
----------------------------------------------------------------
  hq, pack                  source-backed. Authority is the external
                            Kenney pack / `source_archive`.
  local (+ generated bytes
  held only in the archive)  ARCHIVE-AUTHORITATIVE / PRESERVED. Authority
                            is a FROZEN PRE-OPERATION SNAPSHOT of the
                            archive, attested by an external manifest.
  site, internet,
  torrent_import            unchanged.

⛔ `preserved_archive` IS EXPLICITLY WEAKER THAN `produced_source`, and
nothing here pretends otherwise. A produced-source claim can be re-derived
from an input nobody in this pipeline controls; a preserved claim can only
be compared against a copy we took ourselves. Its entire integrity rests
on recomputing the snapshot against a manifest recorded immediately after
the snapshot was made. ⛔ IT NEVER RESTS ON THE ARCHIVE AGREEING WITH
ITSELF: a stale copy agrees with itself perfectly, and permissions and
mtimes are not integrity, because a CIFS tree can change under both.

WHAT THIS MODULE OWNS
---------------------
  1. ALIAS REFUSAL. Source and destination must be distinct trees, and
     equality is not the only way to alias: a source that CONTAINS the
     destination, or sits inside it, is the same defect. Resolved paths
     only, so `..`, a symlink or a trailing slash cannot defeat it.
  2. THE metadata.csv EXPECTED-TRANSFORM CONTRACT. A preserved publish
     may not regenerate `metadata.csv` from the profile's source-path map
     (see below), and it may not be waived either. It changes only in the
     one way a document written BEFORE the operation says it may.
  3. THE FROZEN-SNAPSHOT MANIFEST. Recomputation immediately before a
     preserved authentication, never a trust of the copy.

⛔ WHY THE CSV REGENERATION HAD TO GO RATHER THAN BE POINTED SOMEWHERE ELSE
`populate_archive.py` keeps a CSV row only when its `file_path` is in the
profile's SOURCE-path map, and rewrites that column to the destination
path. Run with the published archive as `--local-source`, the CSV it
reads already holds DESTINATION paths, so nothing matches and it writes a
HEADER-ONLY file. Measured on the real published tree: 0 of 907 site_a
rows match, 0 of 1206 site_b. And `metadata.csv` is not preservation-owned
(`verify_site.PRESERVED_NAMES` covered only `dataset-metadata.json`,
`kenney-hq-replacements.json` and `*.bak`), so nothing noticed. The
destination would have become its own evidence.

⛔ AND IT IS NOT MADE AN ORDINARY EXACT-BASELINE FILE EITHER. A retirement
legitimately removes its row, so a rule of "these bytes may never change"
would refuse the one change that is correct. The expected-transform
document is the narrow shape: exactly the documented rows leave, every
other row survives BYTE-IDENTICALLY AND IN ORDER, and the whole-file hash
afterwards is stated in advance.

⚠️ THE RETAINED ROWS ARE FILTERED BY BYTE, NOT PARSED AND REWRITTEN.
Measured on the real published files: both use CRLF terminators, and
site_b's `metadata.csv` carries 9 BARE LFs inside quoted fields (1,216 LF
bytes against 1,206 logical rows). A `csv`-module round trip would
re-quote and re-terminate those, so "the retained rows are unchanged"
would be false the first time it ran. A record here is delimited by a
newline OUTSIDE a quoted field and its bytes are copied through
untouched.

Usage
-----
    # BEFORE the operation, from the frozen pre-op CSV + the collapse document
    python3 preserved_archive.py csv-transform \\
        --site <frozen-snapshot-or-live-site> \\
        --collapse-document seed/upgrades/asset-collapse.studio-a.json \\
        --out <outside-every-site-tree>/site_a.csv-transform.json

    # immediately after taking the frozen snapshot
    python3 preserved_archive.py snapshot-manifest \\
        --snapshot <frozen-snapshot> \\
        --out <outside-the-snapshot>/site_a.snapshot-manifest.json

    # read-only verification of a CSV against its transform document
    python3 preserved_archive.py verify-csv \\
        --transform <doc> --csv <site>/metadata.csv
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import sys
from pathlib import Path
from typing import Iterable, Mapping

# The roots the archive is authoritative for. `local` is the measured
# case: no media_url, no source_archive, and the source tree is gone.
PRESERVED_ROOTS = frozenset({"local"})

CSV_NAME = "metadata.csv"
GROUPS_NAME = "groups.csv"

TRANSFORM_KIND = "metadata-csv-transform"
TRANSFORM_VERSION = 1
SNAPSHOT_KIND = "frozen-snapshot-manifest"

FILE_PATH_COLUMN = "file_path"

_SHA256_HEX = 64


class PreservedError(ValueError):
    """The contract cannot be used, so nothing may proceed.

    Raised, never returned, for the reason `CollapseError` is: an
    unusable document must never quietly become "no expectations". That
    reading is what let a header-only `metadata.csv` publish in silence.
    """


# ---------------------------------------------------------------------------
# 1. Alias refusal
# ---------------------------------------------------------------------------

def _resolved(p: Path | str) -> Path:
    return Path(p).expanduser().resolve()


def _contains(outer: Path, inner: Path) -> bool:
    """`inner` is at or below `outer`, on resolved paths only.

    `is_relative_to` rather than a string prefix: `/a/bc` starts with
    `/a/b` as text and is not inside it, and `..` plus a symlink defeat
    prefix matching in both directions.
    """
    return inner == outer or inner.is_relative_to(outer)


def alias_refusals(paths: Mapping[str, Path | str | None], *,
                   equal_ok_within: Iterable[Iterable[str]] = ()) -> list[str]:
    """Every pair of supplied paths that are the same tree, or nested.

    ⛔ THIS RUNS BEFORE ANY MUTATION AND BEFORE ANY EVIDENCE IS USED. A
    source root that IS the destination makes the destination its own
    evidence, which is the exact failure ADR 0097 exists to prevent, and
    nesting is the same defect: a "source" holding the destination inside
    it reads bytes this run is about to write.

    Every path the caller knows about is passed in, labelled, including
    the frozen snapshot, the evidence documents and the scratch
    directories. A pair missing from the map is a pair nobody checked.
    """
    groups = [frozenset(g) for g in equal_ok_within]
    named = [(label, _resolved(p)) for label, p in paths.items() if p is not None]
    out: list[str] = []
    for i, (la, a) in enumerate(named):
        for lb, b in named[i + 1:]:
            if a == b:
                # ⚠️ TWO READ-ONLY SOURCE ROOTS MAY BE ONE TREE, and that is
                # the only exemption. A single dataset root serving both
                # `local` and `internet` reads the same bytes twice and
                # writes nothing, so it is a configuration rather than a
                # defect. Nesting is still refused even inside a group, and
                # nothing is ever exempted from the comparison against the
                # tree this run WRITES.
                if any(la in g and lb in g for g in groups):
                    continue
                out.append(f"{la} and {lb} are the same path ({a}); one of them "
                           f"would be its own evidence")
            elif _contains(a, b):
                out.append(f"{la} ({a}) CONTAINS {lb} ({b}); reading through one "
                           f"would read bytes the other writes")
            elif _contains(b, a):
                out.append(f"{lb} ({b}) CONTAINS {la} ({a}); reading through one "
                           f"would read bytes the other writes")
    return out


def refuse_aliasing(paths: Mapping[str, Path | str | None], *,
                    equal_ok_within: Iterable[Iterable[str]] = (),
                    stream=None) -> bool:
    """Print and return False on any aliasing; True when the set is clean.

    ⚠️ `stream` defaults to None and is resolved at CALL time. A
    `stream=sys.stderr` default is bound once, at import, so a caller that
    redirects stderr would not see the refusal, and a refusal nobody can
    read is a refusal nobody can act on.
    """
    stream = stream or sys.stderr
    bad = alias_refusals(paths, equal_ok_within=equal_ok_within)
    if not bad:
        return True
    print(f"error: {len(bad)} path aliasing refusal(s):", file=stream)
    for b in bad:
        print(f"  - {b}", file=stream)
    print("  Refusing. Source and destination must be distinct trees: the "
          "published archive is the thing being written, so it cannot also be "
          "the thing being read as authority.", file=stream)
    return False


# ---------------------------------------------------------------------------
# 2. The metadata.csv expected-transform contract
# ---------------------------------------------------------------------------

def split_csv_records(blob: bytes) -> tuple[bytes, list[bytes]]:
    """(header bytes, data record bytes), every record keeping its own
    terminator so the concatenation is the original file exactly.

    A record ends at a newline that is not inside a quoted field. See the
    module docstring: site_b's published CSV carries bare LFs inside
    quoted values, and a parse-and-rewrite would not give them back.
    """
    records: list[bytes] = []
    start = 0
    in_quote = False
    for i, byte in enumerate(blob):
        if byte == 0x22:            # "
            in_quote = not in_quote
        elif byte == 0x0A and not in_quote:
            records.append(blob[start:i + 1])
            start = i + 1
    if start < len(blob):
        records.append(blob[start:])
    if not records:
        raise PreservedError("the CSV is empty: there is not even a header row")
    if in_quote:
        raise PreservedError("the CSV ends inside a quoted field; it is truncated "
                             "and cannot be filtered safely")
    return records[0], records[1:]


def record_fields(record: bytes) -> list[str]:
    """The parsed fields of one raw record. Parsing is for READING a
    column; the bytes themselves are never re-emitted from here."""
    text = record.decode("utf-8")
    rows = list(csv.reader(io.StringIO(text)))
    return rows[0] if rows else []


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def ordered_digest(row_digests: Iterable[str]) -> str:
    """Order-sensitive digest over the retained rows.

    ⛔ ORDER IS PART OF THE CLAIM. A digest over a SET would accept a
    reordered file, and a reordered `metadata.csv` is a changed published
    artifact whatever its multiset of rows says.
    """
    h = hashlib.sha256()
    for d in row_digests:
        h.update(bytes.fromhex(d))
    return h.hexdigest()


def _file_path_index(header: bytes) -> tuple[list[str], int]:
    fields = record_fields(header)
    if FILE_PATH_COLUMN not in fields:
        raise PreservedError(
            f"the CSV header has no {FILE_PATH_COLUMN!r} column, so a row cannot "
            f"be tied to a retired record. Header: {fields}")
    return fields, fields.index(FILE_PATH_COLUMN)


def read_csv(path: Path) -> tuple[bytes, bytes, list[bytes], list[str], int]:
    """(blob, header, rows, header_fields, file_path column index)."""
    try:
        blob = path.read_bytes()
    except OSError as e:
        raise PreservedError(f"{path}: unreadable ({e})") from e
    header, rows = split_csv_records(blob)
    fields, idx = _file_path_index(header)
    return blob, header, rows, fields, idx


def build_csv_transform(csv_path: Path, *,
                        removals: Iterable[tuple[str, str]],
                        site: Path | None = None) -> dict:
    """The expected-transform document, from the PRE-OPERATION CSV.

    `removals` is (file_path, retired_id) pairs, taken from the committed
    collapse document. A retirement whose `retired_file_path` has no row
    here contributes no removal, which is how site_a's ZERO-REMOVAL
    transform arises: its `metadata.csv` must stay byte-identical, 907
    rows to 907, and that is an expectation to enforce rather than a case
    to skip.
    """
    blob, header, rows, fields, idx = read_csv(csv_path)

    # ⛔ CARDINALITY BEFORE KEYING ON IT. The removals are keyed by
    # `file_path`, so a duplicated one would make "the row this retired
    # record names" ambiguous and could drop a row nobody enumerated.
    seen: dict[str, int] = {}
    for row in rows:
        f = record_fields(row)
        if len(f) <= idx:
            raise PreservedError(
                f"{csv_path}: a data row has {len(f)} field(s), fewer than the "
                f"{len(fields)}-field header reaches; the file is malformed")
        seen[f[idx]] = seen.get(f[idx], 0) + 1
    dupes = sorted(k for k, n in seen.items() if n > 1)
    if dupes:
        raise PreservedError(
            f"{csv_path}: {len(dupes)} {FILE_PATH_COLUMN} value(s) appear on more "
            f"than one row ({dupes[:5]}). A removal is keyed on this column, so a "
            f"duplicate makes the row a retirement names ambiguous.")

    wanted: dict[str, str] = {}
    for file_path, retired_id in removals:
        if file_path in wanted:
            raise PreservedError(
                f"two retirements name the same row {file_path!r} "
                f"({wanted[file_path]} and {retired_id})")
        if file_path not in seen:
            # Not an error: an `hq` retirement whose produced render has
            # no CSV row is the ordinary case. Recorded nowhere, removed
            # nowhere.
            continue
        wanted[file_path] = retired_id

    retained: list[bytes] = []
    removed: list[dict] = []
    for row in rows:
        fp = record_fields(row)[idx]
        rid = wanted.get(fp)
        if rid is not None:
            removed.append({FILE_PATH_COLUMN: fp, "retired_id": rid})
            continue
        retained.append(row)

    digests = [_sha(r) for r in retained]
    after = header + b"".join(retained)
    return {
        "_why": [
            "THE ONE WAY metadata.csv MAY CHANGE IN A PRESERVED PUBLISH (#1319).",
            "Produced BEFORE the operation from the frozen pre-op CSV and the "
            "committed asset-collapse document. Exactly the rows named below "
            "leave; every other row survives byte-identically and in order.",
            "The published CSV is not regenerated from the profile's source-path "
            "map: its file_path column already holds DESTINATION paths, so the "
            "regeneration matched 0 rows and wrote a header-only file.",
        ],
        "kind": TRANSFORM_KIND,
        "version": TRANSFORM_VERSION,
        "site": str(_resolved(site)) if site is not None else "",
        "csv": CSV_NAME,
        "original": {
            "sha256": _sha(blob),
            "bytes": len(blob),
            "data_rows": len(rows),
        },
        "header": {
            "fields": fields,
            "field_count": len(fields),
            "sha256": _sha(header),
        },
        "removals": sorted(removed, key=lambda r: r[FILE_PATH_COLUMN]),
        "expected": {
            "sha256": _sha(after),
            "bytes": len(after),
            "data_rows": len(retained),
            "ordered_digest": ordered_digest(digests),
            "row_digests": digests,
        },
    }


def _require(cond: bool, source: str, msg: str) -> None:
    if not cond:
        raise PreservedError(f"{source}: {msg}")


def _hexish(v) -> bool:
    return (isinstance(v, str) and len(v) == _SHA256_HEX
            and all(c in "0123456789abcdef" for c in v))


def parse_csv_transform(data, *, source: str) -> dict:
    """Validate a transform document, fail closed."""
    _require(isinstance(data, dict), source, "expected an object")
    _require(data.get("kind") == TRANSFORM_KIND, source,
             f"kind is {data.get('kind')!r}, not {TRANSFORM_KIND!r}")
    _require(data.get("version") == TRANSFORM_VERSION, source,
             f"version is {data.get('version')!r}, not {TRANSFORM_VERSION}")
    for section, keys in (("original", ("sha256", "bytes", "data_rows")),
                          ("header", ("fields", "field_count", "sha256")),
                          ("expected", ("sha256", "bytes", "data_rows",
                                        "ordered_digest", "row_digests"))):
        blk = data.get(section)
        _require(isinstance(blk, dict), source, f"`{section}` is not an object")
        missing = [k for k in keys if k not in blk]
        _require(not missing, source, f"`{section}` is missing {missing}")
    for path in (("original", "sha256"), ("header", "sha256"),
                 ("expected", "sha256"), ("expected", "ordered_digest")):
        v = data[path[0]][path[1]]
        _require(_hexish(v), source, f"{path[0]}.{path[1]} is not a sha256: {v!r}")
    fields = data["header"]["fields"]
    _require(isinstance(fields, list) and fields
             and all(isinstance(f, str) for f in fields), source,
             "header.fields must be a non-empty list of column names")
    _require(data["header"]["field_count"] == len(fields), source,
             f"header.field_count is {data['header']['field_count']!r} but "
             f"header.fields holds {len(fields)}")
    _require(FILE_PATH_COLUMN in fields, source,
             f"header.fields has no {FILE_PATH_COLUMN!r} column")
    digests = data["expected"]["row_digests"]
    _require(isinstance(digests, list) and all(_hexish(d) for d in digests), source,
             "expected.row_digests must be a list of sha256 digests")
    _require(data["expected"]["data_rows"] == len(digests), source,
             f"expected.data_rows is {data['expected']['data_rows']!r} but "
             f"expected.row_digests holds {len(digests)}")
    _require(ordered_digest(digests) == data["expected"]["ordered_digest"], source,
             "expected.ordered_digest does not match expected.row_digests; the "
             "document disagrees with itself")
    removals = data.get("removals")
    _require(isinstance(removals, list), source, "`removals` must be a list")
    seen_fp: set[str] = set()
    seen_rid: set[str] = set()
    for i, r in enumerate(removals):
        _require(isinstance(r, dict) and set(r) == {FILE_PATH_COLUMN, "retired_id"},
                 source, f"removals[{i}] must hold exactly {FILE_PATH_COLUMN} and "
                         f"retired_id, got {sorted(r) if isinstance(r, dict) else r!r}")
        fp, rid = r[FILE_PATH_COLUMN], r["retired_id"]
        _require(isinstance(fp, str) and fp, source,
                 f"removals[{i}].{FILE_PATH_COLUMN} is empty")
        _require(isinstance(rid, str) and rid, source,
                 f"removals[{i}].retired_id is empty")
        _require(fp not in seen_fp, source, f"removals names {fp} twice")
        _require(rid not in seen_rid, source, f"removals names {rid} twice")
        seen_fp.add(fp)
        seen_rid.add(rid)
    _require(data["original"]["data_rows"]
             == data["expected"]["data_rows"] + len(removals), source,
             f"the arithmetic does not close: {data['original']['data_rows']} "
             f"original row(s) minus {len(removals)} removal(s) is not "
             f"{data['expected']['data_rows']}")
    return data


def load_csv_transform(path: Path) -> dict:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        raise PreservedError(f"{path}: unreadable ({e})") from e
    return parse_csv_transform(data, source=str(path))


def transform_csv(blob: bytes, doc: dict) -> tuple[bytes, list[str]]:
    """Apply the documented transform to the PRE-OPERATION bytes.

    Returns (after, refusals). A non-empty refusal list means nothing may
    be written: the input is not the file the document describes.
    """
    refusals: list[str] = []
    if _sha(blob) != doc["original"]["sha256"]:
        refusals.append(
            f"the CSV hashes {_sha(blob)[:12]}… but the transform document was "
            f"built from {doc['original']['sha256'][:12]}…. The document is not "
            f"evidence about these bytes; re-emit it from the frozen pre-op copy "
            f"rather than widening the check.")
        return b"", refusals
    header, rows = split_csv_records(blob)
    fields, idx = _file_path_index(header)
    if fields != doc["header"]["fields"]:
        refusals.append(f"the CSV header does not match the document's "
                        f"{doc['header']['field_count']} field(s)")
        return b"", refusals
    wanted = {r[FILE_PATH_COLUMN]: r["retired_id"] for r in doc["removals"]}
    retained: list[bytes] = []
    hit: set[str] = set()
    for row in rows:
        fp = record_fields(row)[idx]
        if fp in wanted:
            hit.add(fp)
            continue
        retained.append(row)
    absent = sorted(set(wanted) - hit)
    if absent:
        refusals.append(
            f"{len(absent)} documented removal(s) have no row to remove "
            f"({absent[:5]}); the file is not in the state the document describes")
        return b"", refusals
    return header + b"".join(retained), refusals


def verify_csv_transform(doc: dict, blob: bytes) -> list[str]:
    """Every way the bytes can fail to be the documented transform.

    ⛔ EVERY CHECK RUNS AND EVERY FAILURE IS REPORTED. Returning at the
    first refusal would make the second one invisible, and an operator
    who fixes one and re-runs deserves to have seen both.
    """
    refusals: list[str] = []
    exp = doc["expected"]

    if _sha(blob) == doc["original"]["sha256"] and doc["removals"]:
        refusals.append("these are still the PRE-OPERATION bytes: the documented "
                        "removals have not been applied")

    try:
        header, rows = split_csv_records(blob)
    except PreservedError as e:
        return refusals + [str(e)]

    if _sha(header) != doc["header"]["sha256"]:
        refusals.append(
            f"the header row changed: {_sha(header)[:12]}… against the documented "
            f"{doc['header']['sha256'][:12]}…. The 41-field header is part of the "
            f"published contract and a preserved publish does not rewrite it.")
    else:
        fields = record_fields(header)
        if fields != doc["header"]["fields"]:
            refusals.append(f"the header parses to {len(fields)} field(s), not the "
                            f"documented {doc['header']['field_count']}")

    if len(rows) != exp["data_rows"]:
        refusals.append(f"{len(rows)} data row(s), the document expects "
                        f"{exp['data_rows']}")

    try:
        fields = record_fields(header)
        idx = fields.index(FILE_PATH_COLUMN)
    except ValueError:
        idx = -1
    if idx >= 0:
        present = set()
        for row in rows:
            f = record_fields(row)
            if len(f) > idx:
                present.add(f[idx])
        still_here = sorted(r[FILE_PATH_COLUMN] for r in doc["removals"]
                            if r[FILE_PATH_COLUMN] in present)
        if still_here:
            by_fp = {r[FILE_PATH_COLUMN]: r["retired_id"] for r in doc["removals"]}
            refusals.append(
                f"{len(still_here)} documented removal(s) are still in the file "
                f"({[f'{p} ({by_fp[p]})' for p in still_here[:3]]}); a removal the "
                f"document authorises and the file did not make is not a pass")

    got = [_sha(r) for r in rows]
    want = list(exp["row_digests"])
    if got != want:
        if sorted(got) == sorted(want):
            first = next((i for i, (a, b) in enumerate(zip(got, want)) if a != b),
                         len(want))
            refusals.append(
                f"the retained rows are REORDERED: row {first} is not the one the "
                f"document records there, and the multiset is unchanged. Order is "
                f"part of the published artifact.")
        else:
            extra = sorted(set(got) - set(want))
            gone = sorted(set(want) - set(got))
            first = next((i for i, (a, b) in enumerate(zip(got, want)) if a != b),
                         min(len(got), len(want)))
            refusals.append(
                f"the retained rows are not the documented ones: first difference "
                f"at row {first}; {len(extra)} row(s) the document does not record "
                f"and {len(gone)} recorded row(s) absent. A retained row must "
                f"survive BYTE-IDENTICALLY; the document is not a summary of it.")

    if ordered_digest(got) != exp["ordered_digest"]:
        refusals.append(f"the ordered digest of the retained rows is "
                        f"{ordered_digest(got)[:12]}…, the document expects "
                        f"{exp['ordered_digest'][:12]}…")

    whole = _sha(blob)
    if whole != exp["sha256"]:
        refusals.append(f"the whole file hashes {whole[:12]}…, the document expects "
                        f"{exp['sha256'][:12]}… ({len(blob)} B against "
                        f"{exp['bytes']} B)")
    return refusals


def removals_from_collapse(doc) -> list[tuple[str, str]]:
    """(retired_file_path, retired_id) for every entry of a collapse
    document, whatever its evidence kind.

    A retirement deletes its produced file, so if the CSV holds a row for
    that path the row goes with it. Which rows actually exist is decided
    against the CSV in `build_csv_transform`, not here.
    """
    return [(e.retired_file_path, e.retired_id) for e in doc.entries]


# ---------------------------------------------------------------------------
# 3. The frozen-snapshot manifest
# ---------------------------------------------------------------------------

def build_snapshot_manifest(snapshot: Path) -> dict:
    """path -> sha256 for every regular file under a frozen snapshot.

    Recorded IMMEDIATELY AFTER the snapshot is made, and kept OUTSIDE it.
    ⛔ Bytes only. Not mtime, not size, not mode: a CIFS tree can change
    under all three, and a copy that agrees with its own metadata is the
    oldest form of this mistake.
    """
    root = _resolved(snapshot)
    files = {p.relative_to(root).as_posix(): sha256_file(p)
             for p in sorted(root.rglob("*")) if p.is_file()}
    return {
        "_why": [
            "FROZEN PRE-OPERATION SNAPSHOT ATTESTATION (#1319).",
            "preserved_archive evidence is authenticated against this snapshot, "
            "and the snapshot is only trustworthy because these hashes are "
            "recomputed against it immediately before that authentication.",
            "Bytes only. Permissions and mtimes are not integrity proof.",
        ],
        "kind": SNAPSHOT_KIND,
        "snapshot": str(root),
        "files": files,
    }


def parse_snapshot_manifest(data, *, source: str) -> dict[str, str]:
    _require(isinstance(data, dict), source, "expected an object")
    _require(data.get("kind") == SNAPSHOT_KIND, source,
             f"kind is {data.get('kind')!r}, not {SNAPSHOT_KIND!r}")
    files = data.get("files")
    _require(isinstance(files, dict) and files, source,
             "`files` must be a non-empty object of path -> sha256")
    for rel, sha in files.items():
        _require(isinstance(rel, str) and rel, source, "a manifest key is empty")
        _require(_hexish(sha), source, f"files[{rel!r}] is not a sha256: {sha!r}")
    return dict(files)


def load_snapshot_manifest(path: Path) -> dict[str, str]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        raise PreservedError(f"{path}: unreadable ({e})") from e
    return parse_snapshot_manifest(data, source=str(path))


def recompute_snapshot(snapshot: Path, manifest: Mapping[str, str],
                       rels: Iterable[str]) -> list[str]:
    """RE-HASH the snapshot paths a preserved authentication is about to
    read, and compare them against the external manifest.

    ⛔ THIS IS THE WHOLE OF WHY `preserved_archive` IS EVIDENCE AT ALL. The
    snapshot is a copy we took; the manifest is what we said it was at the
    moment we took it. Without this step the authentication would be the
    archive agreeing with itself, which a stale copy does perfectly.

    Returns refusals. An empty list means every named path is present and
    still exactly the bytes the manifest attests.
    """
    root = _resolved(snapshot)
    refusals: list[str] = []
    for rel in sorted(set(rels)):
        want = manifest.get(rel)
        if want is None:
            refusals.append(
                f"{rel} is not in the snapshot manifest, so nothing attests it. "
                f"An unattested path cannot authenticate a preserved retirement.")
            continue
        p = root / rel
        if not p.is_file():
            refusals.append(f"{rel} is in the manifest but absent from the "
                            f"snapshot at {root}")
            continue
        got = sha256_file(p)
        if got != want:
            refusals.append(
                f"{rel} hashes {got[:12]}… but the manifest recorded "
                f"{want[:12]}…. The snapshot CHANGED after it was attested, so it "
                f"is not frozen and cannot authenticate anything. Permissions and "
                f"mtimes say nothing about this.")
    return refusals


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _refuse_out_under(out: Path, site: Path, what: str) -> bool:
    """Mirror `verify_site.py baseline`: evidence never lives inside the
    tree it describes, because the operation rewrites that tree."""
    o, s = _resolved(out), _resolved(site)
    if _contains(s, o):
        print(f"error: --out {o} is under {what} {s}; evidence about a tree must "
              f"not live inside it", file=sys.stderr)
        return False
    return True


def _cmd_csv_transform(args) -> int:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import asset_collapse as ac  # local import: only this subcommand needs it

    if not _refuse_out_under(args.out, args.site, "--site"):
        return 2
    site = _resolved(args.site)
    if not site.is_dir():
        print(f"error: --site {site} is not a directory", file=sys.stderr)
        return 2
    removals: list[tuple[str, str]] = []
    if args.collapse_document is not None:
        try:
            doc = ac.load_collapse_document(args.collapse_document)
        except ac.CollapseError as e:
            print(f"error: {e}\n  Refusing: an asset-collapse document that "
                  f"cannot be validated is not evidence, and a transform built "
                  f"from it would not be either.", file=sys.stderr)
            return 2
        removals = removals_from_collapse(doc)
    try:
        out_doc = build_csv_transform(site / CSV_NAME, removals=removals, site=site)
    except PreservedError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(out_doc, indent=1) + "\n", encoding="utf-8")
    print(f"recorded the expected transform of {site / CSV_NAME}: "
          f"{out_doc['original']['data_rows']} row(s) -> "
          f"{out_doc['expected']['data_rows']}, "
          f"{len(out_doc['removals'])} documented removal(s)", file=sys.stderr)
    if not out_doc["removals"]:
        print("  ZERO-REMOVAL transform: this metadata.csv must stay "
              "byte-identical. That is an expectation to enforce, not a case to "
              "skip.", file=sys.stderr)
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


def _cmd_snapshot_manifest(args) -> int:
    if not _refuse_out_under(args.out, args.snapshot, "--snapshot"):
        return 2
    snap = _resolved(args.snapshot)
    if not snap.is_dir():
        print(f"error: --snapshot {snap} is not a directory", file=sys.stderr)
        return 2
    doc = build_snapshot_manifest(snap)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(doc, indent=1, sort_keys=True) + "\n",
                        encoding="utf-8")
    print(f"attested {len(doc['files'])} file(s) under {snap} into {args.out}",
          file=sys.stderr)
    return 0


def _cmd_verify_csv(args) -> int:
    try:
        doc = load_csv_transform(args.transform)
        blob = args.csv.read_bytes()
    except (PreservedError, OSError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    refusals = verify_csv_transform(doc, blob)
    if refusals:
        print(f"⛔ {args.csv} is not the documented transform "
              f"({len(refusals)} refusal(s)):", file=sys.stderr)
        for r in refusals:
            print(f"  - {r}", file=sys.stderr)
        return 1
    print(f"{args.csv} is exactly the documented transform: "
          f"{doc['expected']['data_rows']} retained row(s), "
          f"{len(doc['removals'])} removal(s)", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    t = sub.add_parser("csv-transform",
                       help="record the one way metadata.csv may change")
    t.add_argument("--site", required=True, type=Path,
                   help="the frozen pre-operation site (or the live site, read "
                        "only) whose metadata.csv is the input")
    t.add_argument("--collapse-document", type=Path, default=None,
                   help="committed asset-collapse document; its retirements are "
                        "the only rows that may be removed")
    t.add_argument("--out", required=True, type=Path,
                   help="where to write it; never under --site")
    t.set_defaults(fn=_cmd_csv_transform)

    s = sub.add_parser("snapshot-manifest",
                       help="attest a frozen snapshot, bytes only")
    s.add_argument("--snapshot", required=True, type=Path)
    s.add_argument("--out", required=True, type=Path,
                   help="where to write it; never under --snapshot")
    s.set_defaults(fn=_cmd_snapshot_manifest)

    v = sub.add_parser("verify-csv", help="check a metadata.csv against its "
                                          "transform document (read only)")
    v.add_argument("--transform", required=True, type=Path)
    v.add_argument("--csv", required=True, type=Path)
    v.set_defaults(fn=_cmd_verify_csv)

    args = ap.parse_args(argv)
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
