// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package requests

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingRequests = `-- name: CountPendingRequests :one
SELECT COUNT(*)::BIGINT FROM resource_request WHERE state = 'pending'
`

// Total count of pending rows (no capability filter — the badge
// callers post-filter or accept the unfiltered count).
func (q *Queries) CountPendingRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRequests)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countPendingRequestsForOwner = `-- name: CountPendingRequestsForOwner :one
SELECT COUNT(*)::BIGINT FROM (
    SELECT rr.id
    FROM resource_request rr
    JOIN assets a ON a.id = rr.target_id
    WHERE rr.state = 'pending'
      AND rr.target_kind = 'asset'
      AND rr.requested_capability <> 'content.restore.request'
      AND a.owner_user_ref = $1
      AND a.deleted_at IS NULL
    UNION
    SELECT rr.id
    FROM resource_request rr
    JOIN (
        SELECT id, deleted_by_user_ref, 'asset'::TEXT AS kind
          FROM assets WHERE deleted_at IS NOT NULL
        UNION ALL
        SELECT id, deleted_by_user_ref, 'post'::TEXT
          FROM posts WHERE deleted_at IS NOT NULL
        UNION ALL
        SELECT id, deleted_by_user_ref, 'collection'::TEXT
          FROM collections WHERE deleted_at IS NOT NULL
    ) tgt ON tgt.id = rr.target_id AND tgt.kind = rr.target_kind
    WHERE rr.state = 'pending'
      AND rr.requested_capability = 'content.restore.request'
      AND tgt.deleted_by_user_ref = $1
) q
`

// Badge value for the queue above. Same two branches, kept adjacent so
// they change together — a count that disagreed with its list would
// show a badge for rows the page cannot render.
func (q *Queries) CountPendingRequestsForOwner(ctx context.Context, ownerUserRef *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRequestsForOwner, ownerUserRef)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findPendingRequestForAsk = `-- name: FindPendingRequestForAsk :one
SELECT id, requester_user_ref, target_id, requested_capability,
       reason, state, decided_at, decided_by_user_ref, decision_reason,
       expires_at, requested_at, target_kind
FROM resource_request
WHERE requester_user_ref = $1
  AND target_kind = $2
  AND target_id = $3
  AND requested_capability = $4
  AND state = 'pending'
`

type FindPendingRequestForAskParams struct {
	RequesterUserRef    int64
	TargetKind          string
	TargetID            pgtype.UUID
	RequestedCapability string
}

// The coalesce read (#881, widened by #931). One ask is
// (requester, kind, id, capability); a second one while the first is
// still pending is the same question asked twice, not a new question,
// so Submit returns this row instead of filing another. Matches the
// partial unique index resource_request_one_pending_per_ask exactly —
// if these two ever disagree, the INSERT's 23505 recovery path reads
// nothing back, and the coalesce silently becomes a 500 under a
// double-click.
func (q *Queries) FindPendingRequestForAsk(ctx context.Context, arg FindPendingRequestForAskParams) (ResourceRequest, error) {
	row := q.db.QueryRow(ctx, findPendingRequestForAsk,
		arg.RequesterUserRef,
		arg.TargetKind,
		arg.TargetID,
		arg.RequestedCapability,
	)
	var i ResourceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserRef,
		&i.TargetID,
		&i.RequestedCapability,
		&i.Reason,
		&i.State,
		&i.DecidedAt,
		&i.DecidedByUserRef,
		&i.DecisionReason,
		&i.ExpiresAt,
		&i.RequestedAt,
		&i.TargetKind,
	)
	return i, err
}

const getAssetDeleteState = `-- name: GetAssetDeleteState :one

SELECT deleted_at, deleted_by_user_ref FROM assets WHERE id = $1
`

type GetAssetDeleteStateRow struct {
	DeletedAt        pgtype.Timestamptz
	DeletedByUserRef *int64
}

// ---------------------------------------------------------------------
// Delete state of an appeal's target (#931)
//
// Three queries rather than one because sqlc cannot parameterise a
// table name, and a hand-built `SELECT ... FROM `+table would put a
// string-concatenated identifier on an authorisation path. The Go side
// (Handler.TargetDeleteState) switches on the closed `target_kind`
// enum, so the set of reachable tables is fixed at compile time.
//
// Both columns matter and they answer different questions:
//
//	deleted_at IS NULL      → is there anything to appeal? (Submit)
//	deleted_by_user_ref     → who may decide the appeal? (Decide)
//
// The second is read regardless of the first, because a restore does
// NOT clear deleted_by_user_ref — only deleted_at and deleted_reason.
// That is what lets the deleter still decide an appeal someone else
// already satisfied, instead of the row becoming undecidable the
// moment it is restored.
//
// Ownership is deliberately NOT selected here. It has one home,
// shares.ObjectOwnerRef (#665/#893), and a second copy in this file
// would be a copy that drifts.
// ---------------------------------------------------------------------
func (q *Queries) GetAssetDeleteState(ctx context.Context, id pgtype.UUID) (GetAssetDeleteStateRow, error) {
	row := q.db.QueryRow(ctx, getAssetDeleteState, id)
	var i GetAssetDeleteStateRow
	err := row.Scan(&i.DeletedAt, &i.DeletedByUserRef)
	return i, err
}

const getCollectionDeleteState = `-- name: GetCollectionDeleteState :one
SELECT deleted_at, deleted_by_user_ref FROM collections WHERE id = $1
`

type GetCollectionDeleteStateRow struct {
	DeletedAt        pgtype.Timestamptz
	DeletedByUserRef *int64
}

func (q *Queries) GetCollectionDeleteState(ctx context.Context, id pgtype.UUID) (GetCollectionDeleteStateRow, error) {
	row := q.db.QueryRow(ctx, getCollectionDeleteState, id)
	var i GetCollectionDeleteStateRow
	err := row.Scan(&i.DeletedAt, &i.DeletedByUserRef)
	return i, err
}

const getGrantsByRequestRef = `-- name: GetGrantsByRequestRef :many
SELECT user_ref, capability_code, granted_at, granted_by_user_ref,
       note, team_id, expires_at, request_ref
FROM user_capability_grants
WHERE request_ref = $1
`

// Used by the CapabilitySweeper request-cascade callback hook.
// Mirrors the existing user_capability_grants query shape.
func (q *Queries) GetGrantsByRequestRef(ctx context.Context, requestRef pgtype.UUID) ([]UserCapabilityGrant, error) {
	rows, err := q.db.Query(ctx, getGrantsByRequestRef, requestRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCapabilityGrant
	for rows.Next() {
		var i UserCapabilityGrant
		if err := rows.Scan(
			&i.UserRef,
			&i.CapabilityCode,
			&i.GrantedAt,
			&i.GrantedByUserRef,
			&i.Note,
			&i.TeamID,
			&i.ExpiresAt,
			&i.RequestRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPostDeleteState = `-- name: GetPostDeleteState :one
SELECT deleted_at, deleted_by_user_ref FROM posts WHERE id = $1
`

type GetPostDeleteStateRow struct {
	DeletedAt        pgtype.Timestamptz
	DeletedByUserRef *int64
}

func (q *Queries) GetPostDeleteState(ctx context.Context, id pgtype.UUID) (GetPostDeleteStateRow, error) {
	row := q.db.QueryRow(ctx, getPostDeleteState, id)
	var i GetPostDeleteStateRow
	err := row.Scan(&i.DeletedAt, &i.DeletedByUserRef)
	return i, err
}

const getResourceRequest = `-- name: GetResourceRequest :one
SELECT id, requester_user_ref, target_id, requested_capability,
       reason, state, decided_at, decided_by_user_ref, decision_reason,
       expires_at, requested_at, target_kind
FROM resource_request
WHERE id = $1
`

// Single-row read by id. Used by the decide handler to load the
// row's `state` before transitioning + by the admin viewer's
// detail page.
func (q *Queries) GetResourceRequest(ctx context.Context, id pgtype.UUID) (ResourceRequest, error) {
	row := q.db.QueryRow(ctx, getResourceRequest, id)
	var i ResourceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserRef,
		&i.TargetID,
		&i.RequestedCapability,
		&i.Reason,
		&i.State,
		&i.DecidedAt,
		&i.DecidedByUserRef,
		&i.DecisionReason,
		&i.ExpiresAt,
		&i.RequestedAt,
		&i.TargetKind,
	)
	return i, err
}

const insertResourceRequest = `-- name: InsertResourceRequest :one

INSERT INTO resource_request
    (requester_user_ref, target_kind, target_id, requested_capability, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, requester_user_ref, target_id, requested_capability,
          reason, state, decided_at, decided_by_user_ref, decision_reason,
          expires_at, requested_at, target_kind
`

type InsertResourceRequestParams struct {
	RequesterUserRef    int64
	TargetKind          string
	TargetID            pgtype.UUID
	RequestedCapability string
	Reason              string
}

// Phase 1.17.E — resource_request queries.
//
// Naming convention: InsertX / GetX / ListX / MarkX
// mirrors the existing auth + users packages.
// Creates a fresh pending request. The state column defaults to
// 'pending' via the schema; we don't pass it explicitly so the
// INSERT can't accidentally bypass the default.
func (q *Queries) InsertResourceRequest(ctx context.Context, arg InsertResourceRequestParams) (ResourceRequest, error) {
	row := q.db.QueryRow(ctx, insertResourceRequest,
		arg.RequesterUserRef,
		arg.TargetKind,
		arg.TargetID,
		arg.RequestedCapability,
		arg.Reason,
	)
	var i ResourceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserRef,
		&i.TargetID,
		&i.RequestedCapability,
		&i.Reason,
		&i.State,
		&i.DecidedAt,
		&i.DecidedByUserRef,
		&i.DecisionReason,
		&i.ExpiresAt,
		&i.RequestedAt,
		&i.TargetKind,
	)
	return i, err
}

const listGlobalCapabilityHolders = `-- name: ListGlobalCapabilityHolders :many
SELECT DISTINCT h.ref
FROM (
    SELECT ur.user_ref AS ref, rc.capability_code AS code
      FROM user_roles ur
      JOIN role_capabilities rc ON rc.role_id = ur.role_id
     WHERE ur.team_id IS NULL
       AND rc.capability_code = ANY($1::text[])
    UNION
    SELECT g.user_ref AS ref, g.capability_code AS code
      FROM user_capability_grants g
     WHERE g.team_id IS NULL
       AND g.capability_code = ANY($1::text[])
       AND (g.expires_at IS NULL OR g.expires_at > NOW())
) h
JOIN "user" u ON u.ref = h.ref AND u.approved = 1
WHERE NOT EXISTS (
    SELECT 1 FROM user_capability_revokes r
     WHERE r.user_ref = h.ref
       AND r.team_id IS NULL
       AND r.capability_code = h.code
)
`

// Notification fan-out for a newly created request (#881): every user
// who could act on it. Resolves a capability the same way
// UserHoldsSystemAdmin does — role grant UNION explicit grant, minus an
// explicit revoke, approved users only — but for a SET of codes and
// returning the holders rather than answering about one of them.
//
// Team-scoped rows are excluded (team_id IS NULL on both sides): the
// approver queue this feeds is the global one, and a team-scoped
// approver has no view of a request that names no team.
//
// The revoke check is per-code, not per-caller: a user revoked
// share.grant but holding system.admin is still an approver, and a
// coarser NOT EXISTS over the whole code set would silently drop them.
//
// This is a NOTIFICATION list, never an authorisation answer. The
// decide gate resolves the caller's own capabilities through auth;
// appearing here confers nothing.
func (q *Queries) ListGlobalCapabilityHolders(ctx context.Context, dollar_1 []string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listGlobalCapabilityHolders, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var ref int64
		if err := rows.Scan(&ref); err != nil {
			return nil, err
		}
		items = append(items, ref)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequests = `-- name: ListPendingRequests :many
SELECT id, requester_user_ref, target_id, requested_capability,
       reason, state, decided_at, decided_by_user_ref, decision_reason,
       expires_at, requested_at, target_kind
FROM resource_request
WHERE state = 'pending'
ORDER BY requested_at ASC
LIMIT $1
OFFSET $2
`

type ListPendingRequestsParams struct {
	Limit  int32
	Offset int32
}

// Approver-facing list (/admin/requests). Oldest pending first so
// nothing rots at the bottom of the queue. The handler filters
// the results by the approver's capability scope before returning
// — this query intentionally surfaces ALL pending so the per-row
// gate is the authoritative filter.
func (q *Queries) ListPendingRequests(ctx context.Context, arg ListPendingRequestsParams) ([]ResourceRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceRequest
	for rows.Next() {
		var i ResourceRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserRef,
			&i.TargetID,
			&i.RequestedCapability,
			&i.Reason,
			&i.State,
			&i.DecidedAt,
			&i.DecidedByUserRef,
			&i.DecisionReason,
			&i.ExpiresAt,
			&i.RequestedAt,
			&i.TargetKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequestsForOwner = `-- name: ListPendingRequestsForOwner :many
SELECT rr.id, rr.requester_user_ref, rr.target_id,
       rr.requested_capability, rr.reason, rr.state, rr.decided_at,
       rr.decided_by_user_ref, rr.decision_reason, rr.expires_at,
       rr.requested_at, rr.target_kind
FROM resource_request rr
JOIN assets a ON a.id = rr.target_id
WHERE rr.state = 'pending'
  AND rr.target_kind = 'asset'
  AND rr.requested_capability <> 'content.restore.request'
  AND a.owner_user_ref = $1
  AND a.deleted_at IS NULL
UNION
SELECT rr.id, rr.requester_user_ref, rr.target_id,
       rr.requested_capability, rr.reason, rr.state, rr.decided_at,
       rr.decided_by_user_ref, rr.decision_reason, rr.expires_at,
       rr.requested_at, rr.target_kind
FROM resource_request rr
JOIN (
    SELECT id, deleted_by_user_ref, 'asset'::TEXT AS kind
      FROM assets WHERE deleted_at IS NOT NULL
    UNION ALL
    SELECT id, deleted_by_user_ref, 'post'::TEXT
      FROM posts WHERE deleted_at IS NOT NULL
    UNION ALL
    SELECT id, deleted_by_user_ref, 'collection'::TEXT
      FROM collections WHERE deleted_at IS NOT NULL
) tgt ON tgt.id = rr.target_id AND tgt.kind = rr.target_kind
WHERE rr.state = 'pending'
  AND rr.requested_capability = 'content.restore.request'
  AND tgt.deleted_by_user_ref = $1
ORDER BY requested_at ASC
LIMIT $2
OFFSET $3
`

type ListPendingRequestsForOwnerParams struct {
	OwnerUserRef *int64
	Limit        int32
	Offset       int32
}

// The non-operator queue (/account/requests/incoming). Pending
// requests THIS caller is the one to decide, without holding any
// capability. Oldest first, same ordering as the approver queue.
//
// TWO disjoint branches, joined on two different facts, because the
// two workflows put the decision in two different people's hands.
//
//  1. #881 — access requests against assets the caller OWNS. Joins
//     assets rather than trusting a denormalised owner column on the
//     request: ownership is the assets table's fact, and #665 exists
//     because a second copy of it drifts. The Go path resolves the
//     same fact through shares.ObjectOwnerRef; both read
//     assets.owner_user_ref. Soft-deleted assets drop out — an owner
//     has no decision to make about access to something they deleted.
//
//  2. #931 — restoration appeals against items the caller DELETED,
//     across all three soft-deletable kinds. Keyed to the DELETER,
//     not the owner, because here the owner is the requester: an
//     owner-keyed appeal queue would hand people their own appeals.
//     The predicate is auth.CanRestoreDeleted's deleter half stated
//     in SQL; the super-admin half is not, because a super-admin
//     reads /admin/requests and this queue is specifically the one
//     you can reach with no capability at all.
//
// The branches cannot overlap — the first requires a live asset, the
// second a soft-deleted target — but this is a UNION rather than a
// UNION ALL so that a future third branch cannot silently double-list
// a row. Branch 1 also excludes the appeal capability outright: an
// appeal must never surface to its own requester as decidable, and
// relying on the liveness conjunct alone to achieve that would make a
// security property depend on a JOIN two lines away.
func (q *Queries) ListPendingRequestsForOwner(ctx context.Context, arg ListPendingRequestsForOwnerParams) ([]ResourceRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRequestsForOwner, arg.OwnerUserRef, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceRequest
	for rows.Next() {
		var i ResourceRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserRef,
			&i.TargetID,
			&i.RequestedCapability,
			&i.Reason,
			&i.State,
			&i.DecidedAt,
			&i.DecidedByUserRef,
			&i.DecisionReason,
			&i.ExpiresAt,
			&i.RequestedAt,
			&i.TargetKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsForRequester = `-- name: ListRequestsForRequester :many
SELECT id, requester_user_ref, target_id, requested_capability,
       reason, state, decided_at, decided_by_user_ref, decision_reason,
       expires_at, requested_at, target_kind
FROM resource_request
WHERE requester_user_ref = $1
ORDER BY requested_at DESC
LIMIT $2
`

type ListRequestsForRequesterParams struct {
	RequesterUserRef int64
	Limit            int32
}

// Requester-facing list (/account/requests). Most-recent first.
// limit is hard-capped at the handler layer (50 default; max 200).
func (q *Queries) ListRequestsForRequester(ctx context.Context, arg ListRequestsForRequesterParams) ([]ResourceRequest, error) {
	rows, err := q.db.Query(ctx, listRequestsForRequester, arg.RequesterUserRef, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceRequest
	for rows.Next() {
		var i ResourceRequest
		if err := rows.Scan(
			&i.ID,
			&i.RequesterUserRef,
			&i.TargetID,
			&i.RequestedCapability,
			&i.Reason,
			&i.State,
			&i.DecidedAt,
			&i.DecidedByUserRef,
			&i.DecisionReason,
			&i.ExpiresAt,
			&i.RequestedAt,
			&i.TargetKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRequestDenied = `-- name: MarkRequestDenied :one
UPDATE resource_request
   SET state = 'denied',
       decided_at = NOW(),
       decided_by_user_ref = $2,
       decision_reason = $3
 WHERE id = $1 AND state = 'pending'
 RETURNING id, requester_user_ref, target_id, requested_capability,
           reason, state, decided_at, decided_by_user_ref, decision_reason,
           expires_at, requested_at, target_kind
`

type MarkRequestDeniedParams struct {
	ID               pgtype.UUID
	DecidedByUserRef *int64
	DecisionReason   string
}

// Symmetric to MarkRequestGranted.
func (q *Queries) MarkRequestDenied(ctx context.Context, arg MarkRequestDeniedParams) (ResourceRequest, error) {
	row := q.db.QueryRow(ctx, markRequestDenied, arg.ID, arg.DecidedByUserRef, arg.DecisionReason)
	var i ResourceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserRef,
		&i.TargetID,
		&i.RequestedCapability,
		&i.Reason,
		&i.State,
		&i.DecidedAt,
		&i.DecidedByUserRef,
		&i.DecisionReason,
		&i.ExpiresAt,
		&i.RequestedAt,
		&i.TargetKind,
	)
	return i, err
}

const markRequestExpired = `-- name: MarkRequestExpired :execrows
UPDATE resource_request
   SET state = 'expired'
 WHERE id = $1 AND state = 'granted'
`

// Called from the CapabilitySweeper request-cascade callback when
// a granted-with-request_ref user_capability_grants row reaps.
// Returns rows-affected so the sweeper logs "we expired N
// requests" — and gracefully handles the race where a sweep
// competes with a manual operator action.
func (q *Queries) MarkRequestExpired(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markRequestExpired, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRequestGranted = `-- name: MarkRequestGranted :one
UPDATE resource_request
   SET state = 'granted',
       decided_at = NOW(),
       decided_by_user_ref = $2,
       decision_reason = $3,
       expires_at = $4
 WHERE id = $1 AND state = 'pending'
 RETURNING id, requester_user_ref, target_id, requested_capability,
           reason, state, decided_at, decided_by_user_ref, decision_reason,
           expires_at, requested_at, target_kind
`

type MarkRequestGrantedParams struct {
	ID               pgtype.UUID
	DecidedByUserRef *int64
	DecisionReason   string
	ExpiresAt        pgtype.Timestamptz
}

// Atomic CAS: only transitions pending → granted. Returns the
// updated row so the handler can build the audit changeset
// (1.17.D RecordChange) + the notification payload from a single
// query. Returns no rows when the request was already decided —
// the handler maps that to a 409.
func (q *Queries) MarkRequestGranted(ctx context.Context, arg MarkRequestGrantedParams) (ResourceRequest, error) {
	row := q.db.QueryRow(ctx, markRequestGranted,
		arg.ID,
		arg.DecidedByUserRef,
		arg.DecisionReason,
		arg.ExpiresAt,
	)
	var i ResourceRequest
	err := row.Scan(
		&i.ID,
		&i.RequesterUserRef,
		&i.TargetID,
		&i.RequestedCapability,
		&i.Reason,
		&i.State,
		&i.DecidedAt,
		&i.DecidedByUserRef,
		&i.DecisionReason,
		&i.ExpiresAt,
		&i.RequestedAt,
		&i.TargetKind,
	)
	return i, err
}
