// Package licensing implements the artist-alley-side verifier for
// licenses issued by the artist-alley-license-server. Offline-first:
// every verification step (signature, expiry, chain walk) runs
// against the embedded PublicKeys catalog (see pubkeys.gen.go) with
// no network calls.
//
// The wire format is defined by the license server's TypeScript
// implementation; the canonical-JSON-signed contract is shared via
// the tests in this package — if those pass, signatures generated by
// the Worker verify cleanly here.
//
// Layout:
//
//	claims.go      LicenseClaims struct (mirrors server-side TypeScript)
//	canonical.go   canonical JSON bytes for signature verification
//	envelope.go    text envelope parser (-----BEGIN ARTIST-ALLEY LICENSE-----)
//	verifier.go    Ed25519 verify + temporal + iss checks
//	state.go       in-memory cached state + file loader
//	features.go    feature-flag helpers (HasFeature, Tier, IsEnabled, etc.)
//	pubkeys.gen.go embedded root pubkeys catalog (regenerate via
//	                 the license server's `emit-go-pubkeys` script)
//	handler.go     openapi-strict handler for GET /license/status
//
// Community mode (no license file installed) is the artist-alley
// app's DEFAULT — features are present, capacity is capped at the
// community defaults. The verifier returns a synthesized "community"
// LicenseStatus when no .lic file is present so callers (handlers,
// capability checks) treat it uniformly.

package licensing

// LicenseClaims is the typed shape of the JSON object signed by the
// license server. Field names + types MUST match the TypeScript
// LicenseClaims interface in artist-alley-license-server/src/models/
// claims.ts — those two definitions are the wire contract; tests
// pin the canonical-JSON byte equivalence.
type LicenseClaims struct {
	V              int      `json:"v"`
	KID            string   `json:"kid"`
	LID            string   `json:"lid"`
	Product        string   `json:"prod"`
	Tier           string   `json:"tier"`
	Seats          *int64   `json:"seats"`            // nil = unlimited
	SeatWindowDays int      `json:"seat_window_days"` // rolling window for "active seat" counting
	AssetCap       *int64   `json:"asset_cap"`        // nil = unlimited
	Owner          string   `json:"owner"`
	Org            string   `json:"org"`
	NotBefore      int64    `json:"nbf"` // Unix epoch seconds
	Expires        int64    `json:"exp"`
	IssuedAt       int64    `json:"iat"`
	Features       []string `json:"features"`

	// Optional Layer-1 cross-binding fields. Both may be nil for
	// community/trial/dev licenses where activation overhead would
	// add friction. When set, enforced by the verifier (org_pubkey
	// requires a matching org.key file; bound_domains optionally
	// constrain runtime hostname).
	HostFingerprint *string  `json:"host_fp"`
	OrgPubkey       *string  `json:"org_pubkey"`
	BoundDomains    []string `json:"bound_domains"`

	Issuer string `json:"iss"`
}

// PluginLicenseClaims is the typed shape of plugin-license claims
// signed by a publisher's private key. Walks the chain via an
// embedded publisher cert (signed by us).
type PluginLicenseClaims struct {
	V             int      `json:"v"`
	PublisherKID  string   `json:"publisher_kid"`
	PublisherSlug string   `json:"publisher_slug"`
	LID           string   `json:"lid"`
	Product       string   `json:"prod"`
	Tier          string   `json:"tier"`
	Owner         string   `json:"owner"`
	Org           string   `json:"org"`
	NotBefore     int64    `json:"nbf"`
	Expires       int64    `json:"exp"`
	IssuedAt      int64    `json:"iat"`
	Features      []string `json:"features"`
	OrgPubkey     *string  `json:"org_pubkey"`
}

// PublisherCertClaims is the typed shape of a publisher certificate
// signed by our root key. Bundled into plugin license envelopes to
// establish the chain of trust.
type PublisherCertClaims struct {
	V                  int      `json:"v"`
	CertID             string   `json:"cert_id"`
	SignedByKID        string   `json:"signed_by_kid"`
	PublisherSlug      string   `json:"publisher_slug"`
	PublisherKID       string   `json:"publisher_kid"`
	PublisherPubkeyB64 string   `json:"publisher_pubkey_b64"`
	DisplayName        string   `json:"display_name"`
	AllowedProducts    []string `json:"allowed_products"`
	NotBefore          int64    `json:"nbf"`
	Expires            int64    `json:"exp"`
	IssuedAt           int64    `json:"iat"`
	Issuer             string   `json:"iss"`
}
