// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package workflow

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findTransition = `-- name: FindTransition :one
SELECT id, from_state_id, to_state_id, required_capability, requires_team_scope
FROM workflow_transitions
WHERE from_state_id IS NOT DISTINCT FROM $1
  AND to_state_id = $2
`

type FindTransitionParams struct {
	FromStateID pgtype.UUID
	ToStateID   pgtype.UUID
}

// Looks up the exact transition row for a (from, to) pair. Both
// params are pgtype.UUID; pass an invalid (Valid=false) UUID for
// from when checking the "initial entry" transition (from is NULL
// in the row).
//
// NB: $1 IS NULL OR f.from_state_id = $1 covers both shapes because
// the param's NULL-ness flips the first clause; sqlc-pgx renders
// pgtype.UUID with Valid=false as NULL on the wire.
func (q *Queries) FindTransition(ctx context.Context, arg FindTransitionParams) (WorkflowTransition, error) {
	row := q.db.QueryRow(ctx, findTransition, arg.FromStateID, arg.ToStateID)
	var i WorkflowTransition
	err := row.Scan(
		&i.ID,
		&i.FromStateID,
		&i.ToStateID,
		&i.RequiredCapability,
		&i.RequiresTeamScope,
	)
	return i, err
}

const getAssetState = `-- name: GetAssetState :one
SELECT state_id, team_id
FROM assets
WHERE id = $1 AND deleted_at IS NULL
`

type GetAssetStateRow struct {
	StateID pgtype.UUID
	TeamID  pgtype.UUID
}

func (q *Queries) GetAssetState(ctx context.Context, id pgtype.UUID) (GetAssetStateRow, error) {
	row := q.db.QueryRow(ctx, getAssetState, id)
	var i GetAssetStateRow
	err := row.Scan(&i.StateID, &i.TeamID)
	return i, err
}

const getInitialState = `-- name: GetInitialState :one
SELECT id, domain, code, label, sort_order, is_initial, is_terminal,
       visible_by_default, icon, color, requires_note
FROM workflow_states
WHERE domain = $1 AND is_initial = TRUE
LIMIT 1
`

type GetInitialStateRow struct {
	ID               pgtype.UUID
	Domain           string
	Code             string
	Label            string
	SortOrder        int32
	IsInitial        bool
	IsTerminal       bool
	VisibleByDefault bool
	Icon             string
	Color            string
	RequiresNote     bool
}

// The single is_initial row for the domain. Used at resource creation
// time to populate state_id with the correct entry point. Partial
// unique index guarantees at most one row.
func (q *Queries) GetInitialState(ctx context.Context, domain string) (GetInitialStateRow, error) {
	row := q.db.QueryRow(ctx, getInitialState, domain)
	var i GetInitialStateRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Code,
		&i.Label,
		&i.SortOrder,
		&i.IsInitial,
		&i.IsTerminal,
		&i.VisibleByDefault,
		&i.Icon,
		&i.Color,
		&i.RequiresNote,
	)
	return i, err
}

const getPostState = `-- name: GetPostState :one
SELECT state_id, team_id
FROM posts
WHERE id = $1 AND deleted_at IS NULL
`

type GetPostStateRow struct {
	StateID pgtype.UUID
	TeamID  pgtype.UUID
}

// Returns the post's current state_id and team_id together (both nullable).
// One round-trip for the Transition() pre-check.
func (q *Queries) GetPostState(ctx context.Context, id pgtype.UUID) (GetPostStateRow, error) {
	row := q.db.QueryRow(ctx, getPostState, id)
	var i GetPostStateRow
	err := row.Scan(&i.StateID, &i.TeamID)
	return i, err
}

const getState = `-- name: GetState :one

SELECT id, domain, code, label, sort_order, is_initial, is_terminal,
       visible_by_default, icon, color, requires_note
FROM workflow_states
WHERE id = $1
`

type GetStateRow struct {
	ID               pgtype.UUID
	Domain           string
	Code             string
	Label            string
	SortOrder        int32
	IsInitial        bool
	IsTerminal       bool
	VisibleByDefault bool
	Icon             string
	Color            string
	RequiresNote     bool
}

// Workflow state machine queries. Owned by app/internal/workflow.
// See migration 00018 and docs/adr/0010-permissions-teams-workflow.md.
func (q *Queries) GetState(ctx context.Context, id pgtype.UUID) (GetStateRow, error) {
	row := q.db.QueryRow(ctx, getState, id)
	var i GetStateRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Code,
		&i.Label,
		&i.SortOrder,
		&i.IsInitial,
		&i.IsTerminal,
		&i.VisibleByDefault,
		&i.Icon,
		&i.Color,
		&i.RequiresNote,
	)
	return i, err
}

const getStateByCode = `-- name: GetStateByCode :one
SELECT id, domain, code, label, sort_order, is_initial, is_terminal,
       visible_by_default, icon, color, requires_note
FROM workflow_states
WHERE domain = $1 AND code = $2
`

type GetStateByCodeParams struct {
	Domain string
	Code   string
}

type GetStateByCodeRow struct {
	ID               pgtype.UUID
	Domain           string
	Code             string
	Label            string
	SortOrder        int32
	IsInitial        bool
	IsTerminal       bool
	VisibleByDefault bool
	Icon             string
	Color            string
	RequiresNote     bool
}

func (q *Queries) GetStateByCode(ctx context.Context, arg GetStateByCodeParams) (GetStateByCodeRow, error) {
	row := q.db.QueryRow(ctx, getStateByCode, arg.Domain, arg.Code)
	var i GetStateByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Code,
		&i.Label,
		&i.SortOrder,
		&i.IsInitial,
		&i.IsTerminal,
		&i.VisibleByDefault,
		&i.Icon,
		&i.Color,
		&i.RequiresNote,
	)
	return i, err
}

const insertWorkflowAudit = `-- name: InsertWorkflowAudit :exec
INSERT INTO workflow_audit (
    resource_kind, resource_id, from_state_id, to_state_id, actor_user_ref, note
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertWorkflowAuditParams struct {
	ResourceKind string
	ResourceID   pgtype.UUID
	FromStateID  pgtype.UUID
	ToStateID    pgtype.UUID
	ActorUserRef *int64
	Note         string
}

func (q *Queries) InsertWorkflowAudit(ctx context.Context, arg InsertWorkflowAuditParams) error {
	_, err := q.db.Exec(ctx, insertWorkflowAudit,
		arg.ResourceKind,
		arg.ResourceID,
		arg.FromStateID,
		arg.ToStateID,
		arg.ActorUserRef,
		arg.Note,
	)
	return err
}

const listStatesForDomain = `-- name: ListStatesForDomain :many
SELECT id, domain, code, label, sort_order, is_initial, is_terminal,
       visible_by_default, icon, color, requires_note
FROM workflow_states
WHERE domain = $1
ORDER BY sort_order, code
`

type ListStatesForDomainRow struct {
	ID               pgtype.UUID
	Domain           string
	Code             string
	Label            string
	SortOrder        int32
	IsInitial        bool
	IsTerminal       bool
	VisibleByDefault bool
	Icon             string
	Color            string
	RequiresNote     bool
}

func (q *Queries) ListStatesForDomain(ctx context.Context, domain string) ([]ListStatesForDomainRow, error) {
	rows, err := q.db.Query(ctx, listStatesForDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatesForDomainRow
	for rows.Next() {
		var i ListStatesForDomainRow
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Code,
			&i.Label,
			&i.SortOrder,
			&i.IsInitial,
			&i.IsTerminal,
			&i.VisibleByDefault,
			&i.Icon,
			&i.Color,
			&i.RequiresNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitionsForDomain = `-- name: ListTransitionsForDomain :many
SELECT t.id, t.from_state_id, t.to_state_id, t.required_capability, t.requires_team_scope
FROM workflow_transitions t
LEFT JOIN workflow_states fs ON fs.id = t.from_state_id
JOIN workflow_states ts ON ts.id = t.to_state_id
WHERE ts.domain = $1 AND (t.from_state_id IS NULL OR fs.domain = $1)
`

// Returns every transition where the from-state OR to-state is in the
// given domain. Includes the NULL-from "initial entry" rows for the
// domain's initial state. Used for the workflow editor UI.
func (q *Queries) ListTransitionsForDomain(ctx context.Context, domain string) ([]WorkflowTransition, error) {
	rows, err := q.db.Query(ctx, listTransitionsForDomain, domain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkflowTransition
	for rows.Next() {
		var i WorkflowTransition
		if err := rows.Scan(
			&i.ID,
			&i.FromStateID,
			&i.ToStateID,
			&i.RequiredCapability,
			&i.RequiresTeamScope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowAudit = `-- name: ListWorkflowAudit :many
SELECT a.id, a.resource_kind, a.resource_id,
       a.from_state_id, a.to_state_id,
       a.actor_user_ref, a.note, a.transitioned_at,
       fs.code AS from_code, ts.code AS to_code
FROM workflow_audit a
LEFT JOIN workflow_states fs ON fs.id = a.from_state_id
JOIN workflow_states ts ON ts.id = a.to_state_id
WHERE a.resource_kind = $1 AND a.resource_id = $2
ORDER BY a.transitioned_at DESC
LIMIT $3 OFFSET $4
`

type ListWorkflowAuditParams struct {
	ResourceKind string
	ResourceID   pgtype.UUID
	Limit        int32
	Offset       int32
}

type ListWorkflowAuditRow struct {
	ID             pgtype.UUID
	ResourceKind   string
	ResourceID     pgtype.UUID
	FromStateID    pgtype.UUID
	ToStateID      pgtype.UUID
	ActorUserRef   *int64
	Note           string
	TransitionedAt pgtype.Timestamptz
	FromCode       *string
	ToCode         string
}

// Audit history for a single resource, newest first.
func (q *Queries) ListWorkflowAudit(ctx context.Context, arg ListWorkflowAuditParams) ([]ListWorkflowAuditRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowAudit,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkflowAuditRow
	for rows.Next() {
		var i ListWorkflowAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceKind,
			&i.ResourceID,
			&i.FromStateID,
			&i.ToStateID,
			&i.ActorUserRef,
			&i.Note,
			&i.TransitionedAt,
			&i.FromCode,
			&i.ToCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetState = `-- name: UpdateAssetState :execrows
UPDATE assets
   SET state_id = $2, updated_at = NOW()
 WHERE id = $1 AND deleted_at IS NULL
`

type UpdateAssetStateParams struct {
	ID      pgtype.UUID
	StateID pgtype.UUID
}

func (q *Queries) UpdateAssetState(ctx context.Context, arg UpdateAssetStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAssetState, arg.ID, arg.StateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePostState = `-- name: UpdatePostState :execrows
UPDATE posts
   SET state_id = $2, updated_at = NOW()
 WHERE id = $1 AND deleted_at IS NULL
`

type UpdatePostStateParams struct {
	ID      pgtype.UUID
	StateID pgtype.UUID
}

// Sets the post's state_id. Returns the row count so callers can
// distinguish "no such post / already deleted" from a real update.
func (q *Queries) UpdatePostState(ctx context.Context, arg UpdatePostStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePostState, arg.ID, arg.StateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
