// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 Kenneth Blossom

// Package config loads runtime configuration from environment variables.
//
// All artist-alley configuration is exposed via env vars (12-factor style).
// Defaults are baked in so the binary boots in a sane state without any env
// set; anything sensitive must be provided explicitly.
package config

import (
	"errors"
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

// Config holds every knob the app reads. Add a field here when you need a
// new env var; do not call [os.Getenv] from elsewhere in the codebase.
type Config struct {
	// HTTP listener.
	HTTPAddr string

	// PostgreSQL connection.
	DBHost     string
	DBPort     int
	DBUser     string
	DBPassword string
	DBName     string
	DBSSLMode  string // disable / require / verify-full

	// Pool tuning.
	DBMaxConns        int32
	DBMinConns        int32
	DBConnMaxLifetime time.Duration

	// Logging.
	LogLevel  string // debug / info / warn / error
	LogFormat string // json (default) or text

	// Auth — must match the PHP side exactly during the transition
	// since both worlds hash passwords with the same pepper. Pulled
	// from the same config value the legacy PHP reads as $scramble_key.
	ScrambleKey string

	// First-boot bootstrap. The bootstrap package runs on every
	// startup; it's a no-op when admins exist already. AdminPath
	// is where bootstrap-admin.txt gets written in secure mode
	// (random password); empty defaults to /var/lib/artist-alley.
	// DefaultAdminEnabled mirrors AA_BOOTSTRAP_DEFAULT_ADMIN=1 —
	// when set, the documented literal admin/ArtistAlleyMogul is
	// used instead of a random password + a loud WARN banner is
	// printed. DEVELOPMENT ONLY.
	BootstrapAdminPath     string
	BootstrapDefaultAdmin  bool

	// Storage. Backend selects which storage.Backend implementation
	// the app constructs at boot. The other fields are backend-specific
	// — only the ones for the selected backend need to be set.
	StorageBackend         string // "fs" | "s3" | ...
	StorageFSRoot          string // "fs": absolute path to the storage root
	StorageS3Endpoint      string // "s3": e.g., http://minio:9000 (AWS endpoint when empty)
	StorageS3Region        string // "s3": e.g., us-east-1
	StorageS3Bucket        string // "s3": bucket name
	StorageS3AccessKey     string // "s3"
	StorageS3SecretKey     string // "s3"
	StorageS3UsePathStyle  bool   // "s3": true for MinIO and similar

	// License file path (Phase 1.17.O). When empty or the file
	// doesn't exist, the licensing package falls into "community
	// mode" — the app runs with the built-in community defaults,
	// no license server is contacted. Set to install a paid
	// license.
	LicensePath string

	// org.key path (Phase 1.17.O-3). Customer-side Ed25519 private
	// seed used for Layer-1 license cross-binding. Generated by the
	// license server's `customer-activation.ts` script; the public
	// half is embedded in the .lic as `org_pubkey`. When the loaded
	// license declares an org_pubkey, the verifier reads this file at
	// boot + on every license upload to confirm the install holds the
	// matching private key. Defeats license sharing — a stolen .lic
	// is useless without the org.key it was issued against.
	//
	// Empty disables cross-binding entirely (community / dev). When
	// set, missing file or pubkey mismatch fails the verifier closed.
	OrgKeyPath string

	// DemoMode mirrors AA_DEMO_MODE=1. When set, the public boot
	// payload advertises the shared demo credentials on the login
	// card and renders a "read-only demo" banner once signed in.
	// Purely presentational — write-blocking for the demo deployment
	// is enforced at the edge (nginx), not here. Off = zero footprint.
	DemoMode bool

	// Setup-wizard prefills. Pre-populating these via env makes it
	// possible to script a deployment (Helm chart, Terraform, CI
	// install test) without anyone typing into the browser form. None
	// of them affect runtime behaviour after setup completes — once
	// the admin clicks submit, the values live in system_config.
	SetupDefaults SetupDefaults
}

// SetupDefaults groups every AA_SETUP_DEFAULT_* env value the setup
// wizard prefills its form from. Empty fields just mean "no default —
// the admin must type one in".
type SetupDefaults struct {
	AdminUsername  string
	AdminEmail     string
	AdminFullname  string
	SiteName       string
	SiteBaseURL    string
	SMTPHost       string
	SMTPPort       int
	SMTPEncryption string // none | starttls | tls
	SMTPUsername   string
	SMTPFromAddr   string
}

// Load reads the environment into a Config, applying defaults and
// reporting an error if anything required is missing.
func Load() (Config, error) {
	c := Config{
		HTTPAddr:          envStr("AA_HTTP_ADDR", ":8080"),
		DBHost:            envStr("AA_DB_HOST", "postgres"),
		DBPort:            envInt("AA_DB_PORT", 5432),
		DBUser:            envStr("AA_DB_USER", "artist_alley"),
		DBPassword:        envStr("AA_DB_PASSWORD", ""),
		DBName:            envStr("AA_DB_NAME", "artist_alley"),
		DBSSLMode:         envStr("AA_DB_SSLMODE", "disable"),
		DBMaxConns:        int32(envInt("AA_DB_MAX_CONNS", 20)),
		DBMinConns:        int32(envInt("AA_DB_MIN_CONNS", 2)),
		DBConnMaxLifetime: envDuration("AA_DB_CONN_MAX_LIFETIME", time.Hour),
		LogLevel:          envStr("AA_LOG_LEVEL", "info"),
		LogFormat:         envStr("AA_LOG_FORMAT", "json"),
		ScrambleKey:       envStr("AA_SCRAMBLE_KEY", ""),

		BootstrapAdminPath:    envStr("AA_BOOTSTRAP_ADMIN_PATH", "/var/lib/artist-alley"),
		BootstrapDefaultAdmin: envBool("AA_BOOTSTRAP_DEFAULT_ADMIN", false),

		DemoMode: envBool("AA_DEMO_MODE", false),

		StorageBackend:        envStr("AA_STORAGE_BACKEND", "fs"),
		StorageFSRoot:         envStr("AA_STORAGE_FS_ROOT", "/var/lib/artist-alley/storage"),
		StorageS3Endpoint:     envStr("AA_STORAGE_S3_ENDPOINT", ""),
		StorageS3Region:       envStr("AA_STORAGE_S3_REGION", "us-east-1"),
		StorageS3Bucket:       envStr("AA_STORAGE_S3_BUCKET", ""),
		StorageS3AccessKey:    envStr("AA_STORAGE_S3_ACCESS_KEY", ""),
		StorageS3SecretKey:    envStr("AA_STORAGE_S3_SECRET_KEY", ""),
		StorageS3UsePathStyle: envBool("AA_STORAGE_S3_USE_PATH_STYLE", true),
		LicensePath:           envStr("AA_LICENSE_PATH", "/etc/artist-alley/license.lic"),
		OrgKeyPath:            envStr("AA_ORG_KEY_PATH", "/etc/artist-alley/org.key"),
		SetupDefaults: SetupDefaults{
			AdminUsername:  envStr("AA_SETUP_DEFAULT_USERNAME", ""),
			AdminEmail:     envStr("AA_SETUP_DEFAULT_EMAIL", ""),
			AdminFullname: envStr("AA_SETUP_DEFAULT_FULLNAME", ""),
			SiteName:       envStr("AA_SETUP_DEFAULT_SITE_NAME", "Artist Alley"),
			SiteBaseURL:    envStr("AA_SETUP_DEFAULT_BASE_URL", ""),
			SMTPHost:       envStr("AA_SETUP_DEFAULT_SMTP_HOST", ""),
			SMTPPort:       envInt("AA_SETUP_DEFAULT_SMTP_PORT", 587),
			SMTPEncryption: envStr("AA_SETUP_DEFAULT_SMTP_ENCRYPTION", "starttls"),
			SMTPUsername:   envStr("AA_SETUP_DEFAULT_SMTP_USERNAME", ""),
			SMTPFromAddr:   envStr("AA_SETUP_DEFAULT_SMTP_FROM", ""),
		},
	}

	if c.DBPassword == "" {
		return c, errors.New("config: AA_DB_PASSWORD is required")
	}
	if c.ScrambleKey == "" {
		return c, errors.New("config: AA_SCRAMBLE_KEY is required (must match the legacy $scramble_key)")
	}
	return c, nil
}

func envStr(key, def string) string {
	if v, ok := os.LookupEnv(key); ok {
		return v
	}
	return def
}

func envBool(key string, def bool) bool {
	v, ok := os.LookupEnv(key)
	if !ok || v == "" {
		return def
	}
	switch strings.ToLower(v) {
	case "1", "true", "yes", "y", "on":
		return true
	case "0", "false", "no", "n", "off":
		return false
	default:
		panic(fmt.Sprintf("config: %s=%q is not a valid bool", key, v))
	}
}

func envInt(key string, def int) int {
	v, ok := os.LookupEnv(key)
	if !ok || v == "" {
		return def
	}
	n, err := strconv.Atoi(v)
	if err != nil {
		panic(fmt.Sprintf("config: %s=%q is not a valid int", key, v))
	}
	return n
}

func envDuration(key string, def time.Duration) time.Duration {
	v, ok := os.LookupEnv(key)
	if !ok || v == "" {
		return def
	}
	d, err := time.ParseDuration(v)
	if err != nil {
		panic(fmt.Sprintf("config: %s=%q is not a valid duration", key, v))
	}
	return d
}
