#!/usr/bin/env bash
# Regenerate app/internal/openapi/strictservershim/panicshim_gen.go.
#
# Reads app/internal/openapi/openapi.gen.go (the oapi-codegen
# output) + emits a PanicShim struct with one panic-stub method
# per StrictServerInterface method. Lets tests embed *PanicShim
# and override only the methods their fixture actually exercises
# — historically these stubs were duplicated across 7 per-domain
# test files (~1,200 lines).
#
# Wired from scripts/generate.sh so it stays in sync with every
# openapi.yaml change.

set -euo pipefail

SRC="${1:-app/internal/openapi/openapi.gen.go}"
OUT="${2:-app/internal/openapi/strictservershim/panicshim_gen.go}"

if [[ ! -f "$SRC" ]]; then
    echo "gen-panicshim: source $SRC not found" >&2
    exit 1
fi

# Extract the body of StrictServerInterface — every method line
# inside the `type StrictServerInterface interface { ... }` block.
# awk emits one "MethodName RequestObject ResponseObject" per line.
methods=$(awk '
    /^type StrictServerInterface interface \{/ { inblock = 1; next }
    inblock && /^\}/ { exit }
    inblock && /^	[A-Z][a-zA-Z0-9]+\(ctx context.Context, request [A-Z][a-zA-Z0-9]+RequestObject\) \([A-Z][a-zA-Z0-9]+ResponseObject, error\)/ {
        match($0, /^	([A-Z][a-zA-Z0-9]+)\(ctx context.Context, request ([A-Z][a-zA-Z0-9]+RequestObject)\) \(([A-Z][a-zA-Z0-9]+ResponseObject), error\)/, m)
        print m[1] " " m[2] " " m[3]
    }
' "$SRC")

if [[ -z "$methods" ]]; then
    echo "gen-panicshim: no StrictServerInterface methods found in $SRC" >&2
    exit 1
fi

count=$(echo "$methods" | wc -l)

{
    cat <<'EOF'
// Code generated by scripts/gen-panicshim.sh — DO NOT EDIT.
//
// Re-run after every openapi.yaml change. The generator reads
// app/internal/openapi/openapi.gen.go to enumerate the
// StrictServerInterface methods, so it stays in sync with the
// spec automatically.

package strictservershim

import (
	"context"

	"github.com/mscrnt/artist-alley/app/internal/openapi"
)

// PanicShim is a zero-value default implementation of
// openapi.StrictServerInterface where every method panics with a
// "PanicShim: X called without override" message. Embed
// *PanicShim in a test shim and override only the methods that
// test exercises — Go method resolution will route covered
// methods to the override and unhandled methods through the
// embedded panic stub.
//
// Construct with &PanicShim{} (no fields to set).
type PanicShim struct{}

// Compile-time interface guard: if a future openapi method gets
// added without a corresponding generated stub here, this line
// fails to compile and the test compile fails loudly. Run
// ./scripts/generate.sh to regen.
var _ openapi.StrictServerInterface = (*PanicShim)(nil)

EOF
    echo "$methods" | while read -r name req resp; do
        printf '// %s panics by default; test shims override.\nfunc (*PanicShim) %s(context.Context, openapi.%s) (openapi.%s, error) {\n\tpanic("PanicShim: %s called without override in test fixture (embed *strictservershim.PanicShim and override this method)")\n}\n\n' \
            "$name" "$name" "$req" "$resp" "$name"
    done
} > "$OUT"

# gofmt for tidy output (idempotent — generator output should
# already be well-formed).
if command -v gofmt >/dev/null 2>&1; then
    gofmt -w "$OUT"
fi

echo "gen-panicshim: wrote $count panic stubs to $OUT"
