// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package posts

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCollectionPost = `-- name: AddCollectionPost :exec

INSERT INTO collection_posts (
    collection_id, post_id, sort_order, pinned, expires_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (collection_id, post_id) DO UPDATE SET
    sort_order = EXCLUDED.sort_order,
    pinned     = EXCLUDED.pinned,
    expires_at = EXCLUDED.expires_at
`

type AddCollectionPostParams struct {
	CollectionID pgtype.UUID
	PostID       pgtype.UUID
	SortOrder    int32
	Pinned       bool
	ExpiresAt    pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// collection_posts
// ---------------------------------------------------------------------------
// Idempotent on (collection_id, post_id). Re-adding updates
// sort_order/pinned/expires_at; added_at stays fixed.
func (q *Queries) AddCollectionPost(ctx context.Context, arg AddCollectionPostParams) error {
	_, err := q.db.Exec(ctx, addCollectionPost,
		arg.CollectionID,
		arg.PostID,
		arg.SortOrder,
		arg.Pinned,
		arg.ExpiresAt,
	)
	return err
}

const addPostAcl = `-- name: AddPostAcl :exec
INSERT INTO post_acls (post_id, principal_type, principal_id, permission,
                       granted_by_user_ref, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (post_id, principal_type, principal_id, permission) DO UPDATE SET
    granted_at            = NOW(),
    granted_by_user_ref = EXCLUDED.granted_by_user_ref,
    expires_at            = EXCLUDED.expires_at
`

type AddPostAclParams struct {
	PostID           pgtype.UUID
	PrincipalType    string
	PrincipalID      string
	Permission       string
	GrantedByUserRef *int64
	ExpiresAt        pgtype.Timestamptz
}

// Idempotent on the full (post, principal, permission) PK. Adding the
// same row twice is a no-op (returns 204 the second time).
func (q *Queries) AddPostAcl(ctx context.Context, arg AddPostAclParams) error {
	_, err := q.db.Exec(ctx, addPostAcl,
		arg.PostID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
		arg.GrantedByUserRef,
		arg.ExpiresAt,
	)
	return err
}

const addPostAsset = `-- name: AddPostAsset :exec


INSERT INTO post_assets (post_id, asset_id, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (post_id, asset_id) DO UPDATE SET
    sort_order = EXCLUDED.sort_order
`

type AddPostAssetParams struct {
	PostID    pgtype.UUID
	AssetID   pgtype.UUID
	SortOrder int32
}

// The two post LIST queries (ListPostsPage, ListPostsByAsset) are NOT
// here. They live in list_page.go as hand-built SQL, because the read
// rule they must apply is a runtime fragment (readRuleSQL) and a sqlc
// query is a static string — the same reason every splice site of
// visibility.Predicate is hand-built.
//
// They were deleted from this file rather than left in place unused
// (#660). The version that lived here took a caller-supplied
// `visibility` and applied it as a bare equality, documented as "NULL
// for whatever the caller is authorised to see (handler enforces)" —
// and the handler did not enforce, so `?visibility=private` returned
// every author's private posts to any signed-in caller. A second,
// ungated expression of "which posts does this list return" is exactly
// what produced that bug; leaving one here for the next caller to pick
// up would rebuild it.
// ---------------------------------------------------------------------------
// post_assets (members)
// ---------------------------------------------------------------------------
// Idempotent on PK. Re-adding bumps sort_order; added_at stays fixed.
func (q *Queries) AddPostAsset(ctx context.Context, arg AddPostAssetParams) error {
	_, err := q.db.Exec(ctx, addPostAsset, arg.PostID, arg.AssetID, arg.SortOrder)
	return err
}

const addPostTag = `-- name: AddPostTag :exec
INSERT INTO post_tags (post_id, tag)
VALUES ($1, $2)
ON CONFLICT (post_id, tag) DO NOTHING
`

type AddPostTagParams struct {
	PostID pgtype.UUID
	Tag    string
}

func (q *Queries) AddPostTag(ctx context.Context, arg AddPostTagParams) error {
	_, err := q.db.Exec(ctx, addPostTag, arg.PostID, arg.Tag)
	return err
}

const countLivePostsForAsset = `-- name: CountLivePostsForAsset :one
SELECT COUNT(*)::BIGINT AS value
FROM posts p
WHERE p.deleted_at IS NULL
  AND EXISTS (SELECT 1 FROM post_assets pa
                WHERE pa.post_id = p.id AND pa.asset_id = $1)
`

// How many live posts contain this asset, with NO read rule applied.
//
// The raw total is half of decision 5's disclosure: the handler
// subtracts the posts the caller may actually read and reports the
// remainder as `withheld_count`. It is deliberately a COUNT and not a
// list — see the operation's description for why an id, a title or a
// cursor over the same set would undo the whole point.
func (q *Queries) CountLivePostsForAsset(ctx context.Context, assetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countLivePostsForAsset, assetID)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const createPost = `-- name: CreatePost :one

INSERT INTO posts (
    author_user_ref, title, description, visibility, cover_asset_id,
    cover_thumbnail_asset_id, team_id, state_id, cover_focal_x, cover_focal_y
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, author_user_ref, title, description, visibility, cover_asset_id,
          cover_thumbnail_asset_id, cover_focal_x, cover_focal_y,
          posted_at, like_count, comment_count,
          origin_server_id, team_id, state_id, created_at, updated_at
`

type CreatePostParams struct {
	AuthorUserRef         int64
	Title                 string
	Description           string
	Visibility            string
	CoverAssetID          pgtype.UUID
	CoverThumbnailAssetID pgtype.UUID
	TeamID                pgtype.UUID
	StateID               pgtype.UUID
	CoverFocalX           *float64
	CoverFocalY           *float64
}

type CreatePostRow struct {
	ID                    pgtype.UUID
	AuthorUserRef         int64
	Title                 string
	Description           string
	Visibility            string
	CoverAssetID          pgtype.UUID
	CoverThumbnailAssetID pgtype.UUID
	CoverFocalX           *float64
	CoverFocalY           *float64
	PostedAt              pgtype.Timestamptz
	LikeCount             int64
	CommentCount          int64
	OriginServerID        pgtype.UUID
	TeamID                pgtype.UUID
	StateID               pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// posts (the entity)
// ---------------------------------------------------------------------------
// posted_at defaults to NOW() via the column default. team_id is
// optional (NULL = un-scoped post; scoped post visibility is gated by
// the post's team_id and the caller's scoped caps — see ADR 0010 L5).
// cover_thumbnail_asset_id is an optional standalone thumbnail (not
// a post member) used by the upload modal's "use a different image
// as the cover" UX. state_id is the workflow state in the 'post'
// domain — NULL means no workflow tracking.
// cover_focal_x / cover_focal_y are the crop the author framed for the
// browse grid's square tile (#1210), as fractions of the ORIGINAL
// picture. Both NULL means centred, which is what every post rendered
// before the columns existed; the column CHECK refuses half a pair.
func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorUserRef,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.CoverAssetID,
		arg.CoverThumbnailAssetID,
		arg.TeamID,
		arg.StateID,
		arg.CoverFocalX,
		arg.CoverFocalY,
	)
	var i CreatePostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorUserRef,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.CoverAssetID,
		&i.CoverThumbnailAssetID,
		&i.CoverFocalX,
		&i.CoverFocalY,
		&i.PostedAt,
		&i.LikeCount,
		&i.CommentCount,
		&i.OriginServerID,
		&i.TeamID,
		&i.StateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetOwnerRef = `-- name: GetAssetOwnerRef :one
SELECT owner_user_ref FROM assets WHERE id = $1 AND deleted_at IS NULL
`

// The asset's owner, for the ownership gate on GET /assets/{id}/posts
// (ADR 0091 decision 5). Soft-deleted assets answer no rows: a deleted
// file has no "where does it appear" to report.
func (q *Queries) GetAssetOwnerRef(ctx context.Context, id pgtype.UUID) (*int64, error) {
	row := q.db.QueryRow(ctx, getAssetOwnerRef, id)
	var owner_user_ref *int64
	err := row.Scan(&owner_user_ref)
	return owner_user_ref, err
}

const getPost = `-- name: GetPost :one
SELECT id, author_user_ref, title, description, visibility, cover_asset_id,
       cover_thumbnail_asset_id, cover_focal_x, cover_focal_y,
       posted_at, like_count, comment_count,
       origin_server_id, team_id, state_id, created_at, updated_at,
       ai_provenance
FROM posts
WHERE id = $1 AND deleted_at IS NULL
`

type GetPostRow struct {
	ID                    pgtype.UUID
	AuthorUserRef         int64
	Title                 string
	Description           string
	Visibility            string
	CoverAssetID          pgtype.UUID
	CoverThumbnailAssetID pgtype.UUID
	CoverFocalX           *float64
	CoverFocalY           *float64
	PostedAt              pgtype.Timestamptz
	LikeCount             int64
	CommentCount          int64
	OriginServerID        pgtype.UUID
	TeamID                pgtype.UUID
	StateID               pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	AiProvenance          *string
}

// `ai_provenance` is DERIVED (#1167, ADR 0094) — maintained by the
// triggers 00060 installs, never written by a request. It is selected
// HERE and in no other post query on purpose: every read path that
// renders a post — detail, browse, by-asset, the collection lateral —
// goes through fetchFullPost, so one projection serves all of them, and
// CreatePost/UpdatePost must NOT return it. Their RETURNING clause runs
// before the AFTER triggers that derive it, so the value they could
// report is the pre-membership one: null on every create. fetchFullPost
// re-reads after members are inserted, which is where the truth is.
func (q *Queries) GetPost(ctx context.Context, id pgtype.UUID) (GetPostRow, error) {
	row := q.db.QueryRow(ctx, getPost, id)
	var i GetPostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorUserRef,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.CoverAssetID,
		&i.CoverThumbnailAssetID,
		&i.CoverFocalX,
		&i.CoverFocalY,
		&i.PostedAt,
		&i.LikeCount,
		&i.CommentCount,
		&i.OriginServerID,
		&i.TeamID,
		&i.StateID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AiProvenance,
	)
	return i, err
}

const getPostDeletedBy = `-- name: GetPostDeletedBy :one
SELECT deleted_by_user_ref
  FROM posts
 WHERE id = $1 AND deleted_at IS NOT NULL
`

// Who soft-deleted this post. pgx.ErrNoRows when the row is live or
// absent — the two cases the restore path already conflates.
func (q *Queries) GetPostDeletedBy(ctx context.Context, id pgtype.UUID) (*int64, error) {
	row := q.db.QueryRow(ctx, getPostDeletedBy, id)
	var deleted_by_user_ref *int64
	err := row.Scan(&deleted_by_user_ref)
	return deleted_by_user_ref, err
}

const getPostInitialStateID = `-- name: GetPostInitialStateID :one
SELECT id FROM workflow_states WHERE domain = $1 AND is_initial = TRUE LIMIT 1
`

// The domain's entry-point state (`is_initial`), used for a post that
// is created already published. Asked by name rather than assumed to be
// 'published' so an install that moved its entry point is obeyed; a
// partial unique index guarantees at most one row per domain.
func (q *Queries) GetPostInitialStateID(ctx context.Context, domain string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPostInitialStateID, domain)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getWorkflowStateIDByCode = `-- name: GetWorkflowStateIDByCode :one
SELECT id FROM workflow_states WHERE domain = $1 AND code = $2
`

type GetWorkflowStateIDByCodeParams struct {
	Domain string
	Code   string
}

// Resolve one workflow state's id from its stable (domain, code) key
// — for posts, ('post','published') and ('post','wip') (ADR 0091
// decision 7). UNIQUE (domain, code), so this is one index probe.
//
// This package reads the row rather than caching the UUID because a
// cached id is silently wrong the first time an install reseeds its
// state machine, and "silently wrong" here means every post looks like
// a draft. It is asked once per create and once per cache MISS on the
// read path, never per row.
func (q *Queries) GetWorkflowStateIDByCode(ctx context.Context, arg GetWorkflowStateIDByCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getWorkflowStateIDByCode, arg.Domain, arg.Code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listPostAcls = `-- name: ListPostAcls :many


SELECT post_id, principal_type, principal_id, permission,
       granted_at, granted_by_user_ref, expires_at
FROM post_acls
WHERE post_id = $1
ORDER BY granted_at DESC, principal_type, principal_id, permission
`

// ListCollectionPostsPage was DELETED here (#661, epic #665). It listed
// a collection's pinned posts with `p.deleted_at IS NULL` as its only
// post-side condition — no visibility rule at all — and nothing in the
// tree called it: no handler, no test, and its generated row/param
// types were referenced nowhere. An unused query that would leak every
// private post in a collection the day somebody wired it up is not a
// head start, it is a trap; deleting it is strictly better than
// auditing it. A future collection-posts listing must go through
// the post read rule (posts.readRuleSQL) the way ListPostsByAssetGated does.
// ---------------------------------------------------------------------------
// ACLs (Phase 1.7.B-7b)
// ---------------------------------------------------------------------------
// All ACL rows on a post, newest first. The handler filters expired
// rows out of effective-access checks; this endpoint shows them so
// admins can see "X had read access until last week".
func (q *Queries) ListPostAcls(ctx context.Context, postID pgtype.UUID) ([]PostAcl, error) {
	rows, err := q.db.Query(ctx, listPostAcls, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostAcl
	for rows.Next() {
		var i PostAcl
		if err := rows.Scan(
			&i.PostID,
			&i.PrincipalType,
			&i.PrincipalID,
			&i.Permission,
			&i.GrantedAt,
			&i.GrantedByUserRef,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostAssets = `-- name: ListPostAssets :many
SELECT pa.post_id, pa.asset_id, pa.sort_order, pa.added_at,
       a.title, a.description, a.asset_type, a.owner_user_ref,
       a.status, a.file_hash, a.file_extension, a.file_size_bytes,
       a.metadata, a.ai_provenance, a.created_at AS asset_created_at,
       a.updated_at AS asset_updated_at
FROM post_assets pa
JOIN assets a ON a.id = pa.asset_id
WHERE pa.post_id = $1 AND a.deleted_at IS NULL
ORDER BY pa.sort_order ASC, pa.added_at ASC
`

type ListPostAssetsRow struct {
	PostID         pgtype.UUID
	AssetID        pgtype.UUID
	SortOrder      int32
	AddedAt        pgtype.Timestamptz
	Title          string
	Description    string
	AssetType      int64
	OwnerUserRef   *int64
	Status         string
	FileHash       *string
	FileExtension  *string
	FileSizeBytes  *int64
	Metadata       []byte
	AiProvenance   *string
	AssetCreatedAt pgtype.Timestamptz
	AssetUpdatedAt pgtype.Timestamptz
}

// Members of a post, in display order, joined onto the asset row so
// the API can return the full member shape in one call (no N+1).
//
// `a.ai_provenance` is the MEMBER'S OWN declaration (#1243, ADR 0094),
// and it is not the same fact as the post's derived `ai_provenance`.
// The post's answers "does this contain AI?" over the whole
// contributor set; this one answers it about the file the reader is
// actually looking at, which is what the viewer labels. A mixed post —
// one declared member beside one undeclared — carries `generated` at
// the post level and must NOT paint both members with it. NULL here
// means UNDECLARED, never `none`.
func (q *Queries) ListPostAssets(ctx context.Context, postID pgtype.UUID) ([]ListPostAssetsRow, error) {
	rows, err := q.db.Query(ctx, listPostAssets, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPostAssetsRow
	for rows.Next() {
		var i ListPostAssetsRow
		if err := rows.Scan(
			&i.PostID,
			&i.AssetID,
			&i.SortOrder,
			&i.AddedAt,
			&i.Title,
			&i.Description,
			&i.AssetType,
			&i.OwnerUserRef,
			&i.Status,
			&i.FileHash,
			&i.FileExtension,
			&i.FileSizeBytes,
			&i.Metadata,
			&i.AiProvenance,
			&i.AssetCreatedAt,
			&i.AssetUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPostTags = `-- name: ListPostTags :many

SELECT tag FROM post_tags WHERE post_id = $1 ORDER BY tag
`

// ---------------------------------------------------------------------------
// post_tags
// ---------------------------------------------------------------------------
func (q *Queries) ListPostTags(ctx context.Context, postID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listPostTags, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postIDsForAsset = `-- name: PostIDsForAsset :many
SELECT post_id FROM post_assets WHERE asset_id = $1
`

// Every post that lists this asset as a member. Drives cache
// invalidation when the ASSET changes in a way that changes what
// ListPostAssets returns — soft-delete and restore, which flip the
// `a.deleted_at IS NULL` half of that join without touching any post
// row (#920). No visibility filter: this answers "whose cached copy is
// now wrong", which is every holder, not just the ones a given reader
// may see.
func (q *Queries) PostIDsForAsset(ctx context.Context, assetID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, postIDsForAsset, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var post_id pgtype.UUID
		if err := rows.Scan(&post_id); err != nil {
			return nil, err
		}
		items = append(items, post_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCollectionPost = `-- name: RemoveCollectionPost :exec
DELETE FROM collection_posts WHERE collection_id = $1 AND post_id = $2
`

type RemoveCollectionPostParams struct {
	CollectionID pgtype.UUID
	PostID       pgtype.UUID
}

func (q *Queries) RemoveCollectionPost(ctx context.Context, arg RemoveCollectionPostParams) error {
	_, err := q.db.Exec(ctx, removeCollectionPost, arg.CollectionID, arg.PostID)
	return err
}

const removePostAcl = `-- name: RemovePostAcl :execrows
DELETE FROM post_acls
WHERE post_id = $1
  AND principal_type = $2
  AND principal_id   = $3
  AND permission     = $4
`

type RemovePostAclParams struct {
	PostID        pgtype.UUID
	PrincipalType string
	PrincipalID   string
	Permission    string
}

func (q *Queries) RemovePostAcl(ctx context.Context, arg RemovePostAclParams) (int64, error) {
	result, err := q.db.Exec(ctx, removePostAcl,
		arg.PostID,
		arg.PrincipalType,
		arg.PrincipalID,
		arg.Permission,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removePostAsset = `-- name: RemovePostAsset :exec
DELETE FROM post_assets WHERE post_id = $1 AND asset_id = $2
`

type RemovePostAssetParams struct {
	PostID  pgtype.UUID
	AssetID pgtype.UUID
}

func (q *Queries) RemovePostAsset(ctx context.Context, arg RemovePostAssetParams) error {
	_, err := q.db.Exec(ctx, removePostAsset, arg.PostID, arg.AssetID)
	return err
}

const removePostTag = `-- name: RemovePostTag :exec
DELETE FROM post_tags WHERE post_id = $1 AND tag = $2
`

type RemovePostTagParams struct {
	PostID pgtype.UUID
	Tag    string
}

func (q *Queries) RemovePostTag(ctx context.Context, arg RemovePostTagParams) error {
	_, err := q.db.Exec(ctx, removePostTag, arg.PostID, arg.Tag)
	return err
}

const replacePostTags = `-- name: ReplacePostTags :exec
WITH wipe AS (
    DELETE FROM post_tags WHERE post_id = $1
)
INSERT INTO post_tags (post_id, tag)
SELECT $1, unnest($2::TEXT[])
ON CONFLICT (post_id, tag) DO NOTHING
`

type ReplacePostTagsParams struct {
	PostID  pgtype.UUID
	Column2 []string
}

// Wipes and refills the tag set in one transaction. Called by
// UpdatePost when the body sends a `tags` array.
func (q *Queries) ReplacePostTags(ctx context.Context, arg ReplacePostTagsParams) error {
	_, err := q.db.Exec(ctx, replacePostTags, arg.PostID, arg.Column2)
	return err
}

const softDeletePost = `-- name: SoftDeletePost :exec
UPDATE posts SET deleted_at = NOW(), deleted_reason = $2, deleted_by_user_ref = $3, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type SoftDeletePostParams struct {
	ID               pgtype.UUID
	DeletedReason    *string
	DeletedByUserRef *int64
}

// deleted_by_user_ref: see the note on assets.SoftDeleteAsset. The
// restore gate reads it, so every soft-delete path has to write it.
func (q *Queries) SoftDeletePost(ctx context.Context, arg SoftDeletePostParams) error {
	_, err := q.db.Exec(ctx, softDeletePost, arg.ID, arg.DeletedReason, arg.DeletedByUserRef)
	return err
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET
    title                    = COALESCE($1,                    title),
    description              = COALESCE($2,              description),
    visibility               = COALESCE($3,               visibility),
    cover_asset_id           = COALESCE($4,           cover_asset_id),
    cover_thumbnail_asset_id = COALESCE($5, cover_thumbnail_asset_id),
    state_id                 = COALESCE($6,                 state_id),
    cover_focal_x            = CASE WHEN $7::BOOLEAN THEN NULL
                                    WHEN $8::DOUBLE PRECISION IS NOT NULL
                                         THEN $8::DOUBLE PRECISION
                                    WHEN $4::UUID IS NOT NULL
                                         AND $4::UUID IS DISTINCT FROM cover_asset_id
                                         THEN NULL
                                    ELSE cover_focal_x END,
    cover_focal_y            = CASE WHEN $7::BOOLEAN THEN NULL
                                    WHEN $9::DOUBLE PRECISION IS NOT NULL
                                         THEN $9::DOUBLE PRECISION
                                    WHEN $4::UUID IS NOT NULL
                                         AND $4::UUID IS DISTINCT FROM cover_asset_id
                                         THEN NULL
                                    ELSE cover_focal_y END,
    updated_at               = NOW()
WHERE id = $10 AND deleted_at IS NULL
RETURNING id, author_user_ref, title, description, visibility, cover_asset_id,
          cover_thumbnail_asset_id, cover_focal_x, cover_focal_y,
          posted_at, like_count, comment_count,
          origin_server_id, team_id, state_id, created_at, updated_at
`

type UpdatePostParams struct {
	Title                 *string
	Description           *string
	Visibility            *string
	CoverAssetID          pgtype.UUID
	CoverThumbnailAssetID pgtype.UUID
	StateID               pgtype.UUID
	ClearCoverFocal       bool
	CoverFocalX           *float64
	CoverFocalY           *float64
	ID                    pgtype.UUID
}

type UpdatePostRow struct {
	ID                    pgtype.UUID
	AuthorUserRef         int64
	Title                 string
	Description           string
	Visibility            string
	CoverAssetID          pgtype.UUID
	CoverThumbnailAssetID pgtype.UUID
	CoverFocalX           *float64
	CoverFocalY           *float64
	PostedAt              pgtype.Timestamptz
	LikeCount             int64
	CommentCount          int64
	OriginServerID        pgtype.UUID
	TeamID                pgtype.UUID
	StateID               pgtype.UUID
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

// COALESCE-based partial update — NULL args keep current values.
// The focal pair needs a CASE rather than a bare COALESCE, for the
// reason UpdateCollection's pairs do: COALESCE cannot express "set this
// back to NULL", so clearing a crop is an explicit flag. Both axes read
// the SAME flag, because a focal point is a point and clearing half of
// one is not a state the column CHECK admits.
//
// #1333: AND a focal point does not outlive the picture it was chosen
// against. A fraction of the way across one photograph means nothing on
// the next one, so a cover swap that left the old pair in place framed
// the new picture on a point nobody picked, silently and forever. The
// third CASE arm below is that rule: the cover changed and the caller
// said nothing about framing, so the framing goes.
//
// Arm ORDER is the whole correctness argument, because the arms overlap.
//  1. the explicit clear flag wins outright;
//  2. a SUPPLIED value wins over the swap rule. This is the case both
//     editors actually take, since they save the new cover and its new
//     focal point in one PATCH, and a rule that cleared on any cover
//     change would throw that value away while still passing a
//     single-field test;
//  3. only then, a cover that genuinely CHANGED clears the pair.
//     `IS DISTINCT FROM` rather than `IS NOT NULL`, so a client that
//     round-trips the whole object and re-sends the SAME cover id is
//     not a swap and keeps its framing;
//  4. otherwise the stored value stands.
//
// Both axes read the same arms, so the pair can never half-clear into a
// posts_cover_focal_check violation.
func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (UpdatePostRow, error) {
	row := q.db.QueryRow(ctx, updatePost,
		arg.Title,
		arg.Description,
		arg.Visibility,
		arg.CoverAssetID,
		arg.CoverThumbnailAssetID,
		arg.StateID,
		arg.ClearCoverFocal,
		arg.CoverFocalX,
		arg.CoverFocalY,
		arg.ID,
	)
	var i UpdatePostRow
	err := row.Scan(
		&i.ID,
		&i.AuthorUserRef,
		&i.Title,
		&i.Description,
		&i.Visibility,
		&i.CoverAssetID,
		&i.CoverThumbnailAssetID,
		&i.CoverFocalX,
		&i.CoverFocalY,
		&i.PostedAt,
		&i.LikeCount,
		&i.CommentCount,
		&i.OriginServerID,
		&i.TeamID,
		&i.StateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
