// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sysconfig

import (
	"context"
)

const deleteSystemConfig = `-- name: DeleteSystemConfig :exec
DELETE FROM system_config WHERE key = $1
`

func (q *Queries) DeleteSystemConfig(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteSystemConfig, key)
	return err
}

const getSystemConfig = `-- name: GetSystemConfig :one
SELECT key, value, updated_at
FROM system_config
WHERE key = $1
`

// Returns the raw JSONB blob stored under key. Callers deserialize
// into the typed struct that owns the key.
func (q *Queries) GetSystemConfig(ctx context.Context, key string) (SystemConfig, error) {
	row := q.db.QueryRow(ctx, getSystemConfig, key)
	var i SystemConfig
	err := row.Scan(&i.Key, &i.Value, &i.UpdatedAt)
	return i, err
}

const listSystemConfigByPrefix = `-- name: ListSystemConfigByPrefix :many
SELECT key, value
FROM system_config
WHERE starts_with(key, $1::TEXT)
ORDER BY key
`

type ListSystemConfigByPrefixRow struct {
	Key   string
	Value []byte
}

// Every config row whose key starts with the given literal prefix, in
// key order. Used to load the scalar `jobs.type_concurrency.<type>`
// caps, which are stored one-row-per-type rather than as a single JSON
// blob. starts_with matches the prefix literally (no LIKE wildcards).
func (q *Queries) ListSystemConfigByPrefix(ctx context.Context, prefix string) ([]ListSystemConfigByPrefixRow, error) {
	rows, err := q.db.Query(ctx, listSystemConfigByPrefix, prefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemConfigByPrefixRow
	for rows.Next() {
		var i ListSystemConfigByPrefixRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemConfig = `-- name: UpsertSystemConfig :exec
INSERT INTO system_config (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET
    value      = EXCLUDED.value,
    updated_at = NOW()
`

type UpsertSystemConfigParams struct {
	Key   string
	Value []byte
}

// Idempotent write. updated_at refreshes on every write so audit and
// monitoring can see when settings drift.
func (q *Queries) UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) error {
	_, err := q.db.Exec(ctx, upsertSystemConfig, arg.Key, arg.Value)
	return err
}
