// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outbox

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceDispatchCursor = `-- name: AdvanceDispatchCursor :exec
UPDATE federation_dispatch_state
   SET last_dispatched_activity_id = $1,
       last_dispatched_at          = NOW(),
       updated_at                  = NOW()
 WHERE id = 1
`

// Cursor advance happens in the SAME transaction as the
// outbox INSERTs from the same batch (per design §3.7).
func (q *Queries) AdvanceDispatchCursor(ctx context.Context, lastDispatchedActivityID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, advanceDispatchCursor, lastDispatchedActivityID)
	return err
}

const cancelOutboxByPeer = `-- name: CancelOutboxByPeer :execrows
UPDATE federation_outbox
   SET status     = 'cancelled',
       last_error = 'peer defederation cascade',
       updated_at = NOW()
 WHERE peer_id = $1 AND status = 'queued'
`

// Defederation cascade: cancel every queued row for a peer.
// Returns the count for the audit row.
func (q *Queries) CancelOutboxByPeer(ctx context.Context, peerID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, cancelOutboxByPeer, peerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOutboxByStatusByPeer = `-- name: CountOutboxByStatusByPeer :many
SELECT peer_id, status, COUNT(*) AS n
FROM federation_outbox
GROUP BY peer_id, status
ORDER BY peer_id, status
`

type CountOutboxByStatusByPeerRow struct {
	PeerID pgtype.UUID
	Status string
	N      int64
}

// Admin queue-summary metrics: how many queued / sent /
// failed / cancelled per peer.
func (q *Queries) CountOutboxByStatusByPeer(ctx context.Context) ([]CountOutboxByStatusByPeerRow, error) {
	rows, err := q.db.Query(ctx, countOutboxByStatusByPeer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOutboxByStatusByPeerRow
	for rows.Next() {
		var i CountOutboxByStatusByPeerRow
		if err := rows.Scan(&i.PeerID, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDispatchState = `-- name: GetDispatchState :one

SELECT id, last_dispatched_activity_id, last_dispatched_at, updated_at
FROM federation_dispatch_state
WHERE id = 1
`

// --- dispatch_state ---------------------------------------------------
// The single cursor row. NULL last_dispatched_activity_id means
// "no activities dispatched yet" — first tick processes
// everything from the beginning.
func (q *Queries) GetDispatchState(ctx context.Context) (FederationDispatchState, error) {
	row := q.db.QueryRow(ctx, getDispatchState)
	var i FederationDispatchState
	err := row.Scan(
		&i.ID,
		&i.LastDispatchedActivityID,
		&i.LastDispatchedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOutboxByID = `-- name: GetOutboxByID :one
SELECT id, activity_id, peer_id, target_user_url, status,
       attempts, next_attempt_at, last_attempt_at, last_error,
       sent_at, delivered_with_key_id, created_at, updated_at
FROM federation_outbox
WHERE id = $1
`

func (q *Queries) GetOutboxByID(ctx context.Context, id pgtype.UUID) (FederationOutbox, error) {
	row := q.db.QueryRow(ctx, getOutboxByID, id)
	var i FederationOutbox
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.PeerID,
		&i.TargetUserUrl,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastError,
		&i.SentAt,
		&i.DeliveredWithKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutboxRow = `-- name: InsertOutboxRow :one
INSERT INTO federation_outbox (
    activity_id, peer_id, target_user_url, status, next_attempt_at
)
VALUES ($1, $2, $3, 'queued', NOW())
ON CONFLICT DO NOTHING
RETURNING id, activity_id, peer_id, target_user_url, status,
          attempts, next_attempt_at, last_attempt_at, last_error,
          sent_at, delivered_with_key_id, created_at, updated_at
`

type InsertOutboxRowParams struct {
	ActivityID    pgtype.UUID
	PeerID        pgtype.UUID
	TargetUserUrl *string
}

// Idempotent via the partial UNIQUE indexes. ON CONFLICT DO
// NOTHING handles both targeted (target_user_url IS NOT NULL)
// + broadcast (NULL) flavours.
func (q *Queries) InsertOutboxRow(ctx context.Context, arg InsertOutboxRowParams) (FederationOutbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxRow, arg.ActivityID, arg.PeerID, arg.TargetUserUrl)
	var i FederationOutbox
	err := row.Scan(
		&i.ID,
		&i.ActivityID,
		&i.PeerID,
		&i.TargetUserUrl,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastAttemptAt,
		&i.LastError,
		&i.SentAt,
		&i.DeliveredWithKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueOutbox = `-- name: ListDueOutbox :many
SELECT id, activity_id, peer_id, target_user_url, status,
       attempts, next_attempt_at, last_attempt_at, last_error,
       sent_at, delivered_with_key_id, created_at, updated_at
FROM federation_outbox
WHERE status = 'queued'
  AND next_attempt_at <= NOW()
ORDER BY next_attempt_at
LIMIT $1
`

// Hot-path read for the delivery worker. Uses
// federation_outbox_due_idx (partial index on status='queued').
// Sorted by next_attempt_at so the oldest-due row goes first.
// Limited at the caller's batch size — the delivery worker
// defaults to 100 rows/tick.
func (q *Queries) ListDueOutbox(ctx context.Context, limit int32) ([]FederationOutbox, error) {
	rows, err := q.db.Query(ctx, listDueOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationOutbox
	for rows.Next() {
		var i FederationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.PeerID,
			&i.TargetUserUrl,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastError,
			&i.SentAt,
			&i.DeliveredWithKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueOutboxByPeer = `-- name: ListDueOutboxByPeer :many
SELECT id, activity_id, peer_id, target_user_url, status,
       attempts, next_attempt_at, last_attempt_at, last_error,
       sent_at, delivered_with_key_id, created_at, updated_at
FROM federation_outbox
WHERE status = 'queued'
  AND next_attempt_at <= NOW()
  AND peer_id = $1
ORDER BY next_attempt_at
LIMIT $2
`

type ListDueOutboxByPeerParams struct {
	PeerID pgtype.UUID
	Limit  int32
}

// Per-peer batching for the delivery worker. Pulls due rows
// for a SINGLE peer so the worker can fold them into one
// batched POST per the §3.10 batched-delivery optimisation.
func (q *Queries) ListDueOutboxByPeer(ctx context.Context, arg ListDueOutboxByPeerParams) ([]FederationOutbox, error) {
	rows, err := q.db.Query(ctx, listDueOutboxByPeer, arg.PeerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationOutbox
	for rows.Next() {
		var i FederationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.PeerID,
			&i.TargetUserUrl,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastError,
			&i.SentAt,
			&i.DeliveredWithKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxByPeer = `-- name: ListOutboxByPeer :many
SELECT id, activity_id, peer_id, target_user_url, status,
       attempts, next_attempt_at, last_attempt_at, last_error,
       sent_at, delivered_with_key_id, created_at, updated_at
FROM federation_outbox
WHERE peer_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListOutboxByPeerParams struct {
	PeerID pgtype.UUID
	Limit  int32
}

// Per-peer admin view. Most-recent first.
func (q *Queries) ListOutboxByPeer(ctx context.Context, arg ListOutboxByPeerParams) ([]FederationOutbox, error) {
	rows, err := q.db.Query(ctx, listOutboxByPeer, arg.PeerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FederationOutbox
	for rows.Next() {
		var i FederationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.PeerID,
			&i.TargetUserUrl,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastError,
			&i.SentAt,
			&i.DeliveredWithKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxForAdmin = `-- name: ListOutboxForAdmin :many
SELECT o.id, o.activity_id, o.peer_id, o.target_user_url,
       o.status, o.attempts, o.next_attempt_at, o.last_attempt_at,
       o.last_error, o.sent_at, o.delivered_with_key_id,
       o.created_at, o.updated_at,
       a.activity_type AS activity_type
FROM federation_outbox o
JOIN activities a ON a.id = o.activity_id
WHERE ($1::uuid IS NULL
       OR o.peer_id = $1::uuid)
  AND ($2::text IS NULL
       OR o.status = $2::text)
  AND ($3::text IS NULL
       OR a.activity_type = $3::text)
  AND ($4::timestamptz IS NULL
       OR o.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL
       OR (o.created_at, o.id) < (
           $5::timestamptz,
           $6::uuid
       ))
ORDER BY o.created_at DESC, o.id DESC
LIMIT $7::int
`

type ListOutboxForAdminParams struct {
	PeerID          pgtype.UUID
	Status          *string
	ActivityType    *string
	Since           pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        pgtype.UUID
	LimitN          int32
}

type ListOutboxForAdminRow struct {
	ID                 pgtype.UUID
	ActivityID         pgtype.UUID
	PeerID             pgtype.UUID
	TargetUserUrl      *string
	Status             string
	Attempts           int16
	NextAttemptAt      pgtype.Timestamptz
	LastAttemptAt      pgtype.Timestamptz
	LastError          string
	SentAt             pgtype.Timestamptz
	DeliveredWithKeyID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	ActivityType       string
}

// Filtered + paginated admin list for /admin/federation/outbox
// (Phase 1.22.D-c). All filters are optional (NULL = skip).
// Pagination uses (created_at, id) tuple via the cursor params
// — opaque to the client but deterministic so the next page
// doesn't skip or duplicate rows under concurrent inserts.
func (q *Queries) ListOutboxForAdmin(ctx context.Context, arg ListOutboxForAdminParams) ([]ListOutboxForAdminRow, error) {
	rows, err := q.db.Query(ctx, listOutboxForAdmin,
		arg.PeerID,
		arg.Status,
		arg.ActivityType,
		arg.Since,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.LimitN,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOutboxForAdminRow
	for rows.Next() {
		var i ListOutboxForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityID,
			&i.PeerID,
			&i.TargetUserUrl,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastAttemptAt,
			&i.LastError,
			&i.SentAt,
			&i.DeliveredWithKeyID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ActivityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUndispatchedActivities = `-- name: ListUndispatchedActivities :many
SELECT id, activity_uri, activity_type, actor_uri, actor_user_ref,
       object_uri, object_kind, object_local_id, target_uri,
       to_uris, cc_uris, bto_uris, bcc_uris, audience_uris,
       payload, signature_value, signature_pubkey, source,
       published_at, created_at
FROM activities
WHERE source = 'local'
  AND (
    $2::uuid IS NULL
    OR (created_at, id) > (
      (SELECT created_at FROM activities WHERE id = $2::uuid),
      $2::uuid
    )
  )
ORDER BY created_at, id
LIMIT $1
`

type ListUndispatchedActivitiesParams struct {
	Limit    int32
	CursorID pgtype.UUID
}

// Activities published after the cursor. The cursor itself is
// compared via (created_at, id) so multi-row-same-timestamp
// orderings stay correct. When the cursor's last_id is NULL
// (first run) we return EVERYTHING ordered by (created_at, id).
func (q *Queries) ListUndispatchedActivities(ctx context.Context, arg ListUndispatchedActivitiesParams) ([]Activity, error) {
	rows, err := q.db.Query(ctx, listUndispatchedActivities, arg.Limit, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.ActivityUri,
			&i.ActivityType,
			&i.ActorUri,
			&i.ActorUserRef,
			&i.ObjectUri,
			&i.ObjectKind,
			&i.ObjectLocalID,
			&i.TargetUri,
			&i.ToUris,
			&i.CcUris,
			&i.BtoUris,
			&i.BccUris,
			&i.AudienceUris,
			&i.Payload,
			&i.SignatureValue,
			&i.SignaturePubkey,
			&i.Source,
			&i.PublishedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxAttemptFailed = `-- name: MarkOutboxAttemptFailed :execrows
UPDATE federation_outbox
   SET attempts        = attempts + 1,
       next_attempt_at = $2,
       last_attempt_at = NOW(),
       last_error      = $3,
       updated_at      = NOW()
 WHERE id = $1 AND status = 'queued'
`

type MarkOutboxAttemptFailedParams struct {
	ID            pgtype.UUID
	NextAttemptAt pgtype.Timestamptz
	LastError     string
}

// Transient failure: bump attempts, schedule next_attempt_at
// per the §3.4 backoff schedule. Caller passes the computed
// next_attempt_at + the new error string.
func (q *Queries) MarkOutboxAttemptFailed(ctx context.Context, arg MarkOutboxAttemptFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxAttemptFailed, arg.ID, arg.NextAttemptAt, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxFailedTerminal = `-- name: MarkOutboxFailedTerminal :execrows
UPDATE federation_outbox
   SET status     = 'failed',
       last_attempt_at = NOW(),
       last_error = $2,
       updated_at = NOW()
 WHERE id = $1 AND status = 'queued'
`

type MarkOutboxFailedTerminalParams struct {
	ID        pgtype.UUID
	LastError string
}

// Permanent failure: status → failed. Caller invokes when the
// attempts cap is hit OR when the error is non-retryable
// (4xx that isn't 429).
func (q *Queries) MarkOutboxFailedTerminal(ctx context.Context, arg MarkOutboxFailedTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxFailedTerminal, arg.ID, arg.LastError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxSent = `-- name: MarkOutboxSent :execrows
UPDATE federation_outbox
   SET status     = 'sent',
       sent_at    = NOW(),
       last_attempt_at = NOW(),
       updated_at = NOW(),
       delivered_with_key_id = $2
 WHERE id = $1 AND status = 'queued'
`

type MarkOutboxSentParams struct {
	ID                 pgtype.UUID
	DeliveredWithKeyID *string
}

// Transition queued → sent on a successful delivery.
func (q *Queries) MarkOutboxSent(ctx context.Context, arg MarkOutboxSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxSent, arg.ID, arg.DeliveredWithKeyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requeueFailedOutbox = `-- name: RequeueFailedOutbox :execrows
UPDATE federation_outbox
   SET status          = 'queued',
       attempts        = 0,
       next_attempt_at = NOW(),
       last_attempt_at = NULL,
       updated_at      = NOW()
 WHERE id = $1 AND status = 'failed'
`

// Admin re-queue button (1.22.D-c). Resets the attempt count
// so the operator-driven retry starts fresh against the cap.
func (q *Queries) RequeueFailedOutbox(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, requeueFailedOutbox, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
