// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package teams

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Activity struct {
	ID              pgtype.UUID
	ActivityUri     string
	ActivityType    string
	ActorUri        string
	ActorUserRef    *int64
	ObjectUri       *string
	ObjectKind      *string
	ObjectLocalID   *string
	TargetUri       *string
	ToUris          []byte
	CcUris          []byte
	BtoUris         []byte
	BccUris         []byte
	AudienceUris    []byte
	Payload         []byte
	SignatureValue  *string
	SignaturePubkey *string
	Source          string
	PublishedAt     pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
}

type ApiToken struct {
	ID             pgtype.UUID
	UserRef        int64
	Name           string
	TokenHash      []byte
	Scopes         []string
	ExpiresAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
}

type Asset struct {
	ID                   pgtype.UUID
	Title                string
	Description          string
	AssetType            int64
	OwnerUserRef         *int64
	Status               string
	FileHash             *string
	FileExtension        *string
	FileSizeBytes        *int64
	Access               int32
	HasImage             bool
	IsTranscoding        bool
	Metadata             []byte
	OriginServerID       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
	DeletedAt            pgtype.Timestamptz
	SearchText           interface{}
	StateID              pgtype.UUID
	TeamID               pgtype.UUID
	ProcessingStatus     string
	Thumbhash            []byte
	ProcessingAttempts   int32
	ProcessingError      *string
	ProcessingStartedAt  pgtype.Timestamptz
	ProcessingFinishedAt pgtype.Timestamptz
	Sensitivity          string
}

type AssetAlternate struct {
	ID               pgtype.UUID
	AssetID          pgtype.UUID
	Label            string
	Kind             string
	ObjectHash       string
	ContentType      string
	SizeBytes        int64
	OriginServerID   pgtype.UUID
	CreatedByUserRef *int64
	CreatedAt        pgtype.Timestamptz
	Metadata         []byte
}

type AssetCompanion struct {
	ID            pgtype.UUID
	AssetID       pgtype.UUID
	CompanionPath string
	ObjectHash    string
	ContentType   string
	SizeBytes     int64
	CreatedAt     pgtype.Timestamptz
}

type AssetFieldValue struct {
	AssetID      pgtype.UUID
	FieldID      pgtype.UUID
	ValueText    *string
	ValueNum     *float64
	ValueDate    pgtype.Timestamptz
	ValueOptions []string
	// UUID reference value for ref-typed fields. The _ref suffix follows the table's local multi-type value-column convention (sibling to value_text / value_num / value_date / value_options), distinct from the schema-wide BIGINT-FK _ref rule.
	ValueRef     pgtype.UUID
	SetBy        string
	SetAt        pgtype.Timestamptz
	SetByUserRef *int64
}

type AssetFieldValueHistory struct {
	ID               pgtype.UUID
	AssetID          pgtype.UUID
	FieldID          pgtype.UUID
	OldValue         []byte
	NewValue         []byte
	ChangedAt        pgtype.Timestamptz
	ChangedByUserRef *int64
	SetBy            string
}

type AssetSubtitleTrack struct {
	AssetID      pgtype.UUID
	Lang         string
	Label        string
	FileHash     string
	SourceFormat string
	Confidence   float32
	CreatedAt    pgtype.Timestamptz
}

type AssetTag struct {
	AssetID pgtype.UUID
	Tag     string
	AddedAt pgtype.Timestamptz
}

type AssetType struct {
	Ref               int64
	Name              *string
	AllowedExtensions *string
	OrderBy           *int64
	ConfigOptions     *string
	PushMetadata      *int32
	Colour            *int64
	Icon              *string
	Tab               *int64
	PullImages        *int16
}

type AssetTypeAcl struct {
	AssetTypeRef     int64
	PrincipalType    string
	PrincipalID      string
	Permission       string
	GrantedAt        pgtype.Timestamptz
	GrantedByUserRef *int64
	ExpiresAt        pgtype.Timestamptz
}

type AuditEvent struct {
	ID             pgtype.UUID
	EventType      string
	OccurredAt     pgtype.Timestamptz
	SubjectUserRef *int64
	ActorUserRef   *int64
	Ip             *netip.Addr
	UserAgent      *string
	Metadata       []byte
}

type BrushPack struct {
	ID             pgtype.UUID
	OwnerUserRef   int64
	Name           string
	SourceFile     *string
	CreatedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
}

type BrushPackStamp struct {
	ID            pgtype.UUID
	PackID        pgtype.UUID
	AbrID         *string
	Label         *string
	Width         int32
	Height        int32
	StorageKey    string
	Spacing       float64
	AlignToPath   bool
	SizeJitter    *float64
	OpacityJitter *float64
	AngleJitter   *float64
	CreatedAt     pgtype.Timestamptz
}

type Capability struct {
	Code                   string
	Description            string
	CreatedAt              pgtype.Timestamptz
	RequiredLicenseFeature *string
}

type Collection struct {
	ID             pgtype.UUID
	OwnerUserRef   int64
	Name           string
	Description    string
	Visibility     string
	Membership     string
	ExpiresAt      pgtype.Timestamptz
	Featured       bool
	Purpose        *string
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type CollectionAcl struct {
	CollectionID     pgtype.UUID
	PrincipalType    string
	PrincipalID      string
	Permission       string
	GrantedAt        pgtype.Timestamptz
	GrantedByUserRef *int64
	ExpiresAt        pgtype.Timestamptz
}

type CollectionPost struct {
	CollectionID pgtype.UUID
	PostID       pgtype.UUID
	SortOrder    int32
	Pinned       bool
	ExpiresAt    pgtype.Timestamptz
	AddedAt      pgtype.Timestamptz
}

type CollectionResource struct {
	CollectionID pgtype.UUID
	AssetID      pgtype.UUID
	SortOrder    int32
	Pinned       bool
	ExpiresAt    pgtype.Timestamptz
	AddedAt      pgtype.Timestamptz
}

type Comment struct {
	ID             pgtype.UUID
	TargetKind     string
	TargetID       pgtype.UUID
	ParentID       pgtype.UUID
	RootID         pgtype.UUID
	Depth          int32
	AuthorUserRef  *int64
	Body           string
	BodyHtml       string
	AnnotationType *string
	AnnotationData []byte
	LikeCount      int64
	EditedAt       pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	PeerID         pgtype.UUID
	ActorUri       *string
	ActivityUri    *string
}

type DirectMessage struct {
	ID               pgtype.UUID
	SenderUserRef    int64
	RecipientUserRef int64
	Body             string
	SentAt           pgtype.Timestamptz
	ReadAt           pgtype.Timestamptz
	OriginServerID   pgtype.UUID
}

type FederationDirectory struct {
	ID                    pgtype.UUID
	DirectoryUrl          string
	OperatorName          string
	OperatorPublicKey     string
	OperatorFingerprint   string
	OperatorContact       string
	SubscribedAt          pgtype.Timestamptz
	SubscribedByUserRef   int64
	Enabled               bool
	LastPolledAt          pgtype.Timestamptz
	LastPollStatus        string
	LastPollError         string
	PollIntervalSeconds   int32
	Notes                 string
	PublishStatus         string
	PublishPendingToken   string
	PublishTokenExpiresAt pgtype.Timestamptz
	PublishRecordName     string
	PublishRecordValue    string
	PublishListingID      string
	PublishLastAttemptAt  pgtype.Timestamptz
	PublishLastError      string
	PublishDisplayName    string
	PublishRegion         string
	PublishDescription    string
	PublishTags           []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type FederationDirectoryEntry struct {
	ID                pgtype.UUID
	DirectoryID       pgtype.UUID
	InstanceUrl       string
	DisplayName       string
	InstancePublicKey string
	Fingerprint       string
	Region            string
	Description       string
	Tags              []byte
	VerifiedAt        pgtype.Timestamptz
	VerifiedVia       string
	ListingID         string
	CachedAt          pgtype.Timestamptz
}

type FederationDispatchState struct {
	ID                       int32
	LastDispatchedActivityID pgtype.UUID
	LastDispatchedAt         pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
}

type FederationInbox struct {
	ID                      pgtype.UUID
	ActivityUri             string
	PeerID                  pgtype.UUID
	ActorUri                string
	ActivityType            string
	ObjectKind              *string
	ObjectID                pgtype.UUID
	EnvelopeJson            []byte
	HttpSigKey              string
	ReceivedAt              pgtype.Timestamptz
	Status                  string
	RejectReason            *string
	DispatchAttempts        int32
	LastAttemptAt           pgtype.Timestamptz
	LastError               string
	ProcessedAt             pgtype.Timestamptz
	CorrelationActivityID   pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	WasEncrypted            bool
	DecryptedWithKeyVersion *int32
}

type FederationOutbox struct {
	ID                 pgtype.UUID
	ActivityID         pgtype.UUID
	PeerID             pgtype.UUID
	TargetUserUrl      *string
	Status             string
	Attempts           int16
	NextAttemptAt      pgtype.Timestamptz
	LastAttemptAt      pgtype.Timestamptz
	LastError          string
	SentAt             pgtype.Timestamptz
	DeliveredWithKeyID *string
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
	WasEncrypted       bool
	Sensitivity        *string
	RefusedReason      *string
}

type FederationPeer struct {
	ID                       pgtype.UUID
	InstanceUrl              string
	DisplayName              string
	InstancePublicKey        string
	TrustTier                string
	EncryptionPolicy         string
	Enabled                  bool
	Status                   string
	HandshakeAt              pgtype.Timestamptz
	HandshakeByUserRef       int64
	LastSeenAt               pgtype.Timestamptz
	Notes                    string
	ShareInVisibleList       bool
	CreatedAt                pgtype.Timestamptz
	UpdatedAt                pgtype.Timestamptz
	Capabilities             []byte
	CapabilitiesNegotiatedAt pgtype.Timestamptz
}

type FederationPeerSuggestion struct {
	ID                   pgtype.UUID
	SourcePeerID         pgtype.UUID
	SuggestedUrl         string
	SuggestedDisplayName string
	SuggestedPublicKey   string
	SuggestedFingerprint string
	CachedAt             pgtype.Timestamptz
}

type FederationRemoteActor struct {
	ActorUri                     string
	PeerID                       pgtype.UUID
	DisplayName                  string
	AvatarUrl                    string
	FirstSeenAt                  pgtype.Timestamptz
	LastSeenAt                   pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	EncryptionPublicKey          []byte
	EncryptionPublicKeyVersion   *int32
	EncryptionPublicKeyUpdatedAt pgtype.Timestamptz
}

type FederationShare struct {
	ID                pgtype.UUID
	GrantorUserRef    int64
	ObjectKind        string
	ObjectID          pgtype.UUID
	PeerID            pgtype.UUID
	TargetUserUrl     *string
	Scope             string
	ExpiresAt         pgtype.Timestamptz
	Notes             string
	GrantedActivityID pgtype.UUID
	GrantedAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
	RevokedActivityID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type FederationUserKey struct {
	UserRef          int64
	Version          int32
	Algorithm        string
	PublicKey        []byte
	PrivateKeyEnc    []byte
	IsCurrent        bool
	CreatedAt        pgtype.Timestamptz
	RetainedUntil    pgtype.Timestamptz
	RotatedAt        pgtype.Timestamptz
	RotatedByUserRef *int64
}

type FieldDefinition struct {
	ID                      pgtype.UUID
	Code                    string
	Label                   string
	Description             string
	Type                    string
	Options                 []byte
	Required                bool
	Searchable              bool
	AppliesTo               []int64
	FieldSetID              pgtype.UUID
	ReadCapability          *string
	WriteCapability         *string
	DisplayOrder            int32
	DisplayGroup            string
	Source                  []byte
	Status                  string
	DeprecatedReplacementID pgtype.UUID
	OriginServerID          pgtype.UUID
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	CreatedByUserRef        *int64
	UpdatedByUserRef        *int64
}

type Job struct {
	ID             pgtype.UUID
	Type           string
	Payload        []byte
	Status         string
	Priority       int32
	Attempts       int32
	MaxAttempts    int32
	ClaimedBy      *string
	ClaimedAt      pgtype.Timestamptz
	LeaseExpiresAt pgtype.Timestamptz
	LastError      *string
	Result         []byte
	OriginServerID pgtype.UUID
	ScheduledFor   pgtype.Timestamptz
	EnqueuedAt     pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
}

type Like struct {
	TargetKind string
	TargetID   pgtype.UUID
	UserRef    *int64
	LikedAt    pgtype.Timestamptz
	ID         pgtype.UUID
	PeerID     pgtype.UUID
	ActorUri   *string
}

type Notification struct {
	ID               pgtype.UUID
	RecipientUserRef int64
	ActorUserRef     *int64
	Verb             string
	TargetKind       *string
	TargetID         *string
	Payload          []byte
	ReadAt           pgtype.Timestamptz
	DeliveredAt      pgtype.Timestamptz
	EmailSentAt      pgtype.Timestamptz
	OriginServerID   pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type Post struct {
	ID                    pgtype.UUID
	AuthorUserRef         int64
	Title                 string
	Description           string
	Visibility            string
	CoverAssetID          pgtype.UUID
	PostedAt              pgtype.Timestamptz
	LikeCount             int64
	CommentCount          int64
	SearchText            interface{}
	OriginServerID        pgtype.UUID
	DeletedAt             pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	StateID               pgtype.UUID
	TeamID                pgtype.UUID
	CoverThumbnailAssetID pgtype.UUID
	SubtitleTrackOverride []byte
}

type PostAcl struct {
	PostID           pgtype.UUID
	PrincipalType    string
	PrincipalID      string
	Permission       string
	GrantedAt        pgtype.Timestamptz
	GrantedByUserRef *int64
	ExpiresAt        pgtype.Timestamptz
}

type PostAsset struct {
	PostID    pgtype.UUID
	AssetID   pgtype.UUID
	SortOrder int32
	AddedAt   pgtype.Timestamptz
}

type PostTag struct {
	PostID pgtype.UUID
	Tag    string
}

type Role struct {
	ID             pgtype.UUID
	ParentID       pgtype.UUID
	Name           string
	Description    string
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type RoleCapability struct {
	RoleID         pgtype.UUID
	CapabilityCode string
}

type Session struct {
	ID             pgtype.UUID
	UserRef        int64
	TokenHash      []byte
	CreatedAt      pgtype.Timestamptz
	LastUsedAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
	RevokedAt      pgtype.Timestamptz
	Ip             *netip.Addr
	UserAgent      *string
	OriginServerID pgtype.UUID
}

type StorageObject struct {
	Hash           string
	SizeBytes      int64
	ContentType    string
	Backend        string
	BackendBucket  *string
	OriginServerID pgtype.UUID
	GcEligibleAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type StoragePin struct {
	ObjectHash     string
	PinSubjectType string
	PinSubjectID   string
	CreatedAt      pgtype.Timestamptz
}

type StorageVariant struct {
	ObjectHash  string
	VariantKey  string
	SizeBytes   int64
	ContentType string
	Metadata    []byte
	CreatedAt   pgtype.Timestamptz
}

type SystemConfig struct {
	Key       string
	Value     []byte
	UpdatedAt pgtype.Timestamptz
}

type Team struct {
	ID             pgtype.UUID
	Slug           string
	Name           string
	Description    string
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type TeamClosure struct {
	AncestorID   pgtype.UUID
	DescendantID pgtype.UUID
	Depth        int32
}

type TeamMembership struct {
	TeamID         pgtype.UUID
	UserRef        int64
	AddedAt        pgtype.Timestamptz
	AddedByUserRef *int64
}

type TeamParent struct {
	ChildID  pgtype.UUID
	ParentID pgtype.UUID
}

type User struct {
	Ref                     int64
	Username                *string
	Password                *string
	Fullname                *string
	Email                   *string
	Usergroup               *int64
	LastActive              pgtype.Timestamptz
	AccountExpires          pgtype.Timestamptz
	Comments                *string
	PasswordLastChange      pgtype.Timestamptz
	Approved                int64
	Lang                    *string
	Created                 pgtype.Timestamptz
	PasswordResetHash       *string
	Origin                  *string
	ActorUri                *string
	SigningPublicKeyPem     *string
	SigningPrivateKeyEnc    []byte
	EncryptionPublicKey     []byte
	EncryptionPrivateKeyEnc []byte
}

type UserBlock struct {
	BlockerUserRef int64
	BlockedUserRef int64
	Reason         *string
	CreatedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
}

type UserCapabilityGrant struct {
	UserRef          int64
	CapabilityCode   string
	GrantedAt        pgtype.Timestamptz
	GrantedByUserRef *int64
	Note             string
	TeamID           pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
}

type UserCapabilityRevoke struct {
	UserRef          int64
	CapabilityCode   string
	RevokedAt        pgtype.Timestamptz
	RevokedByUserRef *int64
	Note             string
	TeamID           pgtype.UUID
	ExpiresAt        pgtype.Timestamptz
}

type UserFollow struct {
	FollowerUserRef int64
	FolloweeUserRef int64
	CreatedAt       pgtype.Timestamptz
	OriginServerID  pgtype.UUID
}

type UserPasswordHistory struct {
	ID             pgtype.UUID
	UserRef        int64
	PasswordHash   string
	ChangedAt      pgtype.Timestamptz
	OriginServerID pgtype.UUID
}

type UserPreference struct {
	UserRef              int64
	NotificationChannels []byte
	DefaultViews         []byte
	OriginServerID       pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type UserProfile struct {
	UserRef        int64
	DisplayName    *string
	Bio            string
	AvatarUrl      *string
	Location       string
	WebsiteUrl     *string
	SocialLinks    []byte
	OriginServerID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Language       string
	Theme          string
}

type UserRole struct {
	UserRef           int64
	RoleID            pgtype.UUID
	AssignedAt        pgtype.Timestamptz
	AssignedByUserRef *int64
	TeamID            pgtype.UUID
}

type WorkflowAudit struct {
	ID             pgtype.UUID
	ResourceKind   string
	ResourceID     pgtype.UUID
	FromStateID    pgtype.UUID
	ToStateID      pgtype.UUID
	ActorUserRef   *int64
	Note           string
	TransitionedAt pgtype.Timestamptz
}

type WorkflowState struct {
	ID               pgtype.UUID
	Domain           string
	Code             string
	Label            string
	SortOrder        int32
	IsInitial        bool
	IsTerminal       bool
	VisibleByDefault bool
	CreatedAt        pgtype.Timestamptz
	Icon             string
	Color            string
	RequiresNote     bool
}

type WorkflowTransition struct {
	ID                 pgtype.UUID
	FromStateID        pgtype.UUID
	ToStateID          pgtype.UUID
	RequiredCapability *string
	RequiresTeamScope  bool
}
